### ISSUE TITLE
Cmake fails when strictly following BUILD_INSTRUCTIONS

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/sirikali#1]
I tried compiling it by following the BUILD_INSTRUCTIONS, but got the following error message when running cmake:

```
~/Downloads/mhogomchungu-sirikali-7dc9fde/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DQT5=true -DNOSECRETSUPPORT=false -DINTERNAL_LXQT_WALLET=false -DNOKDESUPPORT=false -DCMAKE_BUILD_TYPE=RELEASE . ..
-- Checking for module 'pwquality'
--   No package 'pwquality' found
-- Checking for module 'lxqt-wallet'
--   No package 'lxqt-wallet' found
-- ERROR: could not find lxqt_wallet package
-- ---------------------------------------------------------------------------
-- lxqt wallet support will be provided by an internal library
-- ---------------------------------------------------------------------------
-- found gcrypt header file: /usr/include/gcrypt.h
-- found gcrypt library: /usr/lib/x86_64-linux-gnu/libgcrypt.so
-- 
--------------------------------------------------------------------------
-- kwallet support NOT found,will not build kwallet functionality
-- -----------------------------------------------------------------------
-- 
--------------------------------------------------------------------------
-- libsecret support found,will build libsecret functionality
-- -----------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- Building GUI components using Qt5
-- ---------------------------------------------------------------------------


-- Configuring done
-- Generating done
-- Build files have been written to: Downloads/mhogomchungu-sirikali-7dc9fde/build

```

**Comment by mhogomchungu** [comment]
There is no error there.

"pwquality" package was not found and hence the support for it is disabled meaning when creating a new volume,you will not be told how strong your password is.

external/system supplied "lxqt-wallet" package was not found and hence an internal copy of the package will be used instead.

Just type "make" to build the package and it will build just fine.

**Comment by smessmer** [comment]
Ok. Maybe BUILD_INSTRUCTIONS should be adapted?

Btw I tried compiling it on Mac but wasn't successful. Even with qt5 installed, cmake doesn't seem to find it. Did you try compiling it on Mac?

**Comment by mhogomchungu** [comment]
The project is currently linux only.

I dont have a mac and i have not put any though into porting it to other systems.

Porting the project to mac would need two things.

1. Mac version of libgcrypt and this seems to be doable since a mac version is present[1].An alternative is to disable secure storage of volume keys by disabling lxqt-wallet functionality.

2. Have a way of being informed about mount events.The current linux only implementation does this by monitory "/proc/self/mountinfo"[2]

[1] https://www.macports.org/ports.php?by=library&substr=libgcrypt
[2] https://github.com/mhogomchungu/sirikali/blob/master/src/mountinfo.cpp

**Comment by mhogomchungu** [comment]
I have updated build instruction documentations[1] to mention the two dependencies that were reported as not being found on your system.

[1] https://github.com/mhogomchungu/sirikali/commit/dbb367b314abb1b544a4f4a2d6f629fd576ed3f8

**Comment by mhogomchungu** [comment]
SiriKali is now functional on a mac: https://github.com/mhogomchungu/sirikali/issues/18
