### ISSUE TITLE
Portable release

### ISSUE THREAD

**Issue by Rundik** [mhogomchungu/sirikali#107]
It would be great to have portable release for windows so people don't have to use installer

**Comment by mhogomchungu** [comment]
Next version will be released on August 1st,2019(two days from today) and it will have a portable release.

**Comment by Rundik** [comment]
That's great news, can't wait see the new release

**Comment by mhogomchungu** [comment]
New version is out and you can get the portable version by downloading the one named "SiriKali-1.3.9.exe.zip".

https://github.com/mhogomchungu/sirikali/releases/tag/1.3.9
