### ISSUE TITLE
Add favorites and current mounts in tray menu

### ISSUE THREAD

**Issue by kzar79** [mhogomchungu/sirikali#108]
I have been a (happy) user of cryptkeeper for many years. Now I had to move from encfs to gocryptfs for security reasons, and I discovered this great piece of work, Sirikali.

One thing that was extremely useful in cryptkeeper was the ability to mount and unmount volumes directly from the tray icon. That is a great feature because it means only two clicks, while with the current Sirikali workflow it is three (+ locating the favorites button and scrolling it).

I don't know how complex it would be to add the possibility to mount and unmount directly from the tray menu. If you point me at the relevant pieces of code I can try to make it myself.

Another very very very useful feature would be to be able to add a (current) mounted volume to the favorites. You could just add a choice in the context menu on the mounted volume (open folder, unmount, *add to favorites*, ...).

**Comment by mhogomchungu** [comment]
Both are doable and will look into them.

**Comment by mhogomchungu** [comment]
The git version now supports showing favorite entries on the tray context menu with an ability to mount/unmount a volume simply by clicking its entry on the menu.

![Screenshot_20190813_184340](https://user-images.githubusercontent.com/3496115/62956658-01bbbd80-bdfc-11e9-8c05-9b814cd20343.png)

**Comment by mhogomchungu** [comment]
Both requests now exists in the git version.
