### ISSUE TITLE
Wallet Behaviour

### ISSUE THREAD

**Issue by rnc** [mhogomchungu/sirikali#109]
A few questions, potential issues:

1. Where are the keys stored (and how to manage them) if `Internal Wallet` is selected? Is the application managing it internally - running `lxqt_wallet-cli --wallets` shows nothing. 
  * When I go to Favourites / Mount All the key appears to have been saved _somewhere_ but I am not sure where.

2. When i select KWallet for the key storage there is nothing indicating that option has taken effect - I would have expected some form of 'current key storage is 'Internal Wallet | LibSecret | KWallet'

( Using sirikali-1.3.6-2.fc30.x86_64 )

**Comment by mhogomchungu** [comment]
Each application is expected to manage its own secrets when using internal wallet/lxqt_wallet. Wallets are stores in files in ```.~/.config/lxqt/wallets/$APPLICATION_NAME``` where ```$APPLICATION_NAME``` is a name of the application that owns the wallet.

Version 1.3.6 is a bit old. Most recent version have below window that shows what backend keys are automatically retrieved from and gives an option to change the backend.

The "key storage button" gives access to a specific backend when you to see all the SiriKali keys in that backend.

If you select KWallet, you should be able to get the same information using ```kwalletmanager``` and if you select libsecret, then ```seahorse``` program i believe should show the same information but it will be structured poorly.


![Screenshot_20190801_124745](https://user-images.githubusercontent.com/3496115/62283682-c4018100-b45a-11e9-9907-2d1763aeac3a.png)

**Comment by rnc** [comment]
Thanks for the reply! 

So the "Keys in Wallet" screen select where to get the key from, and the "Key Storage" simply allows management of keys within respective wallets. 

It looks like a new version is currently in testing for Fedora 30 ( https://bodhi.fedoraproject.org/updates/FEDORA-2019-472b2b328f ).

The curious thing is, I have deleted the `lxqt....` file but it still seems to be obtaining the key from somewhere (!) However, maybe this may be cleared up when the new version arrives.

**Comment by mhogomchungu** [comment]
You have to delete the file while SiriKali is not running.

Closing this one for now and feel free to reopen it when anything comes up.
