### ISSUE TITLE
Wishlist - Disable unavailable encryptors

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#11]
Add a visual indication in the Create Volume menu (dim?) if an encryptor is not available, with a note on why ("'EncFS' is not installed").

Currrently, you have to go through volume setup to get the message, and the recovery option may not be obvious to the user.

Several options are not available as packages.

**Comment by mhogomchungu** [comment]
Git version now has the behavior you want,screenshot below:

![screenshot_20160917_220847](https://cloud.githubusercontent.com/assets/3496115/18610369/add8786e-7d23-11e6-9536-5b071da5e4e4.png)
