### ISSUE TITLE
CMake Error [...] could not find gcrypt header file

### ISSUE THREAD

**Issue by marianoju** [mhogomchungu/sirikali#111]
While building the latest SiriKali from source in this GitHub repo (following instructions in [LINUX_BUILD_INSTRUCTIONS](https://github.com/mhogomchungu/sirikali/blob/master/LINUX_BUILD_INSTRUCTIONS)) on Ubuntu 18.04.3 I encountered an fatal error when executing `cmake`: 

```
CMake Error at CMakeLists.txt:104 (MESSAGE):
  could not find gcrypt header file


-- Configuring incomplete, errors occurred!
See also "/home/user/Setups/sirikali-master/build/CMakeFiles/CMakeOutput.log".
```

I was unable to locate a package of `libgcrypt-devel` but installing `libgcrypt11-dev` solved this issue.

**Comment by mhogomchungu** [comment]
In debian based systems, the development version of libgcrypt package is named ```libgcrypt11-dev``` or ```libgcrypt20-dev```.
