### ISSUE TITLE
error: ‘class QString’ has no member named ‘front’

### ISSUE THREAD

**Issue by marianoju** [mhogomchungu/sirikali#112]
While building the latest SiriKali from source in this GitHub repo (following instructions in [LINUX_BUILD_INSTRUCTIONS](https://github.com/mhogomchungu/sirikali/blob/master/LINUX_BUILD_INSTRUCTIONS)) on Ubuntu 18.04.3 I encountered an fatal error when executing `make -j$(nproc)`: 

```
...
[ 76%] Building CXX object CMakeFiles/sirikali.dir/src/help.cpp.o
/home/user/Setups/sirikali-master/src/keydialog.cpp: In lambda function:
/home/user/Setups/sirikali-master/src/keydialog.cpp:380:45: error: ‘class QString’ has no member named ‘front’
    auto ac = m->addAction( e.replace( 0,1,e.front().toUpper() ) ) ;
                                             ^~~~~
CMakeFiles/sirikali.dir/build.make:1105: recipe for target 'CMakeFiles/sirikali.dir/src/keydialog.cpp.o' failed
make[2]: *** [CMakeFiles/sirikali.dir/src/keydialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/sirikali.dir/all' failed
make[1]: *** [CMakeFiles/sirikali.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mhogomchungu** [comment]
Replace that "e.front()" with "e.at(0)"

Your version of Qt is below minimum expected. Will update the sources
sometimes next week to make it build on older version.

The oldest version of Qt supported should be in whatever is in debian 9.

**Comment by mhogomchungu** [comment]
SiriKali git version now builds with debian 8. Debian 8 is the minimum supported version.

**Comment by marianoju** [comment]
Thanks! :raised_hands:
