### ISSUE TITLE
Packaging: Proper ebuild for Gentoo/Linux

### ISSUE THREAD

**Issue by holgersson32644** [mhogomchungu/sirikali#113]
Hi,
thanks for developing and maintaining sirikali!

You provide an ebuild with your release which should compile, but has several outdated parts like the Qt4 support which was dropped in Gentoo a while a go as upstream does not maintain this old version anymore.

I updated the ebuild and put it into my overlay; you can find a mirror of it [here](https://github.com/holgersson32644/holgersson-overlay/commit/e9107f23bd01e7cd961fe83c414e577e21c376bd).
Feed free to add it to your next release or point to my [overlay](https://git.holgersson.xyz/foss/holgersson-overlay) or the mentioned mirror on github.com.

Have a nice day,
Nils

**Comment by mhogomchungu** [comment]
I do not know anything about overlays and gentoo.

Is "overlay" like a repository?
Is your overlay part of official gentoo project or its a private/personal one like ubuntu's ppa?

Somebody created the ebuild file i distribute a long time ago and it still contains those Qt4 parts because i don't know how to create/update it.

**Comment by holgersson32644** [comment]
Sorry, I assumed you know about it when you provide an ebuild :-)

Yes, you could see an overlay like a PPA. There are official ones for testing/experimental Ebuilds like ones from the Gentoo-KDE project and many unofficial ones from other Gentoo users like mine.

**Comment by mhogomchungu** [comment]
I plan to make a new release tomorrow and it will be nice if i could point to your ebuild while it has the updated version.

Do you monitor for new releases?
If not, how should i contact you to inform you of new releases?

**Comment by holgersson32644** [comment]
Thanks for reaching out; I monitor your release page now and you can contact me best by mail (see my profile for the address).

I think it will be best to link against my overlay mirror at github.com then.
However, for packaging I need the actual released files, so I suggest the following "workflow":
1. you create the releases
2. I update the ebuild and check everything is still fine around
3. I’ll drop you a note with the link to the ebuild (containing the commit ID)
4. you update the release page.

What do you think?

**Comment by mhogomchungu** [comment]
That sounds fine.

The new release is out: https://github.com/mhogomchungu/sirikali/releases/tag/1.4.0

**Comment by mhogomchungu** [comment]
I do not know anything about gentoo and its build system/packaging system so bear with me here.

How do these ebuild files work exactly?

A gentoo user will go to that link and do what exactly to get SiriKali installed/updated in their system?

Why is that link better than this[1] one? This one has more info and they can get the file you link to.

[1] https://github.com/holgersson32644/holgersson-overlay/tree/master/app-crypt/sirikali

**Comment by holgersson32644** [comment]
Sure. The ebuild file is kind of recipe written in bash which is parsed by the package manager "portage" in Gentoo[1]. If you know Archlinux you can compare it in some way to PKGBUILDs.
The main portage tree is a repository of such recipes and literally everyone can create overlays containing custom ebuilds to "lay it over" the main tree.

The most common and fastest way is to add my overlay, and install sirikali via the package manger.

I just pointed you to the exact ebuild within git commit ID, because you provided an ebuild the last releases and just copied that. The commit ID was there to ensure even in three years, when I have already deleted the old version, your link would point to a valid target.

Maybe instead you add a section "installing" with install instructions for different distros or put a note about it the github wiki for the sirikali repo.
There you could then say something like
Debian/Ubuntu: apt install sirikali
Archlinux: pacman -S sirikali
Gentoo: Add this overlay and install with emerge --ask sirikali
Fedora: ...
and so on. (Note that the entries here are just guesses for illustration - I did not check other distros!)

[1] side note: To stay precisely: There are other PM aswell, but portage is the default one.

**Comment by mhogomchungu** [comment]
Arch users already get it from here[1], after posting a new version, i go there and mark the previous version as out of date.

I have included your overlay info to the download page and i will create a wiki entry about different ways of installing SiriKali sometime in the near future.

Thanks for the offer of maintaining SiriKali for gentoo.

[1] https://aur.archlinux.org/packages/sirikali/

**Comment by mhogomchungu** [comment]
New version is out

**Comment by mhogomchungu** [comment]
I have added a link to your overlay in SiriKali main page under the section "binary packages for linux".

**Comment by holgersson32644** [comment]
Thanks!
