### ISSUE TITLE
unable to resize favorites window in HiDPI displays

### ISSUE THREAD

**Issue by akhilin** [mhogomchungu/sirikali#116]
I tried all DPI scale settings in windows 10 latest build. but no use.

Screenshot
![image](https://user-images.githubusercontent.com/21128035/64196970-961cbb80-cea2-11e9-910e-7b8471445e1e.png)

**Comment by mhogomchungu** [comment]
Its hard for me to test these things because i dont have the hardware.

You have a problem with this window only or with others? Can you also mention the rest of them if you know them.

Open the registry editor and then go to ```Computer\HKEY_CURRENT_USER\Software\SiriKali\SiriKali``` and then change the value of ```EnableHighDPIScalling``` to ```true``` and then restart SiriKali and see if it made a difference.

Also change the value of ```EnabledHighDpiScalingFactor``` key to higher numbers and then restart SiriKali and see if it makes a difference.

**Comment by akhilin** [comment]
tried these:
EnableHighDPIScalling 
EnabledHighDpiScalingFactor

not worked.

But I got a windows insider preview build yesterday...
It's not doing any scaling but windows are big now...
windows build: Version	10.0.18970 Build 18970

screenshot:
![image](https://user-images.githubusercontent.com/21128035/64269501-9925b380-cf57-11e9-98df-11fe810818c1.png)

**Comment by akhilin** [comment]
It's working now.
while testing HiDPI scaling I forgot to kill sirikali in task manager that's why settings not affected.


These are working perfectly.
EnabledHighDpiScalingFactor   1.1
EnableHighDPIScalling                 true

properties

![image](https://user-images.githubusercontent.com/21128035/64271301-b445f280-cf5a-11e9-88be-faca72dfb159.png)


Thank you

**Comment by mhogomchungu** [comment]
Thanks for the confirmation that the settings work.

I will expose those settings in the GUI within a day or two.

I meant to do it a while ago but totally forgot about it.

**Comment by mhogomchungu** [comment]
The git version now has a GUI way of setting the options.

![Screenshot_20190905_085446](https://user-images.githubusercontent.com/3496115/64316546-d45acd80-cfbd-11e9-8558-ca2f134e49ce.png)

**Comment by akhilin** [comment]
adding default value 1.1 would be helpful for basic users.

Thank you.

**Comment by mhogomchungu** [comment]
Done.

https://github.com/mhogomchungu/sirikali/commit/869a29bca8705061708608c538aa6f8e771c6c5f
