### ISSUE TITLE
Problem creating gocryptfs

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#12]
Attempting to create a gocryptfs volume yields the following error to stdout:

2016/10/09 22:50:27 Could not find fusermount binary: exec: "fusermount": executable file not found in $PATH

fusermount is in /usr/bin
cryfs mounts can be created
gocryptfs mounts can be created from the command line.

**Comment by mhogomchungu** [comment]
'Whats are the contents of your $PATH variable?

This is an internal error of gocryptfs and i dont think there is anything i can do to solve it,will open a bug report on gocrypt bug tracker to direct him here and i hope they can look into this with us.

**Comment by mhogomchungu** [comment]
It maybe useful to mention that you are using debian.

**Comment by mhogomchungu** [comment]
Can you also mention what version of gocryptfs you are using.

**Comment by rfjakob** [comment]
gocryptfs developer here. Hmm, that's a message from the go-fuse library, the gocryptfs version should not matter. It tries to find fusermount in $PATH, and, if that fails, in /bin:
https://github.com/hanwen/go-fuse/blob/master/fuse/mount_linux.go#L146

What is is $PATH set to?

**Comment by rfjakob** [comment]
Maybe replace the gocryptfs binary with this to find out what $PATH is actually definitely set to:
```
#!/bin/bash
echo "PATH=$PATH"
exec gocryptfs.bin "$@"
```

**Comment by davesteele** [comment]
The version of go-fuse in sid predates the lookPathFallback() function. The old version just calls LookPath(), with no fallback.

But, that should have been sufficient.

Also, creating and mounting a gocryptfs volume works fine from the CLI.

$ sirikali 
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.

-----
2016/10/10 12:17:12 Could not find fusermount binary: exec: "fusermount": executable file not found in $PATH

$ which fusermount
/bin/fusermount

$ dpkg --list | grep go-fuse
ii  golang-github-hanwen-go-fuse-dev                     0.0~git20150627.0.324ea17-1                                 all          Native Go bindings for the FUSE kernel module

$ gocryptfs foo bar
PATH=/home/daves/bin:/home/daves/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Password: 
Decrypting master key

Your master key is:

    406b6687-feb9986b-c53c4f75-9674456f-
    9c49f491-e71aef28-ef83b310-defb75bc

If the gocryptfs.conf file becomes corrupted or you ever forget your password,
there is only one hope for recovery: The master key. Print it to a piece of
paper and store it in a drawer.

Filesystem mounted and ready.

**Comment by rfjakob** [comment]
I have printed out the PATH variable from Go, and it's empty. I don't understand why bash is lying to us. Is it printing some kind of default value? Because it's not the same as the PATH you get when running gocryptfs manually.

Anyway this seems to fix it: https://github.com/rfjakob/sirikali/commit/abab48f0ce3cb84cbbf26a3aa1e36b125b2a82b7
