### ISSUE TITLE
Undefined MIME type?

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#121]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941456:

When running update-desktop-database, I get the following error message:
Error in file "/usr/share/applications/io.github.mhogomchungu.sirikali.desktop": "inode/directory:1" is an invalid MIME type ("inode/directory:1" contains an invalid character in the subtype)

Looking at the desktop file, it contains:

MimeType=inode/directory:1;

------------------------

This was added by 85217ccc

**Comment by mhogomchungu** [comment]
Perfect timing, i removed the addition and made a new release.

[1] https://github.com/mhogomchungu/sirikali/releases/tag/1.4.0
