### ISSUE TITLE
cryfs config file

### ISSUE THREAD

**Issue by lawmanuk** [mhogomchungu/sirikali#125]
Hi,

Is there any information on how to use config file for cryfs?

Can't find on cryfs github page or website.

Thanks

**Comment by mhogomchungu** [comment]
Below is everything i know about cryfs and its config file and i suspect the third entry answers your question.

1. The encryption/decryption key among other crypto properties are stored secured in a cryfs config.
2. The config file is stored in the root folder of cryfs volume by default and cryfs looks for it there by default.
3. If the config file is not in the default location, cryfs can be informed of where it is with "--config" option that specifies a path to where cryfs should look for the config file.
4. The whole of the config file is encrypted so you can't see anything in it without first decrypting it and as far a i know, cryfs is currently the only tool that can decrypt it.
5. SiriKali has GUI options to set the location of the config file if its not in the default location.

**Comment by lawmanuk** [comment]
I  misunderstood what you meant by config file options.   Didn't realise you were referring to the config file in base folder of cryfs.   thanks
