### ISSUE TITLE
cryptomator

### ISSUE THREAD

**Issue by lawmanuk** [mhogomchungu/sirikali#127]
Hi,

Are there any options for a cryptomator backend?

Would be great not to have to rely on cryptomator gui which isn't the best in linux, especially for automation.

thanks

**Comment by mhogomchungu** [comment]
SiriKali does not have a cryptomator backend and i am unlikely to add it for two reason.

1. Its just too different compared to all supported backends.
2. Support for it would be through cryptomator-cli[1] and the disclaimer on the project's page highly discourages using it.

[1] https://github.com/cryptomator/cli

**Comment by mhogomchungu** [comment]
Closing this one for lack of activity but feel free to post if anything comes up.

**Comment by yuufoqaxckbhwdibtd** [comment]
Hi,

It seems that there is a cli interface for cyberduck (https://duck.sh/) which seems to support Cryptomator vaults (https://trac.cyberduck.io/wiki/help/en/howto/cli#Cryptomator). Perhaps it can be used here instead of cryptomator cli

**Comment by mhogomchungu** [comment]
I just looked again at "cryptomator-cli" project[1] and it looks like the git version now FUSE based.

Will wait until they have a stable version out that is FUSE based and will probably support it.

[1]  https://github.com/cryptomator/cli

**Comment by mhogomchungu** [comment]
The git version now has support for cryptomator-cli. For now, you will have to build cryptomator from source using the following branch[1]. The branch has a fix for this[2] issue.

[1] https://github.com/ndob/cli/tree/fix_cpu_usage
[2] https://github.com/cryptomator/cli/issues/35

![Screenshot_20201012_134418](https://user-images.githubusercontent.com/3496115/95738943-b7013400-0c92-11eb-9045-422bba66dc5d.png)

![Screenshot_20201012_135347](https://user-images.githubusercontent.com/3496115/95738969-bec0d880-0c92-11eb-874b-96a21af0ae0b.png)
