### ISSUE TITLE
does sirikali work with sshfs-win using private/public key pair auth, or other more secure methods?

### ISSUE THREAD

**Issue by meeotch** [mhogomchungu/sirikali#128]
I read a comment by mhogomchungu - it might have been on the sshfs-win github, I don't recall - that sirikali was working with sshfs-win and "tested with keepass".  Does this mean that sirikali is able to work around the limitation that sshfs-win only works with password auth by default?  And if so, are there specific instructions somewhere about how to set that up?

I've got sirikali an sshfs-win working with password auth, but I'd really like to disable that and move to something more secure.

**Comment by mhogomchungu** [comment]
You must be refering to my comment here: https://github.com/billziss-gh/sshfs-win/issues/86#issuecomment-547089709

Steps for setting up SiriKali to work with sshfs are documented here[1] and the SiriKali screenshot that shows the windows where sshfs options can be set is below. 

These steps works the same in Linux and Windows and i am not aware of any limitation in sshfs-win that prevents it from working with other methods other than password authentication.

If you want sshfs-win to work with ```private/public key pair auth```, set the path  to your private key as specified in step 4. The path should not contain a space character in it.

If you want sshfs-win to work with KeePass 2, only tested with this one, then set the path as explained in step 3. I explained how to get the the key agent socket path in windows in the sshfs-win bug report i mentioned above.

In windows, i support connecting to ssh service using sshfs-win using:
1. Password authentication.
2. private/public key pair authentication.
3. KeePass 2 as source of authentication data,

[1] https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#90-how-do-i-add-options-to-connect-to-an-ssh-server

![Screenshot_20191105_203918](https://user-images.githubusercontent.com/3496115/68231743-ac630700-000c-11ea-8e8a-9af54a2b2b04.png)

**Comment by mhogomchungu** [comment]
Closing this one since i think the question is sufficiently answered. Feel free to post if anything else comes to mind.

**Comment by mhogomchungu** [comment]
Did you manage to connect using Key Agents or public key authentication?

If you, what errors are you getting?

**Comment by meeotch** [comment]
I haven't gotten it to work with key pair auth, unfortunately.  (Haven't tried key agent.)  I have a favorite saved that works fine with a password, and a key pair that works fine when running ssh from the command line.  But if I change the config to add the IdentityFile, and also click the "Volume Does Not Use A Password" box, I get errors:

`***************************
Backend took 5 seconds to finish
Generated backend output:
Permission denied, please try again.
Permission denied, please try again.
mitch@meeotch.farted.net: Permission denied (publickey,password).
read: Connection reset by peer

***************************
Exit Code: 1
Exit Status: 0
-------
StdOut: 
-------
StdError: Permission denied, please try again.
Permission denied, please try again.
user@domain.net: Permission denied (publickey,password).
read: Connection reset by peer
-------
Command: "C:\Program Files\SSHFS-Win\\bin\sshfs.exe" -f "user@domain.net:/mnt/X" "Z:"  -o rw,fsname=sshfs@"user@domain.net:/mnt/X",subtype=sshfs,idmap=user,StrictHostKeyChecking=no,port=22,IdentityFile=C:/Users/user/Documents/.ssh/id_rsa,volname="X"
`

And if I monitor /var/log/auth.log on the server, I can see that sshfs-win still seems to be attempting to connect with a password:
`Nov 10 20:52:57 server sshd[29739]: Failed password for user from 172.58.227.54 port 29388 ssh2
Nov 10 20:52:57 server sshd[29739]: Failed password for user from 172.58.227.54 port 29388 ssh2
Nov 10 20:52:57 server sshd[29739]: Connection closed by 172.58.227.54 [preauth]
`

**Comment by mhogomchungu** [comment]
lets get the obvious out of the way.
1. Did you enable the server to accept public key authentication.
2. Can you connect to the server with public key authentication using other tools?

**Comment by mhogomchungu** [comment]
Maybe you have multiple sshfs entries in favorites and you are not clicking the right one or SiriKali is ending up using a wrong one because of identical ssh addresses in favorites' list.

1. Try to add a completely new favorite entry that use the IdentifyFile.
2. This new favorites entry should have a completely unique ssh address. You can achieve this by using
a different remote folder path like using something else other than "/mnt/X".
3. Try again.

In my test here, SiriKali connected with this command
```
"C:\Program Files\SSHFS-Win\\bin\sshfs.exe" -f "ink@192.168.43.100:/home" "Y:"  -o rw,fsname=sshfs@"ink@192.168.43.100:/home",subtype=sshfs,idmap=user,StrictHostKeyChecking=no,IdentityFile=C:/Users/Ink/Desktop/ssh/id_rsa,volname="home"
```

and sshd on linux accepted the connection with below log entry
```
Nov 11 14:48:07 mtz sshd[14563]: Accepted publickey for ink from 192.168.43.10 port 49688 ssh2: RSA SHA256:<redacted>
Nov 11 14:48:07 mtz sshd[14563]: pam_unix(sshd:session): session opened for user ink by (uid=0)
```

**Comment by meeotch** [comment]
o.k. - I think I've got it at least partially figured out.  The key was experimenting with the command line copy-pasted from the sirikali debug window in a cmd shell.  

The first problem was some sort of Windows permissions issue.  The key file had the proper permissions according to cygwin, but due to some arcane Windows b.s., sshfs-win was reporting that the key file wasn't locked down enough.  I managed to fix it with a powershell command from here:  https://code.visualstudio.com/docs/remote/troubleshooting

The second problem was that I was using a key file that had a passphrase associated with it.  I'd either forgotten, or assumed that sirikali would prompt me for the passphrase.  Anyway, trying it again with a key file with no passphrase worked.

Interestingly, neither of these two problems were reflected in the sirikali debug window, they just showed up as timeouts.

I guess in order to use a key file with a passphrase, I'll have to set up keepass ssh agent?

**Comment by mhogomchungu** [comment]
SiriKali did not prompt for the passphrase because you checked "Volume Does Not Use A Password" option when adding the favorite's entry.

Uncheck the option and you will get the password prompt. I have not tested the keyfile that was associated with a passphrase but it should work because SiriKali will send both to sshfs-win.

**Comment by meeotch** [comment]
Yes - that's actually the first thing I tried, after discovering the passphrase problem.  It didn't seem to work (still got a backend timeout).

**Comment by mhogomchungu** [comment]
Will investigate this tomorrow.

**Comment by mhogomchungu** [comment]
SiriKali has a default 30 seconds timeout when using sshfs-win.

Google says its not possible to connect to ssh servers with password protected private key without using a key agent.

My tests here on Linux confirms what Google says, trying to do so without using a key agent and sshfs fails after a while with an error that says ```Timeout waiting for prompt```. Adding the key to the running key agent and things work as expected.

So, ssh has its own timeout but i don't know how long it is but it must be longer that SiriKali's timeout because you are hitting SiriKali's.

**Comment by meeotch** [comment]
Not sure what you mean by this, exactly:

> Google says its not possible to connect to ssh servers with password protected private key without using a key agent.

ssh definitely prompts for a passphrase, when there is one - it's how I connect to my server regularly.  In fact, sshfs-win also prompts for a passphrase, when run from a cmd shell.

Unfortunately, I've now run into another issue where I'm currently unable to mount by running *any* sshfs.exe command in a cmd shell...  Even just simple password-only mount commands that work fine when running via sirikali now fail when cut-and-pasted into a cmd shell.  /var/log/auth/log reveals that the password or key file is accepted on the server side, but then the connection just drops with "disconnected by user".  (Weirdly, "net use" still works for mounting.)

Anyway, I was able to verify that sshfs.exe will prompt for a passphrase, and correctly transmit the decrypted key to the server.  But I'm having a hard time testing anything beyond that, at the moment.

**Comment by mhogomchungu** [comment]
Sshfs on linux behaves the following in my tests.

1. I get a password prompt to enter a password when connecting to ssh using defaults.
2. I automatically get connected when i connect using a passwordless private key passed to sshfs using "IdentifyFile" argument.
3. Sshfs hangs and then error out with ```Timeout waiting for prompt``` when i attempt to connect using a ```password protected private key``` passed to sshfs using "IdentityFile" argument.
4. Sshfs automatically connects when a password protected private key if the key is first added to a key agent. Sshfs seems to take the key from the agent.

Are you saying that you do get a prompt when you attempt to connect using a password protected private key?

SiriKali does the same exact thing to both sshfs on Linux and sshfs-win on Windows.

**Comment by meeotch** [comment]
Yes, for point 3) above, both ssh (cygwin) and sshfs.exe (cmd shell) prompt for a passphrase, rather than timing out.  

Also, it seems that on ubuntu, that is the correct behavior for ssh:  http://manpages.ubuntu.com/manpages/xenial/man1/ssh.1.html

"If ssh needs a passphrase, it will read the passphrase from the current terminal if it was run from a terminal."

Oddly, on my Linux Mint installation, it seems to ignore the passphrase completely.  `ssh user@host -v -i keyfilewithpassphrase` gives:
```
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: .ssh/testkey
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
```

**Comment by mhogomchungu** [comment]
I get the prompt with ssh when connecting using password protected private key
```
[ink@mtz ~]$ ssh ink@mtz -i .ssh/passworded_key/id_rsa
Enter passphrase for key '.ssh/passworded_key/id_rsa': 
```

With sshfs on Linux, i also get the prompt if i remove ```password_stdin``` option.

**Comment by mhogomchungu** [comment]
My tests with sshfs on Linux and sshfs-win on Windows show consistent behaviors and these behaviors are the supported ones on Windows and Linux.

1. SiriKali works with password authentication.
2. SiriKali works with key agents and is tested with KeePass 2 on Windows.
3. SiriKali works with public/private key authentication if the private key is not password protected.
4. A password protected private key when doing public/private key authentication should first be loaded to a key agent and then SiriKali be configured to use the key agent.

If any of the above doesn't work then please open another issue to discuss it.
