### ISSUE TITLE
Remember Key

### ISSUE THREAD

**Issue by CurtisFeatures** [mhogomchungu/sirikali#131]
Hi,

Is there a way to remember the Key so I can have the drive automatically mapped with no user input? If I need to use a key file to do this then thats fine and I will have to try and figure out how to set this up. 

Thanks
Jamie

**Comment by mhogomchungu** [comment]
Steps to take to configure SiriKali to connect to ssh server using sshfs are documented here[1].

What you want is possible using public key authentication with a private key not password protected(Option 3).


[1] https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#90-how-do-i-add-options-to-connect-to-an-ssh-server

**Comment by fabeit** [comment]
I am sorry but I am getting lost with trying to store a password to connect mount an sftp drive through ssh. I would like for SiriKali to remember the Key so I don't have to type it, is creating a private key the only way to do it?

**Comment by mhogomchungu** [comment]
1. What version of SiriKali are you using?
2. You are using it on what OS?

**Comment by fabeit** [comment]
Sorry I should have specified. Version 1.4.3 and I am on Windows 10 64-bit

**Comment by mhogomchungu** [comment]
That ability will be in the next version[1] and i plan to release it on june first, 2020.

Will post a git based binary package within a few hours for you to use.

[1] https://github.com/mhogomchungu/sirikali/blob/9cc32f6f2c25449587bfdb137e42300d18f7d798/changelog#L219

**Comment by mhogomchungu** [comment]
You can get a binary package with the functionality from here: https://github.com/mhogomchungu/sirikali/releases/download/1.4.3/SiriKali-1.4.3-next-2020-05-13.setup.exe

Once you have it installed, do the following:
1. Click the favorites entry on the menu bar.
2. Select "Manage Favorites" on the generated menu list.
3. Click "Select Keys In Wallet" tab.
4. Select "windows' DPAPI" entry on the default wallet list.
5. A window will show up asking you to enter a password and enter the password you want to use to protect your login passwords you want SiriKali to manage for you. You will be asked for this password everytime SiriKali wants to access stored passwords. You can use an empty password you don't want to be bothered with the password prompt.
6. Enter Volume Path and Its Password in their respective places and then click "Add Volume To Selected Wallet".
7. Close the window.

SiriKali will now automatically read the saved password and add it to the mount dialog window.

The tab to select storage backend and to enter credentials to be saved look like below:

![Screenshot_20200514_141526](https://user-images.githubusercontent.com/3496115/81931963-948bc180-95f3-11ea-8c72-6873642acb04.png)

**Comment by fabeit** [comment]
Thank you! I will test this and get back to you

**Comment by fabeit** [comment]
So I have tried 
![image](https://user-images.githubusercontent.com/10210185/82154262-e4c18880-986c-11ea-8027-de76c9d2a7f2.png)

but then when I select Mount all it prompts the key
![image](https://user-images.githubusercontent.com/10210185/82154305-2a7e5100-986d-11ea-822a-f33a658977fc.png)

**Comment by mhogomchungu** [comment]
The path you have hidden in your second screen shot is the path you are supposed to add to the windows password storage system.

When can Sirikali automatically take the volume key from the storage system, you can have SiriKali automatically mount the volume or show the mount window with the password already filled in. The option to choose between these two options is in the settings window.

**Comment by fabeit** [comment]
I am sorry but I can't get it to work. I have tried all combination possible in the volume path but I am still prompted a password. I have tried
"user@ssh.mysite.com:/"
"ssh.mysite.com:/"
"user@ssh.mysite.com:/myfolder/"
"D:/user@ssh.mysite.com:/"

**Comment by mhogomchungu** [comment]
Lets start from the beginning.

1. Connect to a remove computer using SiriKali and SiriKali will add its entry to the main window, right click the entry and you see a context menu like image 1 below, on the context menu, click "Add To Favorites".

2. On the generated Window in picture 2, click on the button that number "2" is pointing at. You should see the text field to the left of the button has the same text as in the first column on the main window.

3. Click on the button at step 2 above will land you to a window like in picture 3. Make sure you have the default wallet set to what number "3" is pointing at. The field point to by number "4" should already be set. Put the password to the field pointed by number "5" and then press the button pointed by number "6" to add the entry to the wallet and then click "close" to close the window.

4. On the main window, select the entry then click "unmount" to unmount it and then mount it again to see if SiriKali can pick up the password automatically.

Picture 1
![11](https://user-images.githubusercontent.com/3496115/82212173-c87c2500-991a-11ea-849f-5f37928df61d.png)

Picture 2
![22](https://user-images.githubusercontent.com/3496115/82212738-b5b62000-991b-11ea-94c3-73dd432ac5ca.png)

Picture 3
![33](https://user-images.githubusercontent.com/3496115/82212954-104f7c00-991c-11ea-99d2-d3451499c86f.png)

**Comment by mhogomchungu** [comment]
I just discovered a bug when retrieving passwords with sshfs backend. Will fix it first and then post steps on how to use it.

**Comment by fabeit** [comment]
Sounds good, I will wait for the fix then.

**Comment by mhogomchungu** [comment]
Install this one[1] and try again
[1] https://github.com/mhogomchungu/sirikali/releases/download/1.4.3/SiriKali-1.4.3-next-2020-05-19.setup.exe

Steps to follow are below:

1. Make sure the default wallet is set to "Windows DPAPI" and your above screenshot shows you know how to set it.
2. Connect to the ssh server to have the volume show up on SiriKali main window.
3. Right click on the volume entry on the main window and then click "Add To Favorites" as seen in image 1 below
4. Above step will land you to a window as seen in image 2 below. Notice the volume path is already be set. Click the button pointed to by number "2".
5. Above step will land you to a window as seen in image 3 below. Notice the volume path is already set. Enter the password in the text field pointed to number "4" and then press the button pointed to by number "5".
6. Close the window.
7. Unmount the volume on the main window and mount it again and report if SiriKali successfully picked up the key from window's DPAPI.

Image 1
![1](https://user-images.githubusercontent.com/3496115/82354715-dceb1b00-9a09-11ea-927a-5a8784d6bee6.png)

Image 2
![2](https://user-images.githubusercontent.com/3496115/82355765-56373d80-9a0b-11ea-96cb-86087a71fddd.png)

Image 3
![3](https://user-images.githubusercontent.com/3496115/82355788-5f280f00-9a0b-11ea-8abe-925dd80c1822.png)

**Comment by fabeit** [comment]
thank you my friend, it is finally working. I'm not sure why but the first time I have tried it was not working. I uninstalled and then reinstalled I left the Windows wallet password blank but still not working. Then I tried again but I set a password for the wallet, this time it was working! I then set again the wallet password to blank and it worked, the password shows up when the volume mount dialog appears. I had set the volume to auto mount but I still have to click on "OK", and I asking too much in the volume can be mounted automatically without any interaction? If when I start SiriKali I need to mount many volumes I would need to click through OK for each one of them, so the process is not completely automated. Thanks again for your assistance!

**Comment by mhogomchungu** [comment]
To set SiriKali to automatically get a volume key from a password store and automatically mount a volume, uncheck the option pointed to by number 1 in image 1 below.

To set SiriKali to automatically get volume keys from a password store and automatically mount all volumes that are set to automount when it is starting up, set the option pointed to by number 2 in image 1 and set the automount option to true for each volume you want to automount at start up. Image 2 shows step to to toggle on/off the automount option.

Image 1
![1](https://user-images.githubusercontent.com/3496115/82493071-03838180-9af0-11ea-83e7-47bbd1cabbb2.png)

Image 2
![2](https://user-images.githubusercontent.com/3496115/82493663-ff0b9880-9af0-11ea-84d4-1bd4223881e5.png)

**Comment by fabeit** [comment]
thank you for your help things are getting better now and I'm able to get these mounted when Windows starts. There are still a few pickups, like the software needs to be completely closed and restarted, but I will able to report more specific bugs once I use it for a little longer. One problem might be with the auto-reconnect when the Internet connection goes down. thanks again

**Comment by mhogomchungu** [comment]
With the next version, clicking "mount all" will cause all volumes with the "auto mount" option set in their favorites entry and have passwords set in the default key store to auto mount.

**Comment by fabeit** [comment]
I see, is there anyway to have to volume re-connect after an internet disconnection or a wake from sleep?

**Comment by mhogomchungu** [comment]
sshfs seems to already be capable of doing what you want: https://serverfault.com/questions/6709/sshfs-mount-that-survives-disconnect/639735

**Comment by fabeit** [comment]
Good thinking, I did see that question before, so where do I add commands for sshf in Sirikali? -o reconnect and ServerAliveInterval=15. Can this go in the mount options?

**Comment by mhogomchungu** [comment]
Yes,  the mount option field should already have two entries, add the ones you want and separate them with a comma character.

**Comment by mhogomchungu** [comment]
Version 1.4.4 is out and i recommend you switch to it

https://github.com/mhogomchungu/sirikali/releases/tag/1.4.4

**Comment by fabeit** [comment]
Nice thank you. For now it is working well with what we did before. I will give a test to this new build.
