### ISSUE TITLE
Is this normal? Mounted as a drive rather than network location.

### ISSUE THREAD

**Issue by CurtisFeatures** [mhogomchungu/sirikali#132]
Not sure if you can help me but here is some background:

Iv got some application which check in a network share for updated versions of itself as well as reading and writing other files it uses. We have a customer that wants to disable port 445 which is what our app uses. This is why I am looking into mapping a drive over SSH.

Iv used a program called SFTPDrive which mounts the SSH share to a mapped drive and everything works. The app can check and pull updates as well are read and write files to sub folders. I cant see any issues with our software at all.

When I use SSHFS and Sirikali it mounts the drive as a local drive (not network drive) - Not sure if this is relevant. The reading and writing of sub files and folders is working fine. however when I start my application it's complaining it can't access its "update" location to check for new files. Which makes no sense as it works using the SFTPDrive  software.

Just wondering if you had any ideas to look into this?

**Comment by mhogomchungu** [comment]
I do not know if there are differences between a network drive and a local drive.

sshfs-win creates a local drive when used the way SiriKali is using it and it creates a network drive when used through the "net" command.

Open cmd.exe and then run sshfs through the net command with something like below and check if the problem is still there

```
net use X: \\sshfs\XYZ@REMOVE_ADDRESS
```

**Comment by mhogomchungu** [comment]
Its possible to make SiriKali create a network drive instead of a local drive. To do so, create an sshfs favorite's entry and then add mount option of```--VolumePrefix=\mysshfs\XYZ``` where ```XYZ``` is a string of your choice.

I just found out about it here: https://github.com/billziss-gh/sshfs-win/issues/125

**Comment by CurtisFeatures** [comment]
Hi,

I wasn't having much luck getting anything to mount using the net command which is strange. It just kept telling me the network name cannot be found. But the same address works in your app. 

I will test your second option and see what results i get. Again thanks for your help.

**Comment by CurtisFeatures** [comment]
Would you be able to send me a screenshot of an example. I'm having trouble getting this going :) i'm probably misunderstanding how to configure it.

**Comment by CurtisFeatures** [comment]
Never mind. I deleted my old config and started from scratch and it worked. I will retest my original issue.
