### ISSUE TITLE
Newline (\n) in the end of mount options leads to error

### ISSUE THREAD

**Issue by pbtsrc** [mhogomchungu/sirikali#133]
.json conf:

"mountOptions": "reconnect,ServerAliveInterval=60,ServerAliveCountMax=5,cache=yes,kernel_cache,compression=no,large_read,port=2222\n",

debug log:
StdError: fuse: invalid argument `,password_stdin,StrictHostKeyChecking=no'

Command: "/usr/bin/sshfs"  "user@XXX.XXX.1.10:/" "/home/mnt/sftp/"  -o rw,fsname=sshfs@"user@XXX.XXX.1.10:/",subtype=sshfs,reconnect,ServerAliveInterval=60,ServerAliveCountMax=5,cache=yes,kernel_cache,compression=no,large_read,port=2222
,password_stdin,StrictHostKeyChecking=no

**Comment by mhogomchungu** [comment]
Thanks for the report, the git version no longer has this problem.

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for this problem.

https://github.com/mhogomchungu/sirikali/releases/tag/1.4.2

**Comment by pbtsrc** [comment]
Great, thank you
