### ISSUE TITLE
Sirikali portable

### ISSUE THREAD

**Issue by aardbol** [mhogomchungu/sirikali#138]
Hi

I just wanted to ask the question about the .zip release of Sirikali. Is that a portable version of the software? I'm looking into using SK to encrypt contents on a USB drive and also put the SK binaries on the stick so I can open the encrypted containers on any Windows PC. Is that technically possible?

**Comment by mhogomchungu** [comment]
The release in the .zip archive is the portable version as in you can run the version in the folder in any windows computer that is atleast windows 7 without first installing it.

This version should pick up all of its backends if they are either installed on the host system or are found in the "bin" folder located within the portable folder.

The biggest problem you are going to hit is the runtime dependency of the backends SiriKali supports. Securefs, Encfs and Sshfs-win requires winfsp to be installed in the host system for them to works and  Cryfs requires dokany to be installed in the host system for it to work.

Winfsp and dokany are kernel drivers and as far as i know, can not be used if they are not installed and these drivers prevents these backends to be used in a portable fashion.

**Comment by aardbol** [comment]
Thanks for the detailed answer! Okay, but those issues aren't the case with gocryptfs I hope? That's what I'm using.

**Comment by mhogomchungu** [comment]
gocryptfs currently works in Linux and MACOS only.

The windows version is called cppcryptfs and it has the same issue[1]

[1] https://github.com/bailey27/cppcryptfs/issues/65
