### ISSUE TITLE
gvfs mount detection

### ISSUE THREAD

**Issue by pboguslawski** [mhogomchungu/sirikali#139]
Sirikali (1.3.6+dfsg1-1 from debian) does not detect mounting samba shares in Gnome. This kind of mount does not update /proc/self/mountinfo which sirikali seems to monitor.

Please consider listening also for mount events generated for gvfs; seems it use dbus messages:

https://wiki.gnome.org/Projects/gvfs/doc

I can see (in dbus-monitor) that mounting smb share in gnome (Debian 10) generates dbus traffic containing:

[...]
method call time=1579221072.973035 sender=:1.95 -> destination=:1.18 serial=219 path=/org/gtk/vfs/mounttracker; interface=org.gtk.vfs.MountTracker; member=MountLocation
[...]
method call time=1579221073.123475 sender=:1.124 -> destination=:1.18 serial=29 path=/org/gtk/vfs/mounttracker; interface=org.gtk.vfs.MountTracker; member=RegisterMount
[...]
signal time=1579221073.124051 sender=:1.18 -> destination=(null destination) serial=137 path=/org/gtk/vfs/mounttracker; interface=org.gtk.vfs.MountTracker; member=Mounted
[...]

Regards,
Paweł

**Comment by mhogomchungu** [comment]
What are you trying to do?

A quick google search has says GVFS creates its mount points in ```/run/user/$USER/gvfs/``` and the easiest way of monitoring for GVFS mounting/unmounting events is to monitor for folder creation/deletion in this directory.

**Comment by pboguslawski** [comment]
> What are you trying to do?

Sirikali (1.3.6+dfsg1-1 from debian) is configured for automatic mounting of encfs folder ~/.sirikali/test/Docs and ~/.sirikali/test is symbolic link to
/run/user/NNNN/gvfs/smb-share:server=server.domain,share=test to workaround problem described in https://github.com/mhogomchungu/sirikali/issues/137#issue-545488342

where NNNN is UID of user.

When gnome mounts smb share as above, sirikali does not mount encfs folder automatically - one have to manually call Favourites function to open it.

Quick look at sirikali source shows that it uses /proc/self/mountinfo to check for folders to became available but gnome does not use this file when mounting gvfs. So in this issue I propose to monitor also gnome signals to be able to use automatic sirikali mounting with gvfs.

Regards,
Paweł

**Comment by mhogomchungu** [comment]
The functionality is now in the git version.

Can you compile SiriKali from source code?

If you can, update by compiling the git version, start it and then open SiriKali config file located at 
```~/.config/SiriKali/SiriKali.conf``` and then look for ```MountMonitorFolderPaths``` entry and add your ```/run/user/NNNN/gvfs/``` path and start SiriKali and see if SiriKali can now notice. mount points created by gvfs.

**Comment by pboguslawski** [comment]
Just compiled 7b138f7400b4d9854167d8f45cf9ca83bd50bbf6 in Debian 10 amd64 and set MountMonitorFolderPaths and it doesn't work.

I've also checked with

`inotifywait --monitor /run/user/1234/gvfs`

that mount/umount of smb share in this dir does not generate IN_CREATE|IN_DELETE inotify events only

`ls /run/user/1234/gvfs`

throws 

```
/run/user/1234/gvfs/ OPEN,ISDIR 
/run/user/1234/gvfs/ ACCESS,ISDIR 
/run/user/1234/gvfs/ ACCESS,ISDIR 
/run/user/1234/gvfs/ CLOSE_NOWRITE,CLOSE,ISDIR 
```

Checked in regular dir that creating/removing subdirectory...

```
mkdir ~/tmp/foo
rmdir ~/tmp/foo
```

...generates IN_CREATE|IN_DELETE ok in the same system:

```
inotifywait --monitor ~/tmp
Setting up watches.
Watches established.
/home/me/tmp/ CREATE,ISDIR foo
/home/me/tmp/ DELETE,ISDIR foo
```

Seems inotify is not enough for gvfs.

Regards,
Paweł

**Comment by mhogomchungu** [comment]
fsnotify doesn't seem to work with FUSE[1] and "dbus-monitor" is too chatty to be useful. The easiest solution i can think of for FUSE based folfrtd is to do a manual poll of folder contents after every specified amount of time and respond when folder changes.

[1] https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE

**Comment by mhogomchungu** [comment]
The config file has a new option ```MountMonitorFolderPollingInterval```.

Update from git and then set the above option with a number greater than 0 and SiriKali will start polling the mount point for folder additions after every values in seconds.

**Comment by pboguslawski** [comment]
Just compiled dfb3ea319dc3345888a02b7d3d619cd220a453b3 in debian 10 amd64 and configured

```
MountMonitorFolderPaths=/run/user/1234/gvfs/
MountMonitorFolderPollingInterval=10
```
and encryped dir

`/run/user/1234/gvfs/smb-share:server=myserver.mydomain,share=myshare/encfsstuff`

is not automatically mounted by sirikali after 60s after subdir

`smb-share:server=myserver.mydomain,share=myshare`

is created by gvfs in /run/user/1234/gvfs; tried also

`MountMonitorFolderPaths=/run/user/1234/gvfs/`

and

`MountMonitorFolderPaths=/run/user/1234/gvfs/smb-share:server=myserver.mydomain,share=myshare/encfsstuff`

without success (I assume MountMonitorFolderPaths should poll only local dir /run/user/1234/gvfs and using full network path should be avoided).

Notwithstanding the above, using dbus seems to be better solution in this case than polling dir.

> "dbus-monitor" is too chatty to be useful.

According to

https://dbus.freedesktop.org/doc/dbus-tutorial.html#signalprocedure

> Any process on the message bus can register "match rules" indicating which signals it is interested in.

so sirikali should not try bo process all dbus traffic but only singnals from gvfs regarding mount/umount events (similar to inotify stuff in terms of load problably) in addition to inotify and /proc/self/mountpoint monitoring for dirs other than gvfs (leaving MountMonitorFolderPollingInterval MountMonitorFolderPaths as option for other difficult to predict cases).

**Comment by mhogomchungu** [comment]
Lets deal with the polling functionality first.

MountMonitorFolderPaths=/run/user/1234/gvfs/
MountMonitorFolderPollingInterval=10

The above two options set SiriKali to poll for folder changes in "/run/user/1234/gvfs/" after every ten seconds. 10 seconds seems like a long time.

1. Unmount your network share.
2. Configure SiriKali to automount on available volume located at "/run/user/1234/gvfs/smb-share:server=myserver.mydomain,share=myshare/encfsstuff" 
3. Start SiriKali.
4. Mount the share and SiriKali will notice the addition of "smb-share:server=myserver.mydomain,share=myshare" folder in "/run/user/1234/gvfs/" after 10 seconds at the latest.
5. SiriKali will announce the showing up of the folder to another part of itself and the other part
will check if a folder located at "/run/user/1234/gvfs/smb-share:server=myserver.mydomain,share=myshare/encfsstuff" is configured to automount when available.

I suspect the problem you are having is at step 2

**Comment by pboguslawski** [comment]
Just tested as above without success. Sirikali does not detect subdir /run/user/1234/gvfs/smb-share:server=myserver.mydomain,share=myshare when its available.

Volume has "Auto Mount" = true in properties (I also have another volume in other smb dir defined with automounting enabled also but is should'nt be an obstacle).

Didn't find any debug infos from sirikali on its stdout/err/syslog not option to generate such more details.

**Comment by mhogomchungu** [comment]
Git version now prints to the terminal logs and they appear here as below

```
Timeout Event Noticed
Timeout Event Noticed
New Mount Point Detected: /var/run/user/500/gvfs/smb-share:server=localhost,share=share
Automount Favorites Detected: /var/run/user/500/gvfs/smb-share:server=localhost,share=share/gocryptfs
Timeout Event Noticed
Timeout Event Noticed
```

**Comment by pboguslawski** [comment]
Update: dfb3ea319dc3345888a02b7d3d619cd220a453b3 automounts ok with

MountMonitorFolderPaths=/run/user/1234/gvfs/
MountMonitorFolderPollingInterval=10

(I didn't spot error during package update and older sirikali build was tested before).

Now there is no problem with automounting two different smb directories mapped using gvfs.

Thank you!

> Git version now prints to the terminal logs and they appear here as below

Consider adding debug option to cli (-d/--debug maybe? but there is already -d in params) to enabled such logs avoid spamming console if not necessarry.

Regards,
Paweł

**Comment by mhogomchungu** [comment]
Press "CTRL+D" while the main window has focus to get a debug window. The window doesn't show every event and it only show the ones that are hard to troubleshoot.

**Comment by mhogomchungu** [comment]
Git version of SiriKali now uses QtDBus to monitor gvfs mount events.

1. Update SiriKali from git.
2. Remove ```MountMonitorFolderPaths``` option from the config file
3. Add ```GvfsFuseMonitorPath=/run/user/1234/gvfs/``` to SiriKali config file to tell SiriKali where the gvfs mount path is.
4. Start SiriKali.
5. Check if the feature works.

Closing it for now but will appreciate a confirmation that the feature works
