### ISSUE TITLE
Add PGP signing key for binaries

### ISSUE THREAD

**Issue by SilmorSenedlen** [mhogomchungu/sirikali#144]
Good day
It would be great if you added PGP public key which signing binaries on release page or about page.

**Comment by mhogomchungu** [comment]
You can get the signing key using below command

```
gpg --recv-keys 0x6855E493B5B2DF96E319BB6D16E2E1ACC6F51242
```

Will add it later to somewhere more discoverable.

**Comment by mhogomchungu** [comment]
I have added the above line on the release page and will always be adding it from now for every release page.
