### ISSUE TITLE
Unrecognized option "--config" with EncFS 1.9.2

### ISSUE THREAD

**Issue by CoolSpot** [mhogomchungu/sirikali#146]
Ubuntu 18.04 LTS and latest Linux Mint 19.3 are shipping EncFS [version 1.9.2 in their repositories](https://packages.ubuntu.com/search?keywords=encfs).
When I am trying to use EncFS config stored in arbitrary path (Options -> Options -> "Unlock A encfs Volume With Specified Configuration File.") I get the following error message:
`Failed To Complete The Task And Below Log was Generated By The Backend.

----------------------------------------
/usr/bin/encfs: unrecognized option '--config'
The directory "/home/username/Documents/dropbox.encfs6.xml/" does not exist. Should it be created? (y,N) Directory not created.
Unable to locate root directory, aborting.Build: encfs version 1.9.2
`
This happens because there was no "--config" flag [before version 1.9.5](https://github.com/vgough/encfs/pull/474) .
The environment variable [ENCFS6_CONFIG](https://manpages.ubuntu.com/manpages/eoan/en/man1/encfs.1.html) is supported in all EncFS versions.

**Comment by mhogomchungu** [comment]
1. Uninstall the version of SiriKali you have installed.
2. Install below binary package and try again.

https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_18.04/amd64/sirikali_1.4.3.1589312816.0017255-0_amd64.deb

**Comment by mhogomchungu** [comment]
This issue is fixed. You can get the fix by either building from source code or using a binary package that is applicable to your distribution from here[1]

[1] https://download.opensuse.org/repositories/home:/obs_mhogomchungu/
