### ISSUE TITLE
support for panel theming

### ISSUE THREAD

**Issue by brainchild0** [mhogomchungu/sirikali#151]
Following PapirusDevelopmentTeam/papirus-icon-theme#2267, SiriKali might support theming  by using a separate icon name  `sirikali-panel` for the icon in the system indicator. The target file, in the  application distribution, corresponding to the  added panel icon might be a copy or link of the existing application icon. The separate names, however, give themes the flexibility to override each of the native icons with distinct images. 

A minimal change may be simply to add a second call to `QIcon::fromTheme()`, with string `sirikali-panel`,  to use this result with the functionality in `QSystemTrayIcon`, and to add a symbolic link in the package distribution.

**Comment by mhogomchungu** [comment]
Done.

https://github.com/mhogomchungu/sirikali/commit/07548e09773f081576b1ef9fc174f5391d23c5ea

**Comment by mhogomchungu** [comment]
New version is SiriKali is out: https://github.com/mhogomchungu/sirikali/releases/tag/1.4.5
