### ISSUE TITLE
Network Request Failed To Respond Within 5 Seconds - but everything works

### ISSUE THREAD

**Issue by anttin2020** [mhogomchungu/sirikali#154]
Almost every time after mount and occasionally I get "Network Request Failed To Respond Within 5 Seconds" but everything still works :o 
Is there some setting that could help or should I just ignore that?
I tried to increase the timeout to 20 s. but it does not affect on that.

Thank you :)

Antti

**Comment by mhogomchungu** [comment]
What version of SiriKali are you using? That looks like an error from a very old version.

How did you increase the timeout?

**Comment by anttin2020** [comment]
Hi!
Sirikali should be the latest, it's 1.4.4.
Actually the timeout was for different purpose, it was the idle timeout, what does that actually affect? And is that minutes or seconds? I returned it to default (empty) :)

**Comment by mhogomchungu** [comment]
I do not think sshfs accepts that option, some backends like encfs, gocryptfs and cryfs accepts a "idle timeout" option and its purpose is to unmount a file system if its mount point is idle for a specified period of time.

The functionality that produces that error is disabled on windows and by default, a user has to manually run the functionality and its odd you are seeing it on windows.

In linux, to trigger the functionality, a user has to click the selected entry on the SiriKali tray menu in the image below and SiriKali will go online to check for latest versions of installed backends and produces the version info window.

SiriKali fails with that error if a network request does not respond within 5 seconds[1]

[1] https://github.com/mhogomchungu/sirikali/blob/077c39f0ffd63015b90492014691cf09804b6fe4/src/checkforupdates.cpp#L222

![Screenshot_20200622_141034](https://user-images.githubusercontent.com/3496115/85281178-34a9f580-b492-11ea-866d-6820c0e9cc49.png)

**Comment by mhogomchungu** [comment]
Next version should fix this warning.
