### ISSUE TITLE
Missing tray icon sometimes

### ISSUE THREAD

**Issue by pehlm** [mhogomchungu/sirikali#158]
I have sirikali autostarting on Ubuntu 18.04, it is always running after login and the volumes are mounted but the icon isn't always showing in the tray. Because of that I must kill sirikali and start it again, then the icon appear. This is on Gnome but it works as it should in Xubuntu (Xfce4). My other tray icons is working. Using 1.4.4.

**Comment by mhogomchungu** [comment]
I don't know what i can do about this, the code that shows the tray icon is here[1] and it tries 10 times to set the tray icon before giving up.

[1] https://github.com/mhogomchungu/sirikali/blob/96b8ffca48d7f4caac3ca3b4a60cdebe4a349cd8/src/sirikali.cpp#L339-L361

**Comment by pehlm** [comment]
Thanks for the answer! This is working sometimes, now when I was logging in it worked! Maybe then it is a Gnome problem, I was thinking that you had a clue about it though. It's sometimes annoying.

**Comment by mhogomchungu** [comment]
Upsream GNOME does not support tray icons and you can see tray icons only if you are using one of GNOME's many extensions that offer tray icon support. Which one of the tray icon extension are you using?

**Comment by pehlm** [comment]
However, I mostly use Xubuntu which always shows the icon without any problem. Now I tried for a while Ubuntu, and it has its default appindicator gnome shell extension. Sometimes the icon does not appear. I do not know why, but it is probably a bug in that Ubuntu appindicator extension.

**Comment by mhogomchungu** [comment]
I do not think there is anything i can do about this in SiriKali.
