### ISSUE TITLE
MacOS: current master fails to unmount an FS

### ISSUE THREAD

**Issue by mouse07410** [mhogomchungu/sirikali#160]
It used to work OK until the current master (and possibly the current CryFS master).

MacOS Catalina 10.15.6, Xcode-11.6, current master.
![Screen Shot 2020-08-06 at 14 51 15 ](https://user-images.githubusercontent.com/5923577/89570962-e6a84180-d7f4-11ea-9d37-a6cacd0ddffd.png)

Filesystem:
![Screen Shot 2020-08-06 at 14 54 15 ](https://user-images.githubusercontent.com/5923577/89570848-c1b3ce80-d7f4-11ea-9114-1f6bb4e2c89a.png)

Here's what I'm getting on the attempt to unmount:
![Screen Shot 2020-08-06 at 14 50 33 ](https://user-images.githubusercontent.com/5923577/89570751-9df08880-d7f4-11ea-866a-e792fbdd2e10.png)
Repeating attempts to unmount don't help/don't work - same error message, regardless of the delay before the next attempt.

Manual unmount works fine, though not immediately:

```sh
$ mount
/dev/disk1s5 on / (apfs, local, read-only, journaled)
. . . . .
Cryfs@/Users/uri/cryfs-raw on /Users/uri/.SiriKali/cryfs-raw (osxfuse, nodev, nosuid, synchronous, mounted by uri)
$ cryfs-unmount /Users/uri/.SiriKali/cryfs-raw
CryFS Version 0.10.2+302.g80267016.dirty
Unmounting CryFS filesystem at "/Users/uri/.SiriKali/cryfs-raw".
Filesystem will unmount as soon as nothing is accessing it anymore.
$ mount
/dev/disk1s5 on / (apfs, local, read-only, journaled)
. . . . .
/dev/disk1s3 on /Volumes/Recovery (apfs, local, journaled, nobrowse)
$ 
```
I.e., it unmounted the CryFS filesystem fine.

**Comment by mhogomchungu** [comment]
When SiriKali window has focus, press "CTRL+D" to get debug window and then click "refresh" and then attempt to unmount and finally post the contents of the produced window.

**Comment by mhogomchungu** [comment]
Also, try to unmount using "umount" command because that is what SiriKali is using: https://github.com/mhogomchungu/sirikali/blob/9974336b695f1024d4ad7e216d4b1fcae27d9e6e/src/engines.cpp#L262

**Comment by mhogomchungu** [comment]
Update from git and try again.

**Comment by mouse07410** [comment]
> Update from git and try again.

Thank you - updated build worked correctly!

**Comment by mhogomchungu** [comment]
Can you build from git and make sure it works?

I want to make a new release on October 1st, 2020 and i want to be sure it has no issues on macos.

Thanks.

**Comment by mouse07410** [comment]
I only build from git. :-)

Just did a fresh pull, and built successfully. Started, mounted an FS, played with it, unmounted. All ok.

I think macOS is fine.
