### ISSUE TITLE
Windows x64 executable?

### ISSUE THREAD

**Issue by Achaean** [mhogomchungu/sirikali#161]
**Hi!**  :-)

Just a question:
Is it possible to build an x64 executable on Windows?

Sidequestion:
Is there any x64 version of QT?

PS. I admit that I didn't build something on Windows, for ages!

**Comment by mhogomchungu** [comment]
Its possible to have x64 version of Qt[1] and therefore it should be possible to have x64 version of SiriKali in Windows but I have not tried to build it.

Currently, SiriKali is a 32 bit executable and is build using "MinGW 7.3" and the minimum supported version is windows 7.

[1]https://doc.qt.io/qt-5/windows.html

**Comment by Achaean** [comment]
Nope! I failed!
Seems quite complicated to me.   :-)

Again, just don't take my word for this. I'm keeping my gives and takes with the Windows world, to the absolute minimum, for ages, so I'm not the proper person to speak.

OK. I'll give in to the temptation and I'll make this post to a feature request, so
Please build a native x64 executable, because wow64 is good only for games.  :-)
OK! Low priority! :-)

I went on and I installed (the installer version) at my system (Win 10 Pro x64 b.1909), and: 

1) (At "Settings"), "Select Language" doesn't do something. Pressing it, has no effect.

2)  (I don't know, if this is on purpose), but it misses the "Check for updates" tray icon, right-click entry

**Comment by mhogomchungu** [comment]
"Check For Updates" on windows is disabled because SiriKali uses QtNetwork library to do network connections and this library depends on openssl libraries to be installed/bundled too and i have not looked into how to bundle needed openssl libraries.

What do you miss in x32 executable that makes you want x64 executable? x32 executable works in both versions of windows but x64 executable only works in x64 versions of windows. With x32 version, i can release one binary and it will work on both versions of windows, if i release x64 version then i will need to also release x32 version meaning releasing 2 different versions for windows.

**Comment by mhogomchungu** [comment]
There seems to be issues with bundling of openssl libraries: https://doc.qt.io/qt-5/ssl.html#import-and-export-restrictions

**Comment by mhogomchungu** [comment]
x64 binaries are now available and they use Qt6.

https://github.com/mhogomchungu/sirikali/releases/tag/1.5.2

**Comment by mhogomchungu** [comment]
They are not there because they are not officially released.

They will officially be released with the release of the next version and i do not know when that will be.

**Comment by mhogomchungu** [comment]
They are there now.

Qt5 is the default because my primary system is Linux with plasma 5 and plasma 5 requires Qt5.

**Comment by sitiom** [comment]
I have now updated the Winget and Scoop packages with the new 64bit binary accordingly:
- https://github.com/microsoft/winget-pkgs/pull/190149#pullrequestreview-2425966961
- https://github.com/ScoopInstaller/Extras/pull/14387

**Comment by mhogomchungu** [comment]
Thank you @sitiom for your packages.

I just released version 1.7.1 and it fixes an issue introduced in version 1.7.0.

https://github.com/mhogomchungu/sirikali/releases/tag/1.7.1

**Comment by sitiom** [comment]
Updated (fixed the asset names for the autoupdate as well):
- https://github.com/microsoft/winget-pkgs/pull/191528
- https://github.com/ScoopInstaller/Extras/pull/14411
