### ISSUE TITLE
How to reset Windows DPAPI Wallet?

### ISSUE THREAD

**Issue by magsom** [mhogomchungu/sirikali#162]
I set a password, but now I forget it. I want to delete the wallet and recreate one.
I didn't find any entry about SiriKali in the Credential Manager in Windows Control Panel.

**Comment by mhogomchungu** [comment]
1. Close SiriKali.
2. With the desktop having focus, use "Window_KEY+R" keyboard combo to bring up the run window.
3. In the text field, type "regedit" and press enter to bring up registry key editor.
4. Browse to SiriKali's configuration folder and delete the entry named ```LXQtWindowsDPAPI_Data```
5. Restart SiriKali.

The image below shows where the option is.

![windows](https://user-images.githubusercontent.com/3496115/91823271-9e3c4200-ec41-11ea-84f0-e0605c42ba99.png)

**Comment by mmagill-thinksense** [comment]
This did not work for me with the current version.  I had to close Sirikali, remove the lqxt settings file in the user's AppData\Local\Sirikali folder, and reopen Sirikali.  I was immediately prompted to set a password for the DPAPI wallet
