### ISSUE TITLE
SSHFS port edition

### ISSUE THREAD

**Issue by jo-chemla** [mhogomchungu/sirikali#164]
Hello, I cannot find the way to edit the port to which I want my SFTP connection to go through - when following your [SSHFS guide](https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#90-how-do-i-add-options-to-connect-to-an-ssh-server), and entering **user@ipv4:port/remote_path** as encrypted folder path, when connecting to this Favorite I get a "Connection time-out" error, `ssh: connect to host IPV4 port 22: Connection timed out / read: Connection reset by peer`. I also tried with the win-sshfs syntax user@ipv4!port/path with no luck. Is it possible via sirikali to edit the port to not go through port 22? Thanks in advance!

Note that I am connecting using user/password pair, and when using the ipv4!port port I get another error immediately, `sshfs: bad mount point `user@ipv4!port/path': No such file or directory` (when the above connection timeout error was taking longer to appear).

**Comment by jo-chemla** [comment]
Sorry, simply had to add the `port=PORT_NUMBER` in the mount Options (not documented but pretty straightforward). Syntax for encrypted folder path is simply user@ipv4:/path with no reference to port number. Closing issue.

**Comment by mhogomchungu** [comment]
The git version now has a dedicated section to set the port number.

![ssh](https://user-images.githubusercontent.com/3496115/92562815-3c9e5800-f27f-11ea-9f62-68a00fc7bd81.png)

**Comment by jo-chemla** [comment]
Thanks for the info, will wait for the next release!

**Comment by jo-chemla** [comment]
I have another question linked to that issue. I've set up a Windows' DPAPI wallet to store passwords to my SFTP shares, however, my set-up is the following:

 - I have a router with a public IP, which has different external ports opened and mapped to different NAS servers on the local network, each one with its IP and SFTP share set-up. The specificity of my set-up here is that on each of these NAS I have a user with the same username (but different passwords per nas), and same directory structure and paths. 
 - Therefore the Volume Path in Sirikali are all the same `Sshfs SAME_USERNAME@SAME_PUBLIC_IP:/SAME_REMOTE_PATH`, and ports are given only as Mount Options. 
 - Hence, when adding all these entries to the default wallet in sirikali, only the last password is taken into consideration, and the connection auto-mounts with the right password only for one NAS. For all other connections, I need to set-up the right password.

Hence the question: am I correctly identifying the issue here (wallet association to passwords is only based on the connection string, which in my case is the same for all conections), and if so, do you think you can have a fix for this specific issue? For example, do you plan to integrate the port in the Remote Ssh Server Address, which could help separate the different connections in the wallet? Or should I rename my users to be distinct on each nas? 

Thanks in advance for your feedback!

**Comment by mhogomchungu** [comment]
You can download a git version from here: https://github.com/mhogomchungu/sirikali/releases/download/1.4.6/SiriKali-1.4.6-dev-10.09.2020.setup.exe

After you have installed this version:

1. Delete all favorite sshfs entries you have and readd them with your custom port number.
2. Go to "manage keys in wallet" tab and click the button pointed to in the image below to get a list of favorites entries and click the entry you want to add the in the wallet.
3. You will notice that the ssh path ends with "####PORT_NUMBER" for port numbers that are different from 22.
4. Add the password and continue normally.

![sss](https://user-images.githubusercontent.com/3496115/92729557-2ecdfd00-f37b-11ea-8680-20f95dcdedb2.png)

**Comment by jo-chemla** [comment]
Thanks that's exactly what's needed!

**Comment by mhogomchungu** [comment]
New version is out and i recommend you update to it: https://github.com/mhogomchungu/sirikali/releases/tag/1.4.7
