### ISSUE TITLE
Lintian issues

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#165]
The [Lintian report](https://lintian.debian.org/sources/sirikali/1.4.4-1.html) for Sirikali has a number of issues that address upstream:

[hardening-no-bindnow](https://lintian.debian.org/tags/hardening-no-bindnow.html) usr/bin/sirikali
[hardening-no-bindnow](https://lintian.debian.org/tags/hardening-no-bindnow.html) usr/bin/sirikali.pkexec
[spelling-error-in-binary](https://lintian.debian.org/tags/spelling-error-in-binary.html) usr/bin/sirikali occured occurred
[spelling-error-in-binary](https://lintian.debian.org/tags/spelling-error-in-binary.html) usr/bin/sirikali responce response

**Comment by mhogomchungu** [comment]
Typos fixed: https://github.com/mhogomchungu/sirikali/commit/b54f4301dae05fb5209718cf14b46c5350d8c3e2

The link option is also added: https://github.com/mhogomchungu/sirikali/commit/f313f8b9a5d8b8c3662e90b6976932809a0e412e

The next version will be out in October 1, 2020.
