### ISSUE TITLE
KWallet on KDE doesn't show up

### ISSUE THREAD

**Issue by Alt37** [mhogomchungu/sirikali#169]
Look like SiriKali doesn't recognize that I have KWallet installed on my system (it's definitely used). When I try to create Cryfs or Encfs Volume KWallet is missing on a dropdown list (Gnome Wallet is present). On settings KWallet can't be selected as "Default Wallet"
OS is Kubuntu 20.04. Tried both latest version (1.4.7 from OBS repo) and version from Ubuntus repository (1.4.2)

**Comment by mhogomchungu** [comment]
Kwallet/libsecret(gnome wallet) are compile time dependencies.

If the option is not there then the reason is because it was not included
when building SiriKali.

**Comment by Alt37** [comment]
> Kwallet/libsecret(gnome wallet) are compile time dependencies. If the option is not there then the reason is because it was not included when building SiriKali.

I can't figure out how to enable it.  LINUX_BUILD_INSTRUCTIONS mentions kde-devel but I can't find it for Debian or even Fedora.
Could you please enable KWallet for [OBS builds](https://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=sirikali)?

**Comment by mhogomchungu** [comment]
The problem here is that adding kwallet support as a compile time dependency will drap in a bunch of KDE libraries and some people don't like  it.

The solution here is to have kwallet support as a runtime dependency through through d-bus and i am working on it.

**Comment by mhogomchungu** [comment]
Try again with the OBS version. i have added kwallet support through dbus so there should be no additional package requirement..

**Comment by mhogomchungu** [comment]
Closing this one as "fixed" but would appreciate a confirmation that it does work.
