### ISSUE TITLE
How to mount volume created in SiriKali from command line?

### ISSUE THREAD

**Issue by ikatza** [mhogomchungu/sirikali#17]
So as the title says, however I'm interested when the option of Key+KeyFile are used to create the volume. Does cryfs, securefs, gocryptfs, encfs or ecrypts support Key+KeyFile?

If a volume was created with SiriKali and Key+KeyFile can it be mounted with something else?

**Comment by mhogomchungu** [comment]
No,these backends are not aware of the implementation of "key+keyfile" option as SiriKali generates a passphrase that is a combination of a key and a keyfile and passes on the result as a passphrase to these backends.

The passphrase is generated with the below formular:
``` passphrase = hmac_sha256(key,keyfile contents) ```

You can use a CLI tool "hmac256"(DO NOT set the binary option) among others to generate the passphrase independently of SiriKali. This CLI tool should already be installed in your computer(it is in mine).

[1] http://manpages.ubuntu.com/manpages/xenial/en/man1/hmac256.1.html

**Comment by mhogomchungu** [comment]
Implementations of key options are explained here: https://github.com/mhogomchungu/SiriKali/wiki/Frequently-Asked-Questions#40-what-does-different-key-options-means-in-the-dialog-for-creatingunlocking-volume

**Comment by ikatza** [comment]
Thanks! Already got it working.

**Comment by mhogomchungu** [comment]
Version 1.2.5 of SiriKali(already released) has an option to display a password in the password dialog prompt and you can use this feature to see the generated key that will be passed to the backend.

From CLI currently on this git version,you can get the password also by using "-s" option that enables the feature together with "-f" that takes a path to a keyfile. The password will be asked by a terminal prompt. Example of the above is below:

```
[mtz@ink ~]$ sirikali -s -f key 
Password: 
408d71e534422ff5af7894216c6762adc4fe11dfda20a7b9bfb61946355d05c6
[mtz@ink ~]$ 

```

**Comment by eugenesvk** [comment]
I get different hashes for these two commands (on both Linux and macOS)
`hmac256 key ./file.txt` (have also tried with `--stdkey` option)
`cat ./file.txt | openssl dgst -sha256 -hmac ""`, only the latter matches the hash generated in SiriKali.
