### ISSUE TITLE
Mounting items in Favorites does not respect Re Use Mount Point setting

### ISSUE THREAD

**Issue by suyang-nju** [mhogomchungu/sirikali#170]
The "Re Use Mount Point" setting is only respected when using the "Mount Volume" button in the main window. When mounting an entry in the Favorites menu at a pre-existing mount point, the setting is ignored and SiriKali complains "Failed To Create Mount Point".

**Comment by mhogomchungu** [comment]
What version of SiriKali are you using?

**Comment by suyang-nju** [comment]
I tried version 1.4.7 and the current git build from Arch Linux's AUR.

**Comment by mhogomchungu** [comment]
Try now using git version

**Comment by suyang-nju** [comment]
Fixed. Thanks!
