### ISSUE TITLE
Arm build failure

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#173]
FYI, lxqt-wallet is failing build on some ARMs - [e.g.](https://buildd.debian.org/status/fetch.php?pkg=sirikali&arch=armhf&ver=1.4.7-1&stamp=1604185889&raw=0)

There is an "internal compiler error" in that log.

It builds fine on my armhf Pi, running Raspberry Pi OS Buster.

**Comment by mhogomchungu** [comment]
The compiler crash is not caused by lxqt-wallet but by "NetworkAccessManager"[1] and the building of it started at the third 3% mark.

[1] https://github.com/mhogomchungu/sirikali/blob/master/src/3rdParty/NetworkAccessManager/network_access_manager.hpp

**Comment by mhogomchungu** [comment]
T o be precise, what happens here is as follows:-
1. The compiler is crashing.
2. The compiler is crashing after seen something in QtCore.
3. The path to the problematic line in QtCore was pulled in by QtNetworkAccessManager.
4. QtNetworkAccessManager was pulled in by SiriKali here[1].

Thanks for the info but i do not think there is anything i can do here.

[1] https://github.com/mhogomchungu/sirikali/blob/14974f69e7defd57503fc3d43da6c55db6667566/src/3rdParty/NetworkAccessManager/network_access_manager.hpp#L34

**Comment by davesteele** [comment]
Hence the fyi.
