### ISSUE TITLE
Problem with GPS home location

### ISSUE THREAD

**Issue by Agm2104** [mhogomchungu/sirikali#174]
Hi everyone!

I'm having a problem when trying to run the hello_drone script, since I'm getting the following error:

**msgpackrpc.error.RPCError: rpclib: function 'armDisarm' (called with 2 arg(s)) threw an exception. The exception contained this information: Vehicle does not have a valid GPS home location.**

However I think I have implemented the location in the settings.json correctly

![image](https://user-images.githubusercontent.com/74015104/98276635-8ca34d80-1f96-11eb-8617-2b26fb0d1a04.png)

Also, when linking with PX4 I get the following:

![image](https://user-images.githubusercontent.com/74015104/98276325-17d01380-1f96-11eb-9c8c-bab0988e8111.png)

Which according with #2647 is a good sign.

However I'm unable to arm the robot and I'm running out of ideas...
What do you think the problem is?

**Comment by mhogomchungu** [comment]
I think you posted this on the wrong project
