### ISSUE TITLE
Encrypted Folder Path is Already Taken

### ISSUE THREAD

**Issue by OdinVex** [mhogomchungu/sirikali#177]
I created a volume, unmounted and deleted it and the remnant folder and then tried to create a volume with the same name and path (I previously forgot to set the block size to 4K) but was met with “Encrypted Folder Path is Already Taken.”

Created Volume.
Unmounted Volume.
Deleted Remnant Folder.

I tried creating another volume with same name but apparently the folder already existed despite my deleting it.

`**I had to delete the remnant folder...a second time.**`

The debug log contained nothing relevant (just ykchalresp and the info relating to ciphers from opening the options' dialog).

**Comment by OdinVex** [comment]
Now I'm met with:

Failed To Complete The Task And Below Log was Generated By The Backend.

----------------------------------------
Error 20: The filesystem id in the config file is different to the last time we loaded a filesystem from this basedir.

**Comment by mhogomchungu** [comment]
Version 1.4.3(released April 1st, 2020) added the option ```--allow-replaced-filesystem``` and is enabled by default

![Screenshot_20210106_194058](https://user-images.githubusercontent.com/3496115/103795717-5f872000-5057-11eb-9ac4-26414763b7e1.png)

**Comment by mhogomchungu** [comment]
I am closing this one as "working as expected in more recent versions".

Please reopen if you can consistently get the "encrypted folder path is already taken" error when using the latest released version of SiriKali with git version being most preferred version.
