### ISSUE TITLE
Option to customize full mount point, not only its prefix

### ISSUE THREAD

**Issue by Oli72** [mhogomchungu/sirikali#178]
For historical reasons, I have several encfs encrypted folders named `~/somedir/.foldername_encfs` that should be mounted to `~/somedir/foldername`, where `somedir` and `foldername` vary with each folder. In the GUI of SiriKali 1.4.2 I can't find a way to customize the mount point, only its prefix. As a workaround I edited the files in` ~/.config/SiriKali/favorites` manually. In my opinion such a customization option would improve SiriKali.

**Comment by mhogomchungu** [comment]
Done, the git version has an option pointed to in the image below that allow setting a full path to the mount point instead of the current mount prefix.

![Screenshot_20210218_120258](https://user-images.githubusercontent.com/3496115/108332977-746fdb00-71e1-11eb-94c9-8d601825c453.png)
