### ISSUE TITLE
Installed version of SSHFS is too old

### ISSUE THREAD

**Issue by aslahfidaiyi93** [mhogomchungu/sirikali#182]
Hi @mhogomchungu, 

I'm currently running the latest version of SSHFS (3.7.2). Everytime I require to mount my drives, I'm getting the below error. 
Any ideas as to why this is happening? 
![image](https://user-images.githubusercontent.com/80798346/111576690-edb41b00-87eb-11eb-93b9-2ce438da204f.png)

**Comment by mhogomchungu** [comment]
It is a misleading error, install winfsp[1] and try again. Winfsp is listed as a requirement of sshfs-win here[2]

Closing it but feel free to comment if the problem persist.

[1] https://github.com/billziss-gh/winfsp
[2] https://github.com/billziss-gh/sshfs-win#installation
