### ISSUE TITLE
Can't compile on osx catalina

### ISSUE THREAD

**Issue by munntjlx** [mhogomchungu/sirikali#183]
I have required (version 5.x) qt, but I get the following errors:
In file included from /usr/local/include/QtGui/qtguiglobal.h:43:

`In file included from /usr/local/include/QtGui/qtguiglobal.h:43:
/usr/local/include/QtCore/qglobal.h:667:43: error: no template named 'is_arithmetic_v' in namespace 'std'; did you mean
      'is_arithmetic'?
         typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                                     ~~~~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:994:50: note:
      'is_`

After doing cmake and then make.

**Comment by mhogomchungu** [comment]
This bug report could have a solution for you: https://github.com/DGtal-team/DGtal/issues/1556

**Comment by mhogomchungu** [comment]
I do not think i can do anything here and closing this one with a "local problem" tag.
