### ISSUE TITLE
problem with repository signing

### ISSUE THREAD

**Issue by brainchild0** [mhogomchungu/sirikali#187]
Attempting installation on a system running Mint 20.1, which is based on Ubuntu 20.04, I added the suitable Debian repository to the package manager, as given in the instructions, reproduced as follows, from the [OpenSUSE package repository](https://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=sirikali):

```
echo 'deb http://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:obs_mhogomchungu.list
curl -fsSL https://download.opensuse.org/repositories/home:obs_mhogomchungu/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_obs_mhogomchungu.gpg > /dev/null
sudo apt update
sudo apt install sirikali
````

Inclusion of the repository was unsuccessful, due to an error reported as follows, shown when running the *update* command:

```
Err:32 http://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04  InRelease
  The following signatures were invalid: EXPKEYSIG 9B36C042D8190918 home:obs_mhogomchungu OBS Project <home:obs_mhogomchungu@build.opensuse.org>
```

It would seem   the signing of the repository is invalid, or not matched to keys included in  the client distribution.

The package file itself is valid, as  manual download and installation was successful.

**Comment by mhogomchungu** [comment]
Do you still have this problem?

Unfortunately, i do not use any of the supported distros so i can not test locally.

**Comment by brainchild0** [comment]
Yes.

The full message:

```
W: GPG error: http://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04  InRelease: The following signatures were invalid: EXPKEYSIG 9B36C042D8190918 home:obs_mhogomchungu OBS Project <home:obs_mhogomchungu@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Achaean** [comment]
Same EXPKEYSIG problem here (at a Debian based distro).

```
#apt-key list
.
.
.
/etc/apt/trusted.gpg.d/home_obs_mhogomchungu.gpg
------------------------------------------------
pub   rsa2048 2017-06-05 [SC] [expired: 2023-12-15]
      4EB8 5670 7A33 91E8 C5CF  B054 9B36 C042 D819 0918
uid           [ expired] home:obs_mhogomchungu OBS Project <home:obs_mhogomchungu@build.opensuse.org>
#
```
BTW, **Happy New Year** everyone!!!  :-)

**Comment by wttc-nitr** [comment]
is there a fix for this ?

**Comment by mhogomchungu** [comment]
Will look into it tomorrow or day after.

**Comment by mhogomchungu** [comment]
1. You are getting an error saying the key has expired.
2. Browse to [this](https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/) location and you will notice that Release.key file was last updated on 01/02/2024.

3. This "Release.key" file has expiration date of "02/06/2026".
4. Perhaps you need to update this file because it was updated after you downloaded it.

```
[ink@localhost Downloads]$ gpg --list-packets Release.key 
:public key packet:
        version 4, algo 1, created 1496677359, expires 0
        pkey[0]: [2048 bits]
        pkey[1]: [17 bits]
        keyid: 9B36C042D8190918
:user ID packet: "home:obs_mhogomchungu OBS Project <home:obs_mhogomchungu@build.opensuse.org>"
:signature packet: algo 1, keyid 9B36C042D8190918
        version 4, created 1701426915, md5len 0, sigclass 0x13
        digest algo 8, begin of digest 43 cb
        hashed subpkt 2 len 4 (sig created 2023-12-01)
        hashed subpkt 27 len 1 (key flags: 03)
        hashed subpkt 9 len 4 (key expires after 8y249d18h52m)
        hashed subpkt 11 len 5 (pref-sym-algos: 9 8 7 3 2)
        hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
        hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
        hashed subpkt 30 len 1 (features: 01)
        hashed subpkt 23 len 1 (key server preferences: 80)
        subpkt 16 len 8 (issuer key ID 9B36C042D8190918)
        data: [2044 bits]
:signature packet: algo 17, keyid 3B3011B76B9D6523
        version 4, created 1496677359, md5len 0, sigclass 0x13
        digest algo 2, begin of digest 65 99
        hashed subpkt 2 len 4 (sig created 2017-06-05)
        subpkt 16 len 8 (issuer key ID 3B3011B76B9D6523)
        data: [158 bits]
        data: [159 bits]

```

**Comment by wttc-nitr** [comment]
> 1. You are getting an error saying the key has expired.
> 
>     2. Browse to [this](https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/) location and you will notice that Release.key file was last updated on 01/02/2024.
> 
>     3. This "Release.key" file has expiration date of "02/06/2026".
> 
>     4. Perhaps you need to update this file because it was updated after you downloaded it.
> 
> 
> ```
> gpg --list-packets Release.key 
> :public key packet:
>         version 4, algo 1, created 1496677359, expires 0
>         pkey[0]: [2048 bits]
>         pkey[1]: [17 bits]
>         keyid: 9B36C042D8190918
> :user ID packet: "home:obs_mhogomchungu OBS Project <home:obs_mhogomchungu@build.opensuse.org>"
> :signature packet: algo 1, keyid 9B36C042D8190918
>         version 4, created 1701426915, md5len 0, sigclass 0x13
>         digest algo 8, begin of digest 43 cb
>         hashed subpkt 2 len 4 (sig created 2023-12-01)
>         hashed subpkt 27 len 1 (key flags: 03)
>         hashed subpkt 9 len 4 (key expires after 8y249d18h52m)
>         hashed subpkt 11 len 5 (pref-sym-algos: 9 8 7 3 2)
>         hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
>         hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
>         hashed subpkt 30 len 1 (features: 01)
>         hashed subpkt 23 len 1 (key server preferences: 80)
>         subpkt 16 len 8 (issuer key ID 9B36C042D8190918)
>         data: [2044 bits]
> :signature packet: algo 17, keyid 3B3011B76B9D6523
>         version 4, created 1496677359, md5len 0, sigclass 0x13
>         digest algo 2, begin of digest 65 99
>         hashed subpkt 2 len 4 (sig created 2017-06-05)
>         subpkt 16 len 8 (issuer key ID 3B3011B76B9D6523)
>         data: [158 bits]
>         data: [159 bits]
> ```

deleted the expired key, added the new key. 
Problem solved,
Thanks
