### ISSUE TITLE
Cannot create eCryptfs on Debian Bullseye

### ISSUE THREAD

**Issue by Simon-L** [mhogomchungu/sirikali#188]
Hello, I've installed sirikali as well as your Debian package for ecryptfs-simple.
When I try to create an ecryptfs volume, I choose "password", type a password and click "Create", the window greys out and becomes unresponsive, the whole system freezes until it's killed by the kernel.
What are the correct parameters for ecryptfs?

I should note that cryfs works fine and that I'm otherwise using sirikali for sshfs mounts without any problem. 

Version : 1.4.8

**Comment by mhogomchungu** [comment]
While SiriKali has focus, press "CTRL+D" key combo to bring up log window and then attempt to create a volume and you will see the command and its options SiriKali runs.

Try to run ecryptfs-simple from the command like to first be sure the problem is not in SiriKali.
