### ISSUE TITLE
Open favorites with command line options

### ISSUE THREAD

**Issue by saxofooon** [mhogomchungu/sirikali#190]
Hi, I'd like to open encrypted folders with keepass(xc). Is it possible to open sirikali favorites with a command line option?
Examples how it works with veracrypt:
cmd:///usr/bin/veracrypt --auto-mount=favorites
cmd://"C:\Program Files\VeraCrypt\VeraCrypt.exe" /volume "{USERNAME}" /letter Z /password "{PASSWORD}" /quit

**Comment by mhogomchungu** [comment]
1. What backend are you using? CryFS?,Gocryptfs, Securefs or?
2. Your example does not show how keepass is used with veracrypt.

**Comment by saxofooon** [comment]
I use Gocryptfs.
From keepass I can open an URL to any desired program like described above (cmd://....). Keepass replaces the terms in { } with it's saved data like Passwords, Usernames...
So cmd://"C:\Program Files\Sirikali\Sirikali.exe" --favorites --{PASSWORD}  would be great.

**Comment by mhogomchungu** [comment]
I guess you are on windows.

1. Set Store volume key in SiriKali secured storage system as explained here[1] and select "window's DPAPI" backend. Use an empty password if you do not want to see a SiriKali prompt when trying to access your volume key in the storage system.
2. Add your favorite entry to the secured storage system.
3. Your command should now be cmd:///usr/bin/sirikali -d PATH_TO_GOCRYPT_FOLDER -b windows_dpapi.
4. Every time you run the command, sirikali will go look look for the password of the directory path you gave it in the secured stored system you also gave it.

[1] https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#80-how-do-i-add-a-key-to-a-secured-storage-system

**Comment by mhogomchungu** [comment]
This should now be possible in the git version and the command should be something like

```
cmd:///usr/bin/sirikali -d {PATH_TO_VOLUME} -b clargs -w {PASSWORD}
```
