### ISSUE TITLE
Feature Request: Input Sanitation or Hints for Fequent Options

### ISSUE THREAD

**Issue by Grarie** [mhogomchungu/sirikali#193]
I treid to use the software to connect via sshfs. Unfortunately I was inattentive and forgot a colon in the parameter in the "Remote SSH Server Address". It took me half a hour to locate the error, since the only output is
```
sshfs: bad mount point "foo@bar.baz/": No such file or directory
```
Before this, I made the error of "forgetting the username" (here "foo") and the shown error on saving was something like "it doesn't work".

So I'd like to make it more easy for others (and maybe people with less technical background) so I'd like to add something like hints on input, input sanitation, more specific error messages for standard parameters or something like that. Maybe a trouble-shooting-wiki-entry with "common mistakes and error messages" or something like this.

What do you think about it and what would be the best/easiest way?

**Comment by mhogomchungu** [comment]
Its a good idea and i though about doing it years ago and i wonder why i did not.

Will look into it and thanks for the remainder.

**Comment by mhogomchungu** [comment]
This is now fixed, if Sshfs remote is not in the expected format the UI like below will show up to tell the user and give the an opportunity to fix the error.

![Screenshot_20220108_144754](https://user-images.githubusercontent.com/3496115/148643125-8ad2a659-6d09-4ccb-8c7c-ef74c650b086.png)
