### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jkvargas** [mhogomchungu/sirikali#194]
When I try to write files to mounted folder it says that I don't have permission to write it.
Would you mind to share how should I enable that?
Thanks.

**Comment by mhogomchungu** [comment]
1. What backend are you using? Gocryptfs, CryFS, SecureFS, Sshfs or?
2. Are you sure you are creating the mount point in read/write mode?
3. What operating system are you using?

**Comment by jkvargas** [comment]
Nevermind, solved it using uid files :)
Thanks anyways.
