### ISSUE TITLE
HMAC + keyfile doesn't work on wayland. 

### ISSUE THREAD

**Issue by arun54321** [mhogomchungu/sirikali#195]
I have a gocryptfs volume. it mounts fine on x11 but it doesn't open on wayland

DE: KDE
distro: arch
sirikali: 1.4.8

**Comment by mhogomchungu** [comment]
Are you saying that when you select HMAC+Keyfile option, the file dialog prompt does not show up or it does show up and you correctly set the keyfile but gocryptfs complains that the entered key is wrong?

**Comment by arun54321** [comment]
It shows dialog prompt but decryption fails when running on wayland.

**Comment by arun54321** [comment]
I will re-open the issue when I encounter it again and with proper reproducible steps.
