### ISSUE TITLE
GUI is unusable due to poor handling of desktop scaling in GNOME

### ISSUE THREAD

**Issue by DarwinAwardWinner** [mhogomchungu/sirikali#196]
I am testing out Sirikali on my Ubuntu 21.10 GNOME desktop. Unfortunately, the GUI is pretty much unusable due to what appears to be a weird interaction with my desktop scaling settings. In GNOME settings I have scaling set to 200%, which is the appropriate scaling for my screen. However, this causes Sirikali to look like this: 

![image](https://user-images.githubusercontent.com/228145/144712530-d8ab6384-14f7-4253-874d-425bed42840f.png)

If I temporarily set the scaling to 100%, everything looks fine (albeit very small on my screen):

![image](https://user-images.githubusercontent.com/228145/144712534-90fb0c7e-0fea-4caf-a901-cce8871f7fea.png)

Unfortunately, this dialog box cannot be resized, and I'm also unsure if resizing it would actually fix the issue.

**Comment by DarwinAwardWinner** [comment]
(Sorry, I accidentally hit submit too early! I will edit the description shortly.)

**Comment by mhogomchungu** [comment]
1. Set your desktop scalling to 200%.
2. On SiriKali, click "menu->settings" and then change "HiDPI" settings and restart and see if it makes a difference.
