### ISSUE TITLE
cygheap base mismatch detected

### ISSUE THREAD

**Issue by razkif** [mhogomchungu/sirikali#197]
>  0 [main] sshfs (24768) C:\Program Files\SSHFS-Win\bin\sshfs.exe: *** fatal error - cygheap base mismatch detected - 0x1127408/0x1137408.
> This problem is probably due to using incompatible versions of the cygwin DLL.
> Search for cygwin1.dll using the Windows Start->Find/Search facility
> and delete all but the most recent version.  The most recent version *should*
> reside in x:\cygwin\bin, where 'x' is the drive on which you have
> installed the cygwin distribution.  Rebooting is also suggested if you
> are unable to find another cygwin DLL.
>       0 [main] sshfs 1404 dofork: child -1 - forked process 24768 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
> failed to fork: Resource temporarily unavailable
> 
> -------------
> 
> SiriKali::Error Backend Disappeared Unexpectedly.

I've never installed Cygwin, I had a similar error while trying to use git bash.
I read something about ALSR protection on Windows causing this error for git bash users on Windows 10+. 

I ended up running these commands 
```
Get-Item -Path "C:\Program Files\Git\usr\bin\*.exe" | %{ Set-ProcessMitigation -Name $_.Name -Disable ForceRelocateImages }
Get-Item -Path "C:\Program Files\Git\bin\*.exe" | %{ Set-ProcessMitigation -Name $_.Name -Disable ForceRelocateImages }
Get-Item -Path "C:\Program Files\Git\*.exe" | %{ Set-ProcessMitigation -Name $_.Name -Disable ForceRelocateImages } 
``` 

in powershell to rid the isssues using git bash, but I still have issues running Sirikali.

I'm not sure if this is a ALSR issue or git issue or something else entirely.

**Comment by mhogomchungu** [comment]
Those logs clearly spell out the problem and suggests solutions.

This is a problem with sshfs-win and it should be reported here: https://github.com/billziss-gh/sshfs-win
