### ISSUE TITLE
add feature to support gocryptfs on windows

### ISSUE THREAD

**Issue by CodeCubeNeo** [mhogomchungu/sirikali#198]
Hello!

The title says it all! You can basically copy the idea and logic from https://github.com/bailey27/cppcryptfs which works very well and than we would truly have a cross platform gui for at least a single "cryptographic file system" (in this case gocryptfs). The cppcryptfs uses Dokan to get the FUSE filesystem features on windows... Everything works there (in cppcryptfs), you just have to copy it correctly.

**Comment by mhogomchungu** [comment]
They offer a CLI tool named "cppcryptfsctl" and thats the one i will use when adding the functionality.

**Comment by mhogomchungu** [comment]
This now works but it does not work as expected because of this issue i have encountered: https://github.com/bailey27/cppcryptfs/issues/150

![Screenshot_20220205_135009](https://user-images.githubusercontent.com/3496115/152642229-5777d63b-b10d-4374-9866-01c9999bbae4.png)

**Comment by mhogomchungu** [comment]
This feature is now complete.

**Comment by CodeCubeNeo** [comment]
Hello! Thanks, great job. Now you can also change the specification for supported backends on your website. And btw when will there be a new release?

**Comment by mhogomchungu** [comment]
I will make a new release on March 1st, 2022.

For now, you can get a working version from here:- https://github.com/mhogomchungu/sirikali/releases/download/1.4.8/SiriKali-dev-16-Feb-2022.setup.exe

To make it work, do the following:-
1. Install the program and run it.
2. Go to a "bin" folder located in your home directory(C:\users\XYZ\bin) and you will see a file named "cppcryptfs.json".
3. Open the file and then add a full path to a folder where you have both "cppcryptfs" and "cppcryptfsctl" programs. The full path should be added as a value to "FolderPath" json key. 
4. Use forward slashes(/) as a folder separator in the above step or two backslashes(\\)

There will be a GUI way to set where cppcryptfs binaries are located in the released version.

**Comment by CodeCubeNeo** [comment]
I just have a general question (if is it legal), if you can just use (package it together) the cppcryptfs and cppcryptctl in your windows installer (with correct licensing and talking about it with the cppcrypt developer, since it is floss software?). If yes, maybe you could also add the dokany library to fully complete the package? Just a question.

**Comment by CodeCubeNeo** [comment]
Hello! I was trying out this feature and it seems like the cppcryptfs program is still running after I quit, so maybe add an option to kill that program when exiting (since it is also started because of sirikali).

**Comment by mhogomchungu** [comment]
This version behaves as you expect: https://github.com/mhogomchungu/sirikali/releases/download/1.4.8/SiriKali-dev-24-Feb-2022.setup.exe

SiriKali will quit cppcryptfs only if it was the one that started it.

You are not the first one to suggest bundling of supported tools and i have so far resisted doing that because i will then have to update SiriKali everytime any of the bundled project is updated to make sure users of SiriKali are using the latest versions.

**Comment by CodeCubeNeo** [comment]
Thanks for the really quick response. I get why you don't want to package it all together, i just wanted to ask to better understand. Also thanks for making SiriKali kill the cppcryptfs process after it is done. Really appreciate your work!! :+1:

**Comment by mhogomchungu** [comment]
I made a new build because the posted one started crashing on my on start up so update to this one if you experience the crash: https://github.com/mhogomchungu/sirikali/releases/download/1.4.8/SiriKali-DEV-24-Feb-2022.setup.exe

**Comment by mhogomchungu** [comment]
New version is out and it has the official support for cppcryptfs

https://github.com/mhogomchungu/sirikali/releases/tag/1.5.0

![Screenshot_20220301_200724](https://user-images.githubusercontent.com/3496115/156216487-7896bbb6-ba03-48c5-a467-f51ddee62481.png)
![Screenshot_20220301_200800](https://user-images.githubusercontent.com/3496115/156216495-e8eb81e6-c9f7-4c57-a6b4-c15cc9ed27ea.png)
