### ISSUE TITLE
cryfs crash - no message

### ISSUE THREAD

**Issue by ail6b** [mhogomchungu/sirikali#199]
When a cryfs filesystem that cannot be opened (e.g. because the root directory has been corrupted) is opened by sirikali, it does not notify the user that the open was unsuccessful. It does not show up in the list of mounted dirs (which is good), however it still creates the directory ~/.Sirikali/name_of_filesystem, which remains there and is not cleaned up. Sirikali also opens the file manager for the given directory (which could be misleading, it could lead to an assumption that the files placed there will be encrypted, which is not the case, since there is nothing actually mounted there, because cryfs crashed).

To reproduce:
1. create a new cryfs filesystem
2. add a few very small text files for fun, but not too much so the later steps are easy
3. unmount it
4. go to the path with the encrypted files
5. go to the oldest modification date folder, it should (most likely) contain exactly one file
6. flip a bit or a character in the contents
7. try to mount the cryfs filesystem using the command cryfs in the terminal (it will show something along the lines of Could not load blob <long hex>. Is the base directory accessible? Crashed: Input/output error)
8. try to mount the cryfs filesystem in sirikali

Expected behavior:
Notify the user about the crash, do not open file browser, delete the empty folder in ~/.Sirikali

Edit: I am using the latest release sirikali, which is 1.4.8, compiled by myself. Cryfs 0.11.1.

**Comment by mhogomchungu** [comment]
You can get the debug window by pressing "CTRL+D" when SiriKali window has focus.

This is a log output i got when unlocking a corrupted file system
```
Command: "/usr/bin/cryfs" "--allow-replaced-filesystem" "--config" "/home/ink/cryfs/cryfs.config" "/home/ink/cryfs" "/home/_/cryfs_1" "-o" "rw,fsname=Cryfs@/home/ink/cryfs,subtype=Cryfs"
*************************************
The attempt to unlock the volume took 23 seconds
*************************************
-------
Exit Code: 0
Exit Status: 0
-------
StdOut:
CryFS Version 0.11.1
Automatic checking for security vulnerabilities and updates is disabled.

Password: 
Deriving encryption key (this can take some time)...done

----------------------------------------------------
Filesystem configuration:
----------------------------------------------------
- Filesystem format version: 0.10
- Created with: CryFS 0.11.1
- Last opened with: CryFS 0.11.1
- Cipher: xchacha20-poly1305
- Blocksize: 16384 bytes
- Filesystem Id: E1EFA0D44A8B8F67C7BE98BF1E4C32EC
----------------------------------------------------
-------
StdError:
[2022-01-05 21:43:42.362] [Log] [error] Crashed: This is not a valid block.
*************************************
```

I would say the problem is with Cryfs because it failed to unlock a file system but returned a result code of "0" which means success.

**Comment by mhogomchungu** [comment]
Rethinking the issue for a bit and i do nothing this issue can be solved easily.

What happens here is as follows:-
1. You unlock a file system successfully.
2. Shortly afterwards, CryFS notices a problem. with the file system and logs the error and unmounts it.
3. In both of our cases, CryFS noticed the problem immediately after unlocking a file system so it feels like the problem happens at file system unlocking stage but it is not and it may happens minutes or hours later.
4. I should be able to handle the scenario where CryFS disappears immediately after  successfully unlocking a file system.

**Comment by mhogomchungu** [comment]
This is now fixed in the git version.

The error observed here happens after a successful unlocking but before CryFS is daemonised and the error is mistaken to be related to unlocking process.

The fix i went with is checking for error messages on std error before CryFS is daemonized so the problem will still be there if CryFS crashes after it goes to the background but this will no longer mistaken to be related to unlocking process.

**Comment by ail6b** [comment]
Thank you for the quick fix!
