### ISSUE TITLE
Binary version numbers

### ISSUE THREAD

**Issue by Achim16** [mhogomchungu/sirikali#20]
I'm very happy that you point us to the site where binary distributions are offered (was waiting for 1.2.4 binary), however would you know why their version numbers are a bit misleading, most recent 
sirikali_1.2.3.1487072377.d49c2ab-0_amd64.deb (luckily) contains 1.2.4 inside the .deb.

Thanks

**Comment by mhogomchungu** [comment]
I forgot to update the version number. New packages with the correct version number should up within an hour or two.

**Comment by mhogomchungu** [comment]
1.2.5 was just released and binary packages will show up within an hour or two.
