### ISSUE TITLE
Error 24

### ISSUE THREAD

**Issue by Cherkah** [mhogomchungu/sirikali#202]
i have this message:
```Error 24: There was an integrity violation detected. Preventing any further access to the file system. This can either happen if an attacker changed your files or rolled back the file system to a previous state, but it can also happen if you rolled back the file system yourself, for example restored a backup. If you want to reset the integrity data (i.e. accept changes made by a potential attacker), please delete the following file before re-mounting it: /home/USER/.local/share/cryfs/filesystems/XXXXXXXXXXXXXXXX/integritydata```

Question:
If i don't want to delete the ../integritydata File, i cannot get access to my file.
so how to keep the previous version an access to it?

**Comment by mhogomchungu** [comment]
I do not know the answer to your question.

Cryfs specific issues should be reported to Cryfs bug tracker[1].

[1] https://github.com/cryfs/cryfs/issues
