### ISSUE TITLE
HiDPI can't be disabled

### ISSUE THREAD

**Issue by milroneth** [mhogomchungu/sirikali#211]
Once enabled in the settings, "Enable HiDPI Scaling" is impossible to turn off. Scaling can be set to 1 to achieve the same result, but unticking the checkbox does not persist.

**Comment by mhogomchungu** [comment]
What operating system are you using?

**Comment by milroneth** [comment]
Sorry, I had just mentioned it in another issue and forgot to include again. This is on Windows 10.

**Comment by mhogomchungu** [comment]
This is now fixed, thanks for the report
