### ISSUE TITLE
Sirikali does not detect cryfs

### ISSUE THREAD

**Issue by theCalcaholic** [mhogomchungu/sirikali#213]
Sirikali gives "Cryfs is not installed":

![image](https://user-images.githubusercontent.com/6317548/174998904-7f1220bc-6628-4aa8-b71a-e229724718ba.png)

However, cryfs has been installed and is in the path:

```sh
$ which cryfs
/usr/bin/cryfs
```

Sirikali version: 1.4.8
OS: Fedora 36
architecture: amd64

**Comment by mhogomchungu** [comment]
Did you restart SiriKali after installing CryFs?

**Comment by theCalcaholic** [comment]
Yes multiple times, but that didn't help. Finally, after leaving it open for a few minutes, cryfs was available
