### ISSUE TITLE
sirikali stopped working after updating gocryptfs

### ISSUE THREAD

**Issue by arun54321** [mhogomchungu/sirikali#216]
I'm using HMAC+keyfile to unlock volume. it was working fine till I update gocryptfs from 1.8 to latest version (2.2.1)

```
Failed To Complete The Task And Below Log was Generated By The Backend.

----------------------------------------
flag provided but not defined: -q
Usage: gocryptfs-xray [OPTIONS] FILE

Options:
  -0	Use \0 instead of \n as separator
  -aessiv
    	Assume AES-SIV mode instead of AES-GCM
```

**Comment by mhogomchungu** [comment]
What OS are you using?

That output says the program that was called was "gocryptfs-xray" and not "gocryptfs".

Check your system and make sure "gocryptfs" executable actually points to "gocryptfs" executable.

**Comment by arun54321** [comment]
I have cleaned everything and recompiled both gocryptfs and sirikali. it is working fine now.
Probably an issue with my installation.
