### ISSUE TITLE
Password with non ASCII characters incorrectly saved in Kwallet

### ISSUE THREAD

**Issue by SP-937-215** [mhogomchungu/sirikali#217]
Operating System: Arch Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.16-arch1-1 (64-bit)

While creating a favorite, password with "é" is incorrectly saved in Kwallet. It is replaced by "?".

As a result the volume cannot auto-mount as the password is incorrect.

**Comment by mhogomchungu** [comment]
Give me an example of key i can use to test

**Comment by SP-937-215** [comment]
You can use: "tête" as a password to test


------- Original Message -------

**Comment by mhogomchungu** [comment]
It should be fixed with this[1] commit. Update from git and make sure you are using internal lxqt_wallet and try again. You can force building with internal lxqt_wallet by running cmake with option ```-DINTERNAL_LXQT_WALLET=true```

[1] https://github.com/mhogomchungu/sirikali/commit/8c00bf99718db8b0613f6beeae4cdd9d1a624d09

**Comment by SP-937-215** [comment]
Thanks a lot, I test the fix before the end of the week!


------- Original Message -------
