### ISSUE TITLE
Question: how to mount an ssh filesystem (sshfs-win) with private/public key pair, when the keyfile is encrypted with passphrase?

### ISSUE THREAD

**Issue by aetonsi** [mhogomchungu/sirikali#218]
Hello!
I have a remote windows 11 computer (server) with an openssh server running.
On my laptop running windows 11 (client), I would like to mount the server's remote filesystems via sshfs (sshfs-win).
So I set up private/public key pair, and for additional security i have encrypted my private key with a passphrase.
Is there some way to make this work with sirikali?
I see that in issue #128 you mentioned "A password protected private key when doing public/private key authentication should first be loaded to a key agent and then SiriKali be configured to use the key agent.".
Could you kindly expand and explain more about it? What are the steps? I tried loading the private key with `ssh-add.exe` and `pageant.exe`, but then what do i do?

Thanks!

**Comment by LinoBarreca** [comment]
Good question. I'd like to know also.
my ssh-agent has the key added and if I SSH from windows it connects without asking anything else

**Comment by mhogomchungu** [comment]
[Entry number 4] i(https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#90-how-do-i-add-options-to-connect-to-an-ssh-server) has the answer to this question.
