### ISSUE TITLE
Cppcryptfs not detected

### ISSUE THREAD

**Issue by n3rdcub** [mhogomchungu/sirikali#219]
Just finished installing the program and all the options, but I can't get cppcryptfs to detect? It's open and running and double checked the guide, don't think its an issue with installation.

**Comment by mhogomchungu** [comment]
Click menu->settings->external commands and then click the button pointed at in the image below and then select a folder that contains both cppcryptfs.exe and cppcryptfsctl.exe and then restart SiriKali.

![Screenshot_20220927_083046-1](https://user-images.githubusercontent.com/3496115/192441130-c4ab4107-18a1-4e10-9fbc-bae802185e67.png)
