### ISSUE TITLE
SiriKali does not work with CryFS

### ISSUE THREAD

**Issue by CaptainQuake** [mhogomchungu/sirikali#221]
![1](https://user-images.githubusercontent.com/75237891/196152206-7b8d4266-18fc-4fe5-a185-a82505148d3d.jpg)
![2](https://user-images.githubusercontent.com/75237891/196152227-7c8f0d2e-d61f-4a0a-92e9-a02ffe3894ca.jpg)
![3](https://user-images.githubusercontent.com/75237891/196152308-7e45a7f7-d0d3-4f5a-aa08-de308a003bea.jpg)

**Error Code:**
```
Failed To Complete The Task And Below Log was Generated By The Backend.

----------------------------------------
SiriKali::Error: Backend Reported "Success" But Its No Longer Running
Generated Logs Are:
std error
----------------------

----------------------
std out
----------------------
```

**OS: Windows 10 Pro x64
SiriKali 1.5.0
CryFS 0.11.3
Docan 2.0.4
WinFSP 1.10.22006**

**Comment by CaptainQuake** [comment]
> I suspect the problem is caused by CryFS successfully unlocking the volume but then discovers afterwards that there is a problem with your CryFS encrypted folder and then printed an error message and exited. SiriKali noticed CryFS disappeared unexpectedly but failed to capture CryFS last output message.
> 
> Run CryFS from the terminal to see what error message is reported before it exits.

**Test with CLI**
![7](https://user-images.githubusercontent.com/75237891/196349959-2102b7db-2477-4645-948e-bee0f74f0514.jpg)

**Comment by mhogomchungu** [comment]
Local test confirms your finding.

The problem is with CryFS reporting successful unlocking while it failed to so and there are two bug reports about this and they are [here](https://github.com/cryfs/cryfs/issues/434) and [here](https://github.com/cryfs/cryfs/issues/440).

**Comment by CaptainQuake** [comment]
> Local test confirms your finding.
> 
> The problem is with CryFS reporting successful unlocking while it failed to so and there are two bug reports about this and they are [here](https://github.com/cryfs/cryfs/issues/434) and [here](https://github.com/cryfs/cryfs/issues/440).

after installing dokan 1.5.1.1000 the mount worked
![1](https://user-images.githubusercontent.com/75237891/196857355-e7fdb6b9-212c-4bae-8206-8e486c891687.jpg)
![2](https://user-images.githubusercontent.com/75237891/196857374-bddcc65f-1dbe-4860-a668-d3926b373020.jpg)

**Comment by mhogomchungu** [comment]
Thanks for confirming that CryFS works with dokany 1.5 and hence this a problem with CryFS itself.
