### ISSUE TITLE
Broken GUI in KDE Plasma 5.26 (Debian Testing)

### ISSUE THREAD

**Issue by Freeedim** [mhogomchungu/sirikali#223]
As said in the title, the GUI is totally broken.

It's been the case for a while actually, but it slipped off my mind.

None of the bottom buttons appear, but they can be (blindly) clicked. When clicked, their menu items get scrambled when the mouse pointer hovers over them. When clicking on an item that was not too much scrambled, the launched action is however the next item's action.

I am using an X server (not Wayland), Sirikali 1.5.0 (Compiled with Qt 5.15.6).

My window management information is:
```
Version
=======
KWin version: 5.26.3
Qt Version: 5.15.6
Qt compile version: 5.15.6
XCB compile version: 1.15

Operation Mode: X11 only

Build Options
=============
KWIN_BUILD_DECORATIONS: yes
KWIN_BUILD_TABBOX: yes
KWIN_BUILD_ACTIVITIES: yes
HAVE_X11_XCB: yes
HAVE_EPOXY_GLX: yes
HAVE_WAYLAND_EGL: yes

X11
===
Vendor: The X.Org Foundation
Vendor Release: 12101004
Protocol Version/Revision: 11/0
SHAPE: yes; Version: 0x11
RANDR: yes; Version: 0x14
DAMAGE: yes; Version: 0x11
Composite: yes; Version: 0x4
RENDER: yes; Version: 0xb
XFIXES: yes; Version: 0x50
SYNC: yes; Version: 0x31
GLX: yes; Version: 0x0
```

**Comment by mhogomchungu** [comment]
Do you have any volumes set to automount at start up or do you start the app externally with a volume path already set to unlock?

**Comment by Freeedim** [comment]
I am not sure I understand well your question.

I just click on the app in KDE's application launcher menu.

I have a VeraCrypt partition volume that automounts at system startup through crypttab and cryptsetup. But Sirikali has no settings from me (no auto-mounts, no favorites etc.)

**Comment by mhogomchungu** [comment]
I have no idea its not working for you. SiriKali uses QWidget and does not customize them in any shape or form.

Have you enabled hidpi scalling in SiriKali settings?
Are you using a dark theme in SiriKali settings?
Are you using a scale factor with a value other than 1.0 in SiriKali settings?

**Comment by Freeedim** [comment]
I couldn't know as the GUI was too broken to see anything on the settings panel.

So I just `apt purge`'d SiriKali and reinstalled it to have the default settings. And it's exactly the same, no improvement.

I do have a dark theme in plasma, with the default 100% scale and no forced font DPI in Plasma settings. My Look-and-feel theme is QtCurves (but I tried with Adwaita, Breeze, Kvantum, and nothing changed).

I have no error message in the system logs when opening SiriKali.

**Comment by Freeedim** [comment]
Actually, Sirikali works well if I launch it with:
`sudo sirikali`
My root user does not have a dark theme, in case it matters.

However, when run as root, here is what happens:
- "Enable HiDPI scaling is enabled by default.
- If I uncheck it close the app, re-open it with `sudo sirikali` and go to the settings panel, the checkbox will still be checked.

**Comment by mhogomchungu** [comment]
To get default SiriKali settings in your user account, do the following:-
1. Close SiriKali
2. Delete SiriKali folder located at $HOME/.config/SiriKali
3. Start SiriKali.

**Comment by mhogomchungu** [comment]
I can reproduce the issue now when setting the scaling factor to 0.8.

I am glad  we found the problem and the current default value does not have it
