### ISSUE TITLE
[macOS] user configs(favorites) should not be stored in ~/Library/Preferences

### ISSUE THREAD

**Issue by eugenesvk** [mhogomchungu/sirikali#224]
Currently Sirikali stores favorites in `~/Library/Preferences/SiriKali/favorites`

However, per [Apple docs](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) `~/Libray/Preferences/`:

> You should not create files in this directory yourself

The default platform folder for GUI configs is `~/Library/Application Support/`, whics has this description:

> Put app-created support files in the Library/Application support/ directory. In general, this directory includes files that the app uses to run but that should remain hidden from the user. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle.

**Comment by mhogomchungu** [comment]
The code that created the favorites's parent path is [here](https://github.com/mhogomchungu/sirikali/blob/bc588ae95ed1825c09773fb3c57f62d8cf997f1d/src/settings.cpp#L606).

A list of QStandardPaths is [here](https://doc.qt.io/qt-6/qstandardpaths.html) and you seem to suggest i should use ```QStandardPaths::RuntimeLocation```

What problems do you have with the current location?

**Comment by mhogomchungu** [comment]
Git version has "QStandardPaths::AppDataLocation" as a new location.
