### ISSUE TITLE
German and other translations not available any more

### ISSUE THREAD

**Issue by Oli72** [mhogomchungu/sirikali#225]
The option to select the German language is gone in version 1.5.0 (Qt 5.15.3) on my installation of Linux Mint 21.1 Cinnamon. I only see English, French, and Russian.
In the previous version I used (1.4.2, Qt 5.12.5, Linux Mint 20.3 Cinnamon) there were many more languages to select.

**Comment by mhogomchungu** [comment]
Re added and i think i disabled it because it misses too many translations.
