### ISSUE TITLE
Unmount does not work

### ISSUE THREAD

**Issue by linuxissuper** [mhogomchungu/sirikali#233]
It seems SiriKali doesn't use a command for unmounting:   
![image](https://github.com/mhogomchungu/sirikali/assets/74221543/fc1c9f64-cc17-4507-ada8-4826b925e41b)  
  
I'm on NixOS and built it myself (I probably forgot something?)  
But I also tried a version installed through AUR on distrobox and there I get the same error   
`QIODevice::read (QProcess): device not open`   
 
Am I missing some option?

**Comment by mhogomchungu** [comment]
Where they mounted with SiriKali?

Those logs says SiriKali is failing to locate gocryptfs executable.

**Comment by linuxissuper** [comment]
ah I see, thanks

**Comment by linuxissuper** [comment]
This may be a stupid question, but is there a way of making SiriKali aware of the `PATH` variable?

**Comment by mhogomchungu** [comment]
Where is fusermount located in your system?

[This](https://github.com/mhogomchungu/sirikali/commit/d0f5e34f21ae1e3f3d39021a5ba075d7df47acca) commit should solve your issue.

Please update your sources from git version and try again.

**Comment by linuxissuper** [comment]
`/run/wrappers/bin/fusermount` (it's all a little different on NixOS)  
hm, I've updated and rebuilt but it still doesn't work  

but this is probably nix problem  
and I have to adjust my build config

**Comment by mhogomchungu** [comment]
This should now be solved by [this](https://github.com/mhogomchungu/sirikali/commit/e032bb0928741acd10a2448c0e7b6e573b66f72a) commit and it now shows a descriptive error when fusermount can not be found.

I am not sure of a reason but there was one that made me intentionally not including the PATH variable when searching for executables.

![Screenshot_20230605_165748](https://github.com/mhogomchungu/sirikali/assets/3496115/08cad7e9-0f1c-4d6e-a9e2-cacabdb5091b)

**Comment by Saroumane** [comment]
I think a lot of people will encounter this problem, when their distro upgrade to a newer `libfuse` package.
This bug report https://github.com/libfuse/libfuse/issues/794 (from May) says that `fusermount` is not provided anymore by libfuse and that `fusermount3` is not entirely compatible.

For now, I did  : 
`$ sudo ln -s /usr/bin/fusermount3 /opt/bin/fusermount`
and so far it works.

**Comment by mhogomchungu** [comment]
I tried with gocryptfs version 2.4.0 and my observations are on unlocking, gocryptfs tries to use mount command and if that fails then it uses fusermount3 if available and falls back to fusermount.

I think the best solution here is for gocryptfs to handle  unmounting of its volume because it knows how it mounted them. The best i can do is guess work and that is not nice.

Will open a feature request to ask gocryptfs to add an option to lock their volumes.

In the mean time, i will try with fusermount3 if present and fall back to fusermount.

**Comment by mhogomchungu** [comment]
I have opened a feature request to ask gocryptfs to also handle unmounting.

https://github.com/rfjakob/gocryptfs/issues/810
