### ISSUE TITLE
SiriKali on Windows (Yubikey / ykchalresp)

### ISSUE THREAD

**Issue by Aetherinox** [mhogomchungu/sirikali#242]
Two questions
1. I've seen mention of a sirikali.conf config file on Linux, do we have this option on Windows? If so, how do we get one going? I've done a complete system search on Windows to find this file and cannot find it.
2. When attempting to create a volume using the Yubikey Challenge Response, it immediately fails and says that it cannot find ykchalresp

The reason for the config file is that I've seen mentioned that you can change the yubikey challenge response slot that is used:
- https://github.com/mhogomchungu/sirikali/issues/176

I've also tried the **Set Executable Search Path** setting in the SiriKali interface itself. No change.

As for the ykchalresp error. I have the bin folder for the Yubikey Personalization tool added to my Windows Environment Variables, and I can access ykchalresp from any folder in Powershell and Command Prompt, so it should be finding it ok.

Tried the debug windows, and it shows absolutely nothing at all.

---
**Edit**: So I decided to try something after my post in regards to it not locating the ykchalresp binary. So I'll drop it here in case anyone searches.

In regards to the SiriKali setting **Set Executable Search Path**; do not just copy the folder and paste it into SiriKali. It will paste with forward slashes `/` and it won't work. The forward slashes `/` must be backward slashes `\` for the path.
```
X:\Path\To\Binaries\
```

I copied and noticed it looked off. But once I changed them, it appears to find it now. But also keep in mind, if you have the TOUCH policy enabled, you will get no notification of it needing a response from you, the Yubikey will just blink. Make sure you watch for it blinking. The screen will not say anything.

---

So for now, I guess my only option is about the config file, and how I can get Sirikali to look for a Challenge Response on Slot 2 instead of 1.

**Comment by mhogomchungu** [comment]
The config file is located at ```C:\Users\$USER\AppData\Local\SiriKali\settings```

**Comment by Aetherinox** [comment]
> The config file is located at `C:\Users\$USER\AppData\Local\SiriKali\settings`

Thanks. I had already checked there, but I don't have a settings config. I also looked in this Github repo for a template so I could just make it, and I couldn't find that either. Unless I'm missing something.

I'll try installing SiriKali on my Linux machine and see if that'll create one I can copy to my Windows machine.

![image](https://github.com/mhogomchungu/sirikali/assets/118329232/e269eaef-f9dd-42a3-bd4f-38ee0c0b19ba)

**Comment by mhogomchungu** [comment]
You are looking in the wrong path, the config file is called "settings.ini" and is in the first "SiriKali" folder, not the second.

I see what is in the image below

![Screenshot_20231112_222715](https://github.com/mhogomchungu/sirikali/assets/3496115/e582ed78-d018-498c-b887-2d1da376501c)

**Comment by Aetherinox** [comment]
Correct, I've looked in there too. There's no settings folder at all.

![image](https://github.com/mhogomchungu/sirikali/assets/118329232/b9b2b48f-4fb8-4986-9027-02fc096c28fe)

The entire structure of that folder is the following:
```
C:.
└───Users
    └───Username
        └───Appdata
            └───Local
                └───SiriKali
                    └───SiriKali
                        ├───favorites
                        │       XXXXXXXXXXXXXXX-ab95a2a0a8fad607a77daba0bb15ce3682135673e42c862aa1adb95e03657094.json
                        │       XXXXXXXXXXXXXXX-c0cfe387654341b21ab0eac3cd3b6ce1aa4bf3467898850ff733429126676823.json
                        │
                        └───themes
                                Dark.json
```

I see two SiriKali folders. In the first screenshot, there's on SiriKali folder by itself with nothing else. And then inside that one is another which contains favorites and themes.

**Comment by Aetherinox** [comment]
So, after all that pain. I found all the settings because I wondered if I had no settings file, where they were being saved.

I found them in the Registry
![image](https://github.com/mhogomchungu/sirikali/assets/118329232/9a2b265d-825a-4ff2-aecd-02eec6fffcd1)

After reinstalling, I now see a `bin` and `settings` folder: 
![image](https://github.com/mhogomchungu/sirikali/assets/118329232/12920489-8d04-4328-a521-a5d2664b660f)

Those definitely weren't there before as in my other screenshots. So I'm not sure if I was originally on an older version which saved to the registry, and I never had the settings file created, but I now have

```ini
[General]
AutoCheckForUpdates=false
AutoMountFavoritesOnAvailable=false
AutoMountFavoritesOnStartUp=false
AutoMountPassWordBackEnd=none
AutoOpenFolderOnMount=true
[...]
```

It's solved now, but just putting it all here because I knew I wasn't crazy lol. I looked everywhere. Like I said, maybe I started out on an older version and somehow settings were never migrated from registry to the settings file. I'm not sure how your code does it, but I was definitely missing what I have now.

**Comment by mhogomchungu** [comment]
I am glad you got this solved.

Version 1.5.1 has a few changes and two of them that are applicable to you are:-

1. Settings are saved in a config file instead of registry to make it easy to manually change them.
2. System paths are searched when looking for executables.

Glad you have this one solved

**Comment by Aetherinox** [comment]
Appreciate it.
Should have checked for the update sooner tbh. I know SiriKali doesn't update that often and I thought I had already installed it earlier this year, but when I checked the version I noticed it outdated.

Sorry for the troubles. Damn simple update could have saved a lot of time.
