### ISSUE TITLE
The checkbox show error.

### ISSUE THREAD

**Issue by GongHeng2017** [mhogomchungu/sirikali#244]
![截图_选择区域_20231116134851](https://github.com/mhogomchungu/sirikali/assets/32997802/918fc06d-97e8-41b0-8bbc-527af0568bd2)

**Comment by mhogomchungu** [comment]
I do not see what the problem is, can you explain it.

**Comment by GongHeng2017** [comment]
@mhogomchungu 
The Checkbox and Label controls did not use the layout device, but were directly placed manually, which caused the blue border control of Checkbox to be completely displayed. To the right position, the blue border of Checkbox will not be covered by the label control.As the picture shows above, the blue border of Checkbox is not completely displayed.
I have fixed the above questions, and the link to submit the link is:
https://github.com/mhogomchungu/sirikali/pull/243
https://github.com/mhogomchungu/sirikali/pull/245

Do you have any ways to communicate in time, such as mailboxes, so that you can communicate at any time.

**Comment by mhogomchungu** [comment]
I read all emails usually within hours after they are posted but sometimes i forget to respond when i postpone commenting immediately and a solution is a gentle reminder like what you did here.

Sorry for the delay.
