### ISSUE TITLE
Installed"Sshfs" Version Is Too Old (3.5.2)

### ISSUE THREAD

**Issue by dlasher** [mhogomchungu/sirikali#247]
* latest 32 or 64-bit SSHFS (3.5.20357) from: https://github.com/winfsp/sshfs-win/releases/tag/v3.5.20357
* latest WinFSP (2.0.23075) from: https://github.com/winfsp/winfsp/releases
* latest Sirikali (1.5.1) from : https://github.com/mhogomchungu/sirikali

Attempting to mount SSHFS connection, complaint is:
```
Installed"Sshfs" Version Is Too Old.
Please Update to Atleast Version 3.5.2.
```

Nothing in debug window.

Suggestions?

**Comment by zlyfer** [comment]
I can confirm that the portable version is showing this error even if SSHFS is installed.
Once I installed SiriKali using the setup it worked perfectly fine.
![image](https://github.com/mhogomchungu/sirikali/assets/7332940/b07bda96-37fa-4508-ac03-1113c77cf31e)

**Comment by mhogomchungu** [comment]
I still can not reproduce, do the following please.
1. Start problematic SiriKali.
2. Press CTRL+D to bring up debug window.
3. Attempt to unlock an sshfs volume.
4. Close the password windows after you get the "too old" error.
5. Post here the contents of the log window.

**Comment by Luke-Tang** [comment]
sshfs-win-3.7.21011-x64
SiriKaliQt6-1.7.1.setup
winfsp-2.0.23075
![image](https://github.com/user-attachments/assets/e1510ed7-a103-4274-a00c-d0d8443fce18)
![image](https://github.com/user-attachments/assets/565fa4b7-c517-437b-b5fb-26102ce57a23)
![image](https://github.com/user-attachments/assets/23399c63-ccf0-4d7d-8586-c4f4d3f12e67)

**Comment by mhogomchungu** [comment]
Please go to "HKEY_LOCAL_MACHINE\SOFTWARE\SSHFS-Win" registry and then post here the contents of "InstallDir" key.

**Comment by mhogomchungu** [comment]
I have disable checking for sshfs minimum version requirement.

Use git versions from [here](https://github.com/mhogomchungu/sirikali/releases/tag/1.5.2) for now and will close this bug report when a new version is out.

**Comment by Luke-Tang** [comment]
> I have disable checking for sshfs minimum version requirement.
> 
> Use git versions from [here](https://github.com/mhogomchungu/sirikali/releases/tag/1.5.2) for now and will close this bug report when a new version is out.

this worked!
