### ISSUE TITLE
OSX: Sirikali window is not visible in Mission Control

### ISSUE THREAD

**Issue by larsnystrom** [mhogomchungu/sirikali#25]
The macOS Mission Control is like Ubuntu's `super+w`, it's a way to display all open windows at the same time. However, Sirikali doesn't appear in Mission Control:

![apr -04-2017 10-15-50](https://cloud.githubusercontent.com/assets/1000370/24647653/11e48f66-1921-11e7-8269-599bbeb3a507.gif)

As you can see the Sirikali window just fades away when you open Mission Control. When you close mission control the Sirikali window re-appears for a split second before losing focus to the application below it.

**Comment by mhogomchungu** [comment]
I dont think i can do anything with this one since the problem appear to be between Qt and MACOS.
