### ISSUE TITLE
In Favorites menu, gray the action of file not exist may be a good choice.

### ISSUE THREAD

**Issue by GongHeng2017** [mhogomchungu/sirikali#254]
Problem:
![image](https://github.com/mhogomchungu/sirikali/assets/32997802/cd43830d-ff61-492f-bb70-e991b766702d)
When the file of "/home/jerry/base1" dose not exist，we can still click the action to enter the unlocking process. We all know that the next unlocking process will definitely fail.

Suggestion:
Therefore, it is recommended that there is no need to enter the unlocking process. Gray the action. 
Users can enter the <Manage Favorites> dialog to remove the invalid Volume Path.
like that:
![image](https://github.com/mhogomchungu/sirikali/assets/32997802/0b9dc87e-ba61-4a45-b5c2-ea92df2b01d7)

**Comment by mhogomchungu** [comment]
Thank you, pull request accepted.
