### ISSUE TITLE
Unable to mount securefs volume

### ISSUE THREAD

**Issue by himboruah** [mhogomchungu/sirikali#257]
I can create securefs volume just fine. But when I try to mount it later, it says "Not supported volume encountered".

Securefs binary used: [securefs v1.0.0](https://github.com/netheril96/securefs/releases/tag/v1.0.0)

Tested on Windows 10 x64

**Comment by mhogomchungu** [comment]
The problem is caused by securefs changing the name of the config file from ```.securefs.json``` to ```.config.pb```.

Renaming the config file back to ```.securefs.json``` in your new volume should solve the issue.

There are other changes in this 1.0.0 the developer says he is going to reverse "in a few days" and i am waiting for a new securefs release with the changes before i make a new release of SiriKali that supports this new configuration file name.

**Comment by himboruah** [comment]
Oh! Didn't know that. Thanks for the info. I'll look forward to the updates.

Also, it's great to see you right behind the other devs. Thank you.

**Comment by mhogomchungu** [comment]
New version is out and it should now work as expected with the latest version of securefs.

https://github.com/mhogomchungu/sirikali/releases/tag/1.6.0

**Comment by himboruah** [comment]
Hi @mhogomchungu, just tried the new version. But I'm facing issues with it. SiriKali hangs when I try to create a new securefs volume. And if I force close it and try to open the volume that I just created, it throws the following error.

Failed To Complete The Task And Below Log was Generated By The Backend.

----------------------------------------
[Error] [00000000000017BC] [2024-05-11 15:10:53.585817800 UTC] [int __cdecl securefs::commands_main(int, const char *const *):1446]    class securefs::POSIXException: No such file or directory (Z:.12482)

**Comment by mhogomchungu** [comment]
I have updated windows build, try version 1.6.0.1 and see if it solves the problem.

**Comment by himboruah** [comment]
O yea, it solved the issue. Thank you very much. 

One small thing that I noticed while creating a securefs volume is, the default "Volume Path" is set to "C:/Users/Username/Desktop/Desktop". This creates a folder named desktop on the desktop. I think you can get rid of that folder, if it's not by design.

**Comment by himboruah** [comment]
![Screenshot 2024-05-13 114531](https://github.com/mhogomchungu/sirikali/assets/148325082/ee841776-06d7-4edd-9b25-42a7e8aa6661)

And I believe it should've been "Password+KeyFile" instead of "Key+Keyfile".
