### ISSUE TITLE
FEATURE - update encrypted filesystem versions

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [mhogomchungu/sirikali#261]
Probably not without issues, but it would be nice if the new pop-up which advises of **old file-system versions** (nice!) also had the option of "update now?"

I ask this only as its a bit of a pain to go out and grab them all via Github, etc.

I feel it would be safe enough to grab the latest of each version off GitHub and install it on behalf of the user, system dependant (Im ignorant of how Windows and Mac might fit into this)

Its only a tiny request, importance 1 out of 10.

**Systems SK is used on:**  Linux Mint Cinnamon 22.3

Therefore many of the fils-system versions are a bit old and on "stable".

**Comment by mhogomchungu** [comment]
I have another project named "Media Downloader" and it can auto update its programs from github on Linux, Windows and MacOS so i have experience with how to do it.

This "Media Downloader" works more or less like SiriKali but it deals with programs that do media downloading.

Media Downloader started as a fork of SiriKali.

https://github.com/mhogomchungu/media-downloader

**Comment by AtomicRobotMan0101** [comment]
I've been using SiriKali for mounting a "third" backup system (just to be safe)

Its an ANCIENT hard disk plugged to a Modem with USB. It has only FAT32 and USB2, all shared with SMB 1.0... all updateable and completely unable to be flashed to a better OS (such as OpenWRT)

Its terrible and a security nightmare. But with Siri Kali I now put that old beast to use... love it. Absolutely love it.

Wanted to write and say how much I appreciate your work, the simplicity of how you've presented it and the fact you have other top-notch FOSS here on Github.

Thank you.

**Comment by mhogomchungu** [comment]
Update on this feature request

Version 1.7.1 is out and this feature is now opt in. To enable it, set option at "menu->settings->manage Securefs and Gocryptfs".

Only the above mentioned two are supported on linux at the moment because they are the only ones that offer a binary in their github pages.
https://github.com/mhogomchungu/sirikali/releases/tag/1.7.1
