### ISSUE TITLE
Nowhere to store keyfile location for favorites

### ISSUE THREAD

**Issue by sm8ps** [mhogomchungu/sirikali#262]
Recently, I switched to using key+keyfile for encryption and it does work well when mounting manually. When adding the container to the favorites, however, I have not found any way to store that information. I could add the resulting passphrase (SHA(key,keyfile) or so) but that defeats the purpose of using a keyfile in the first place. I would like to specify that the container uses a certain local keyfile and then manually type the password. Furthermore, it should also be possible to store both pieces of information in a wallet for fully automatic mounting.

I hope that I am not overlooking something obvious. Thanks for your consideration as well as this great application!

**Comment by mhogomchungu** [comment]
Git version now allows setting a path to a keyfile in a wallet. 

You will get the behavior you want if you set a keyfile but not a password and automounting will be possible if both are set.

Ui that allows entering keyfile in a wallet now looks like below.

![Screenshot_20240719_145934](https://github.com/user-attachments/assets/df8b5f2b-d5f8-4ce4-a90f-71eed5a251a6)

**Comment by sm8ps** [comment]
Great work! Thanks a lot for your excellent work with Sirikali.
Cheers!
