### ISSUE TITLE
Custom mount options

### ISSUE THREAD

**Issue by sokeeflo** [mhogomchungu/sirikali#27]
Is there a way to provide custom options to execute during mounting filesystem?

For example I would like to use `-allow_other` option for mount gocryptfs filesystem and I don't see how to do it.

**Comment by mhogomchungu** [comment]
Latest git version now has this ability. Add an entry to the favorites like and fill up the "mount options" field
with ```allow_other```. Rememember to NOT add the "-" before the argument.

Will appreciate if you can confirm that it works.

**Comment by sokeeflo** [comment]
It works, thank you!

**Comment by mhogomchungu** [comment]
Version 1.2.7[1] of SiriKali is out and it has this feature. Updating to a released version is advised.

[1] https://github.com/mhogomchungu/sirikali/releases/tag/1.2.7

**Comment by mhogomchungu** [comment]
Latest git version now has an option to set mount options without first creating a favorite entry for the volume. The options are entered on the third field on the dialog.

To active the dialog,click "options" button on the dialog that gives opportunity to create/unlock volumes.

![screenshot_20170603_154712](https://cloud.githubusercontent.com/assets/3496115/26753676/3017d11e-4874-11e7-8ce1-fe476d0f2baf.png)
