### ISSUE TITLE
Rename my Favorits

### ISSUE THREAD

**Issue by hollysheep** [mhogomchungu/sirikali#271]
Hi,

i have 2 Favorites (CryptFS) that i mount with write permissions. I want to create for each of them a Favorite  to mount them read-only. There is a Tray Icon in the Panel, i mount the Favorites with right click on the Icon. Here i see the path to the encrypted folder. For my it would be a good Idea when instead of the Path a self-chosen name is shown, so that i can create one Favorite to mount with write permissions and one for read-only.

**Comment by mhogomchungu** [comment]
I think the fundamental problem you have is that:-
1. You have two entries in the menu and they point to the same volume.
2. One entry unlocks the volume in read only mode.
3. Another entry unlocks the same volume in read/write mode.
4. You want the UI to make it possible to easily tell them apart.

The simplest solution here is add "(ro)" or "(rw)" next to the volume path to easily tell them apart.

This is a nice trick by the way. I find it very annoying to constantly check/uncheck the check box to unlock in read only or read/write mode.

**Comment by mhogomchungu** [comment]
This is now fixed as explained above.
