### ISSUE TITLE
User name containing '@' characters break connection

### ISSUE THREAD

**Issue by krpt** [mhogomchungu/sirikali#272]
Hi,
I want to mount a remote server fs via Bastion, so the username I have to use contains '@' characters which broke the connection process because I suppose you split the connection string using the '@' char.
Could it be possible to separate the connection field into 2 fields, one for the user one for the host like winscp ? 
Or doing a little bit of magic and only retrieving the end of the string to the last @ to fill the server value for connection.
Thanks !

**Comment by mhogomchungu** [comment]
SiriKali does not split the path.

While SiriKali has focus, press "CTRL+D" to bring up debug window and then try to connect and post the contents of the debug window.

PS:
Look first at the output and mask out any sensitive information.

**Comment by krpt** [comment]
Here's the debug output : 
"*************************************
Warning, Wallet Not Set
*************************************
*************************************
1. Processing favorite entry: Sshfs XX@XX@target_server:XX@bastion.si.cnaf.info:/home/nagios
2. Failed to obtain password from wallet
*************************************
Command: "C:\Program Files\SSHFS-Win\\\bin\/sshfs.exe" "-f" "XX@XX@target_server:XX@bastion.si.cnaf.info:/home/nagios" "Z:" "-o" "rw,fsname=Sshfs@XX@XX@target_server:XX@bastion.si.cnaf.info:/home/nagios,subtype=Sshfs,create_file_umask=0000,create_dir_umask=0000,umask=0000,idmap=user,StrictHostKeyChecking=no,volname=nagios,PreferredAuthentications=password,password_stdin"
*************************************
warning, a process is no longer running
*************************************
*************************************
The attempt to connect took 25.99 seconds
*************************************
*************************************
Process Finished
*************************************
-------
Exit Code: -1
Exit Status: 0
-------
StdOut:
ssh: connect to host target_server: Connection timed out
read: Connection reset by peer
-------
StdError:
*************************************

I made it work with sshfs under cygwin with the user specified in the .ssh/config , it didn't like the user right in the command line be it with single quotes or @ escaped..

**Comment by mhogomchungu** [comment]
Glad you found the solution to the problem and thank you for inform the rest of us.
