### ISSUE TITLE
Error while importing PGP key

### ISSUE THREAD

**Issue by shuvashish76** [mhogomchungu/sirikali#274]
While trying to install https://aur.archlinux.org/packages/sirikali it says

```
:: (1/1) Parsing SRCINFO: sirikali
gpg: WARNING: unsafe permissions on homedir '/home/user/.gnupg'
gpg: error reading key: No public key

 :: PGP keys need importing:
 -> 6855E493B5B2DF96E319BB6D16E2E1ACC6F51242, required by: sirikali
:: Import? [Y/n] 
:: Importing keys with gpg...
gpg: WARNING: unsafe permissions on homedir '/home/user/.gnupg'
gpg: key 16E2E1ACC6F51242: no user ID
gpg: Total number processed: 1
 -> problem importing keys
```

While run as `sudo` it says

```
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
 -> error making: sirikali-exit status 10
 -> Failed to install the following packages. Manual intervention is required:
sirikali - exit status 10
```

Any ideas?

**Comment by mhogomchungu** [comment]
Hi and sorry for a late reply, it says above not to run makepkg from root account, have you tried running it from normal user account?

**Comment by shuvashish76** [comment]
> it says above not to run makepkg from root account

That's the 2nd error if I run `sudo yay -S sirikali`

have you tried running it from normal user account?

With `yay -S sirikali` it gives me that PGP key import error.

**Comment by shuvashish76** [comment]
I simply installed the binary https://aur.archlinux.org/packages/sirikali-bin version by _unofficial_ version by [Clifton](https://aur.archlinux.org/account/cmulk). It works well.

**Comment by shuvashish76** [comment]
I simply installed the binary https://aur.archlinux.org/packages/sirikali-bin _unofficial_ version by [Clifton](https://aur.archlinux.org/account/cmulk). It works well ;)

**Comment by mhogomchungu** [comment]
HI and sorry for a late reply, try to run below command first and see if the build succeeds.

```
gpg --keyserver hkps://pgp.surf.nl  --recv-keys 16E2E1ACC6F51242
```

**Comment by shuvashish76** [comment]
Thanks, yes now it should work fine for users.
Would be nice if it could do that automatically without such extra step.
In my case it showed
```
error: failed to commit transaction (conflicting files)
sirikali-debug: /usr/lib/debug/usr/bin/sirikali.debug exists in filesystem (owned by sirikali-bin-debug)
sirikali-debug: /usr/lib/debug/usr/bin/sirikali.pkexec.debug exists in filesystem (owned by sirikali-bin-debug)
Errors occurred, no packages were upgraded.
```
Removed that but again

```
error: failed to commit transaction (conflicting files)
sirikali-debug: /usr/lib/debug/usr/bin/sirikali.pkexec.debug exists in filesystem (owned by sirikali-bin-debug)
Errors occurred, no packages were upgraded.
```
I removed that as well. Now build succeeds and works fine.

**Comment by shuvashish76** [comment]
<details><summary>Details</summary>
<p>

 ```
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    SiriKali-1.7.0.tar.xz ... Passed
    SiriKali-1.7.0.tar.xz.asc ... Skipped
:: (1/1) Parsing SRCINFO: sirikali
gpg: error reading key: No public key

 :: PGP keys need importing:
 -> 6855E493B5B2DF96E319BB6D16E2E1ACC6F51242, required by: sirikali
:: Import? [Y/n] 
:: Importing keys with gpg...
gpg: key 16E2E1ACC6F51242: public key "Francis Banyikwa (A key for signing packages) <banyikwafb@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
resolving dependencies...
looking for conflicting packages...

Package (2)         New Version  Net Change  Download Size

core/cracklib       2.10.2-1       0.90 MiB       0.27 MiB
extra/libpwquality  1.4.5-5        0.43 MiB       0.09 MiB

Total Download Size:   0.36 MiB
Total Installed Size:  1.33 MiB

:: Proceed with installation? [Y/n] 
```

</p>
</details>

Thanks now it asks for importing. Also the build succeeds.

Noticed that after the 1st application launch it auto-downloads `securefs` and `gocryptfs`.
I don't use them, how do I remove them?

**Comment by shuvashish76** [comment]
I understand with bundled with SiriKali, users can now update them directly from it but IMO making these filesystem packages **opt-in** during the 1st launch and only then install with user preference would have been better. That way you could give **all** the filesystem options (not just specific ones) as checkbox.
If missed, users can still re-add them from `Menu > Check for updates > Version info`. (Update only possible if installed through SiriKali)

**Comment by mhogomchungu** [comment]
You are using SiriKali what what backend?

**Comment by shuvashish76** [comment]
backend = the `filesystem`? I'm using `cryfs`.

**Comment by mhogomchungu** [comment]
Version 1.7.1 is released and the feature is now opt in and can be enabled through menu->settings->manage securefs and gocryptfs.

https://github.com/mhogomchungu/sirikali/releases/tag/1.7.1

**Comment by shuvashish76** [comment]
Now when I update it gives me this error

```
/home/my_name/.cache/yay/sirikali/PKGBUILD: line 27: unexpected EOF while looking for matching `''
==> ERROR: Failed to source /home/my_name/.cache/yay/sirikali/PKGBUILD
 -> error making: sirikali-exit status 6
 -> Failed to install the following packages. Manual intervention is required:
sirikali - exit status 6
```

**Comment by mhogomchungu** [comment]
Fixed.

**Comment by shuvashish76** [comment]
Thanks. But we do need a release tag on GitHub?

```
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/mhogomchungu/sirikali/releases/download/1.7.2/SiriKali-1.7.2.tar.xz
    Aborting...
```

**Comment by mhogomchungu** [comment]
:-(

Fixed.

**Comment by shuvashish76** [comment]
> Version 1.7.1 is released and the feature is now opt in and can be enabled through menu->settings->manage securefs and gocryptfs.

What does it do? If I enable that option it will download them but importantly if I re-disable it it'll remove them from [that location](https://github.com/mhogomchungu/sirikali/issues/274#issuecomment-2466586723) correct?

**Comment by mhogomchungu** [comment]
1. Enable the option, restart the app and they will be downloaded on start up.
2. Disable the option and they will get deleted immediately.
3. If the option is set, its possible to update them through the "check for updates" feature.
4. They should be at the same location. Set the option, restart to force them to be updated,press CTRL+D to bring up debug window, use one of them and the debug window will show you the full path of where the program is called from.

**Comment by shuvashish76** [comment]
Thanks for the detailed info.
> 2. Disable the option and they will get deleted immediately.

Yes it does but I see them under "Create volume" options. Not that concerning it gets removed after re-lauch. Would be nice if it could remove the visual option immediately. It's more about experience than bug.

Ofc the debug window throws this errors
<details><summary>Details</summary>
<p>

```
*************************************
An attempt to get version info for backend "Securefs" has failed, retrying...
*************************************
*************************************
Failed to get version info for backend "Securefs".
*************************************
*************************************
Securefs backend has an invalid version string (0.0.0)
*************************************
```

</p>
</details>

**Comment by shuvashish76** [comment]
Sorry for asking too many unrelated topic question. Next time I'll create separate issues if I experience any issue. Maybe enable the discussion page as well.
Closing...ThankYou

**Comment by mhogomchungu** [comment]
>Yes it does but I see them under "Create volume" options. 

This is intentional.

At start up, the app detects that these programs are not present but the app can download them and the option to download them is set so it shows them as if they are present because they are about to be installed. The "lie" that shows they are present will be revealed only if the app fails to download them for whatever reason.

Doing it the right way will require more time than what i have at the moment buts its on my todo list.

**Comment by shuvashish76** [comment]
Thanks for this awesome tool, I.ve share with [itsfoss](https://news.itsfoss.com) team, hopefully they'll review in future.

**Comment by shuvashish76** [comment]
> At start up, the app detects that these programs are not present but the app can download them and the option to download them is set so it shows them as if they are present because they are about to be installed.

Personally I'd prefer the program to be never ever connecting to internet at all but I can see update checker, inbuilt _filesystem_ update option can come handy to some people :D

BTW the update checker runs everytime you launch or only when you open "Menu > Check for updates > Version info" tab? I'd prefer to be opt-in i.e. disabled by default because updating softwares is the job of appstores or should be managed by user himself.

**Comment by mhogomchungu** [comment]
The downloading feature was requested [here](https://github.com/mhogomchungu/sirikali/issues/261).

Network requests to check for updates are done by the "version info" window when it is activated and it gets activated under only two circumstances:-

1. When the user click "menu->check for updates".
2. When the app notices a program that can be downloaded is missing and the option to manage the program is set.

If you do not see the "version info" window then rest assured no network requests are taking place.
