### ISSUE TITLE
Flatpak aarch64 version missing Gocryptfs support

### ISSUE THREAD

**Issue by cadecomposer** [mhogomchungu/sirikali#276]
Hi, thank you so much for making a Flatpak build of this app, it is very appreciated. Everything works great on my x86_64 PC, however I noticed on my ARM tablet, I tried to open up my Gocryptfs volume in SiriKali and was unsuccessful with a message that says, "Failed to complete the request. Gocryptfs executable could not be found." I do have the gocryptfs executable from my distro's package manager, and was able to mount the volume in terminal that way, but this is a Flatpak so of course it wouldn't see that.

I would have used a native package version of SiriKali, but the distro I'm using is based on Alpine (Postmarket OS), so it's unavailable in the repo. For me it seems that using the Flatpak is the easiest way to get this running on here. I'm just wondering if there's a way that I can point the Flatpak version of SiriKali to the Gocryptfs executable? Or if Gocryptfs support could possibly be included with the aarch64 build, like it is for the x86_64 build. Thanks again

![Screenshot_20241001_163637](https://github.com/user-attachments/assets/6a9398ef-eb2e-4bec-a7e1-2aac386ed08f)
![Screenshot_20241001_163819](https://github.com/user-attachments/assets/f41a7bfe-f526-448f-b41d-42fe8c6d785e)

**Comment by mhogomchungu** [comment]
1. Close SiriKali.
2. Put your Gocryptfs executable in ```~/.var/app/io.github.mhogomchungu.sirikali/data/SiriKali/bin```
3. Start SiriKali and your Gocryptfs executable should now be usable from within SiriKali.

**Comment by cadecomposer** [comment]
Yup that works. Thanks

**Comment by mhogomchungu** [comment]
Gocryptfs is now bundled with aarch64.
