### ISSUE TITLE
Create Volume button doesn't work anymore (nixos)

### ISSUE THREAD

**Issue by linuxissuper** [mhogomchungu/sirikali#279]
I'm testing the update from `1.6.0` to `1.7.0` on nixos and the `Create Volume` button doesn't seem to work anymore  
  
`1.6.0`  
![image](https://github.com/user-attachments/assets/155e53c9-ec3f-4d36-9f9e-8569c922d03a)
  
  
`1.7.0`  
![image](https://github.com/user-attachments/assets/c8dc1685-7baf-4967-b6fa-4fcd814899e7)
nothing happens when clicked
  
  
am I missing something?

**Comment by mhogomchungu** [comment]
There should be no difference as far as this feature is concerned.

1. What is in PATH environmental variable.
2. What programs do you expect to show up on the list and where are they located in your system.
3. Your system uses what architecture(x86,x86_64 or something else)

**Comment by mhogomchungu** [comment]
Found the problem and is caused by your system not having "bsdtar" executable. 

Will make a new release soon and the fix will be there.

**Comment by linuxissuper** [comment]
thank you :)

**Comment by mhogomchungu** [comment]
New version is out and it should have a fix for this problem

https://github.com/mhogomchungu/sirikali/releases/tag/1.7.1
