### ISSUE TITLE
Upgrade processing improvement

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#28]
When upgrading e.g. cryfs, it asks, on mount, if you would like to upgrade the backing files to the new version. Sirikali reports this as a 'failure', with no indication that it can be fixed by running cryfs standalone.

**Comment by mhogomchungu** [comment]
cryfs will have to first support auto updating its volumes before SiriKali can do anything about this. cryfs will support it in the future and i am waiting for it to show up there before i can do anything in SiriKali.

There is already a discussion about this in cryfs bug tracker[1].

[1] https://github.com/cryfs/cryfs/issues/130

**Comment by mhogomchungu** [comment]
What version of SiriKali did you notice this behavior?

The latest released version should display cryfs outputs giving the user of SiriKali the same information they would get if they had run cryfs directly.

This feature was added in version 1.2.5: https://github.com/mhogomchungu/sirikali/releases/tag/1.2.5

**Comment by mhogomchungu** [comment]
This bug report has a picture that shows backend output when SiriKali fails to make sense of the backend error message: https://github.com/mhogomchungu/sirikali/issues/19

**Comment by davesteele** [comment]
*What version of SiriKali did you notice this behavior?*

I upgraded [both](https://buildd.debian.org/status/package.php?p=sirikali) yesterday, but this was from v1.2.3. 

The message shown in #19 is adequate. Closing.

**Comment by mhogomchungu** [comment]
The next version of Sirikali(1.2.8) will show below error message.

![screenshot_20170601_155145](https://cloud.githubusercontent.com/assets/3496115/26680932/ea3c4af8-46e3-11e7-97e9-f83624831400.png)

**Comment by davesteele** [comment]
Looks good.

**Comment by mhogomchungu** [comment]
git version of SiriKali can now offers an option to upgrade cryfs volume,

https://github.com/cryfs/cryfs/issues/153#issuecomment-362324867
