### ISSUE TITLE
Not letting me enter password for SSHFS Windows

### ISSUE THREAD

**Issue by StellarFr0st** [mhogomchungu/sirikali#282]
So I have attempted multiple times to do this but it just will not let me enter a password. When I create the SSHFS it gets added to my favourites, nothing special there. However when I attempt to mount this, it asks me for a password, fair enough because the user is passworded, but it just **WILL NOT** let me enter a password in the field? I have attempted to recreate this, it does the exact same thing, I'm using the latest SSHFS Windows and the latest SiriKali

https://github.com/user-attachments/assets/5a9719d5-632b-41b6-be5c-8e36772b78e6

**Comment by mhogomchungu** [comment]
1. Go to "menu->favorites" and click "manage favorites".
2. Go to "favorites list" tab on the window generated.
3. Right click the end on the list and then select "edit".
4. The option "volume does not use a password" is checked or not? The option should be unchecked if you are using a password.

**Comment by StellarFr0st** [comment]
> 1. Go to "menu->favorites" and click "manage favorites".
> 2. Go to "favorites list" tab on the window generated.
> 3. Right click the end on the list and then select "edit".
> 4. The option "volume does not use a password" is checked or not? The option should be unchecked if you are using a password.

This worked, but now it is saying that my SSHFS version is too low? It says use at least version 3.5.2 and I am using 3.7.2?

**Comment by StellarFr0st** [comment]
I did downgrade to 3.5.2 but it still doesn't work

**Comment by StellarFr0st** [comment]
@mhogomchungu Any ideas?

**Comment by mhogomchungu** [comment]
Use these builds because they have a solution for the problem you are facing.


https://github.com/mhogomchungu/sirikali/releases/tag/1.5.2

**Comment by StellarFr0st** [comment]
> Use these builds because they have a solution for the problem you are facing.
> 
> https://github.com/mhogomchungu/sirikali/releases/tag/1.5.2

@mhogomchungu This worked, thank you.
