### ISSUE TITLE
Shutdown prevented in Linux

### ISSUE THREAD

**Issue by Satlinker** [mhogomchungu/sirikali#284]
Kubuntu 24.10., Qt 6.6.2, Plasma 6.1.5, Sirikali 1.6
Hi, Sirikali does not shutdown when the system is switched off. Even when no volume is mounted you have to shutdown twice before sirikali closes. Ubuntu sometimes freezes and is no longer operable.
Maybe a shutdown window with "unmount all" would help?

**Comment by mhogomchungu** [comment]
Fixed.

https://github.com/mhogomchungu/sirikali/commit/aee4cdf9793541b64ad59c7365cf6b72928b9f51
