### ISSUE TITLE
OSX: support auto monitoring of mount events

### ISSUE THREAD

**Issue by mhogomchungu** [mhogomchungu/sirikali#29]
Currently,SiriKali does not support auto monitoring of mount events on OSX and this prevents it from updating its GUI when backends unmount their volumes when inactivity time out is reached. It also prevents SiriKali from auto mounting a favorite list entry when it becomes available.

This is still experimental feature and would appreciate if somebody could test it for me.

The option to enable this feature is set at build time with a cmake option of  "-DOSX_AUTOMONITOR=true". 

A full cmake argument list may look like:
``` cmake -DCMAKE_INSTALL_PREFIX=$HOME/sirikali -DQT5=true -DOSX_AUTOMONITOR=true  -DCMAKE_BUILD_TYPE=RELEASE . ..```

Once the project is build,just run it and try to unlock a volume and then lock it and see if the volume will be added and removed from the GUI respectively.

**Comment by larsnystrom** [comment]
It seems like this works. I just built 6980400821343399c790b4327c6a83ae54be48c9 and compiled it with the cmake arguments you wrote above. If I mount a drive in SiriKali and then unmount it by right clicking it on my desktop and choosing "Unmount", SiriKali updates accordingly (i.e. the drive is no longer visible in the GUI). 

So this LGTM 👍

**Comment by mhogomchungu** [comment]
Thank you,can you try again.

Update from the latest git and report your finding. The old way is now completely gone and hence there is no longer a need to use "-DOSX_AUTOMONITOR=true" cmake option.

The cmake options should be the default of something like 

```
cmake -DCMAKE_INSTALL_PREFIX=$HOME/sirikali -DCMAKE_BUILD_TYPE=RELEASE . ..
```

I will close this bug report afterwards.

**Comment by mhogomchungu** [comment]
I am closing this one since i think the new code has no issue but would appreciate if you could still test and respond if see any difference in how the GUI respond when mounting/unmounting volumes

**Comment by larsnystrom** [comment]
Sorry for not answering. It works perfectly 👍
