### ISSUE TITLE
Stop being brew-exclusive on OS X

### ISSUE THREAD

**Issue by mouse07410** [mhogomchungu/sirikali#32]
Your current `OSX_BUILD_INSTRUCTIONS` makes it appear as if you can only build SiriKali if you install brew. That's plain wrong. 

Instead it should say what packages are required, and that they may be installed via brew, Macports, or manually - and SiriKali needs to be informed of the location where those packages are.

For example, I successfully built and ran the current SiriKali using Macports-installed packages.

**Comment by mhogomchungu** [comment]
A pull request with your improvements will be appreciated. I know nothing about OSX and all the support and documentation comes from OSX users like yourself.

**Comment by mouse07410** [comment]
> A pull request with your improvements will be appreciated.

OK, that's fair. Stand by.

**Comment by mhogomchungu** [comment]
You can also post your modifications here or send them to me through my email address.

Sending pull requests is a bit involving process and it may take too much of your time if you havent done it before.

**Comment by mhogomchungu** [comment]
Closing this one for lack of activity, reopen when you are ready to resume.
