### ISSUE TITLE
add ~/bin/ to directories checked for backend executables

### ISSUE THREAD

**Issue by uhausbrand** [mhogomchungu/sirikali#35]
As the quickstart introduction of gocryptfs mentions copying the binary to ~/bin/ (see 
https://nuetzlich.net/gocryptfs/quickstart/ ), it would be nice if the user didn't need to add a softlink into the currently checked directories.

**Comment by mhogomchungu** [comment]
done[1]

[1] https://github.com/mhogomchungu/sirikali/commit/90ddfa8af8383c74600f1f5e37e26589f529679c

**Comment by mhogomchungu** [comment]
The git version now includes also ```~/.bin``` path for those who want executable path in their home folder but do not want to keep seeing this folder.

**Comment by mhogomchungu** [comment]
New version of SiriKali with a requested feature is out: https://github.com/mhogomchungu/sirikali/releases/tag/1.3.0
