### ISSUE TITLE
SiriKali hangs when selecting Key+Keyfile in macOS

### ISSUE THREAD

**Issue by eugenesvk** [mhogomchungu/sirikali#36]
When I select the **Key+Keyfile** option in Sirikali 1.3.0 (macOS 10.12.6) when trying to create a container it just hangs as though it can't open the file selection dialogue (although it works fine for **HMAC+Keyfile**) and I have to `Force quit` it.
<img width="861" alt="sirikali key keyfile" src="https://user-images.githubusercontent.com/12956286/29829947-7022d48e-8ce9-11e7-8035-c18a02020632.png">

**Comment by mhogomchungu** [comment]
Below image shows a window that seems to be unable to show up in OSX. Will try to move code around to see if it helps. Qt in OSX seems to not like local event loops very much and all the hangs and crashes that have been reported on OSX involves them. I am guessing this[1] local event loop is the one that is causing the hanging.

[1] https://github.com/mhogomchungu/sirikali/blob/1412c5b5bc66a1ff7e7c09a0d3e15a059a274f53/src/utility.cpp#L815

![screenshot_20170829_185510](https://user-images.githubusercontent.com/3496115/29830700-a64d0faa-8ceb-11e7-883b-9b9f82550293.png)

**Comment by mhogomchungu** [comment]
I think the latest git version fixed reported problem. Will appreciate if you can confirm the problem is fixed or if its still present.

**Comment by eugenesvk** [comment]
Yes, it's working now, thanks for a quick fix!
The only problem is that this window gets hidden behind the main window once I select keyfile. I can still access it, but I have to move the main window out of the way or, even better, alt-tab to another app and back, then it jumps back to the foreground

**Comment by mhogomchungu** [comment]
Update from git again and see if the window still goes behing the main window.

**Comment by eugenesvk** [comment]
It's better, but now if I cancel the window with Escape, the app hangs (cancelling via the `cancel` button seems to be working fine)
However, now the app crashes consistently after mounting (see e.g. https://gist.github.com/eugenesvk/b4c46249d1aaecadb1c6d8adb8f1ee01), though the mounting operation seems to be successful

**Comment by mhogomchungu** [comment]
update from git and try again. The crashing should now be gone since i went back to previous code that worked and the hanging should now be gone since the password window is now reused and this avoids creating an a third window which is proving to be very problematic on OSX.

**Comment by eugenesvk** [comment]
Thanks, it's working better now, although the buttons aren't aligned properly 
<img width="217" alt="sirikali key" src="https://user-images.githubusercontent.com/12956286/29899706-b46a5d44-8df5-11e7-9749-0810ffdc8640.png">

I still had the app hang a couple of times when mounting a drive (though the drive got mounted) and one crash, but that might be related to something else

**Comment by mhogomchungu** [comment]
update from git and try again. The "OK" between those two buttons should no longer show and the crashes hopefully are also gone.

**Comment by mhogomchungu** [comment]
Can you update from git and check if you still get those hangs when you mount a volume.

**Comment by eugenesvk** [comment]
So far so good, no hangs/crashes on mounting/unmounting. Thanks for prompt response!
