### ISSUE TITLE
No list of mounted volumes on macOS

### ISSUE THREAD

**Issue by eugenesvk** [mhogomchungu/sirikali#37]
After creating/mounting a volume, Sirikali does open it, however, it doesn't show anything in the list and hence can't unmount any volumes (I have to unmount via Finder)

<img width="861" alt="sirikali list" src="https://user-images.githubusercontent.com/12956286/29831554-313d3db8-8cee-11e7-9ae2-80efaf905403.png">

Even though a volume is mounted (in the default ~/.SiriKali/VolumeName path)
<img width="117" alt="sirikali mount" src="https://user-images.githubusercontent.com/12956286/29831555-3156538e-8cee-11e7-83e2-270f01c2b750.png">

**Comment by mhogomchungu** [comment]
I think i fixed this bug 3 days ago here[1]. I think this is a gocryptfs bug but i did not look too closely into it. Update from git(do you know how to do this) and see if the problem is still there.

[1] https://github.com/mhogomchungu/sirikali/commit/d6033913ef5e51eb0f77c5b210b439265b8dc9ce

**Comment by mhogomchungu** [comment]
It looks like this was a documented change in gocryptfs 1.3. The relevant changelog says

```
Passing "--" now also blocks "-o" parsing
```

**Comment by eugenesvk** [comment]
Yep, building from git (you have good building instructions, so it's just a matter of a few copy&paste commands; though an even better option would be to have a Homebrew formula!) fixes it, thanks!

**Comment by mhogomchungu** [comment]
Just made a new release of SiriKali and i recommend you update to it.

**Comment by eugenesvk** [comment]
Thanks, updated
