### ISSUE TITLE
macOS: App hanging if two volumes auto-mounted with ShowMountDialogue on

### ISSUE THREAD

**Issue by eugenesvk** [mhogomchungu/sirikali#39]
It seems that Sirikali is trying to open two windows at the same time and just hangs instead of mounting one drive, waiting for user input for the first window then proceeding to mount the second volume and show the second window.
I had to manually disable it in the preferences file to be able to launch the app again.

**Comment by mhogomchungu** [comment]
Can you add steps you took to get two windows to show up at the same time.

**Comment by eugenesvk** [comment]
I didn't get two windows, that's just my guess as to what's happening. I only see one window, but I can't interact with it. When I auto-mount two drives without this ShowMountDialogue option, it's working fine. When I auto-mount just **one** drive with this option enabled,  I get a window that I can interact with

**Comment by mhogomchungu** [comment]
Update from git and try again. You will see a single password dialog prompt and it will be reused for all volume you attempt to unlock.

Previous,each volume generated its own password dialog prompt.

**Comment by eugenesvk** [comment]
Thanks, that seems to be fixed!
