### ISSUE TITLE
Create Filesystem with Specified Configuration File

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/sirikali#4]
When creating a file system and clicking on "options", the dialog only allows choosing existing files as a configuration file. However, I'm trying to create a file system, so the configuration file doesn't exist yet and would be created with the file system.

**Comment by mhogomchungu** [comment]
The GUI is a bit confusing here when creating a new volume but it works. 

Just type the name of the config file on the text field and the config file will be created in your home directory.Adding a full pathed config file will cause the config file to be created where you specified it

**Comment by smessmer** [comment]
I was talking about the dialog where you choose a file from your operating system if you don't want to type the file path by hand. It only allows you to choose existing files, but should also allow creating new files.

**Comment by mhogomchungu** [comment]
current git version disables the file chooser dialog when creating a volume as it does not make sense wanting to select a file that does not exist.

I am open to suggestions on the best way to do this since i see no way a user can set a file name/file path without manually typing them.

**Comment by smessmer** [comment]
You can use the Qt Dialog for saving files (used by applications when you choose "File -> Save").

Btw thank you very much for all the fixes of the other issues. I'll compile and test it tomorrow.

**Comment by mhogomchungu** [comment]
git version now has the behavior you expect.

**Comment by smessmer** [comment]
Confirmed - works now.
