### ISSUE TITLE
Ubuntu reports a Wayland issue

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#41]
Bug #[1713313](https://bugs.launchpad.net/ubuntu/+source/sirikali/+bug/1713313), "Unable to launch pkexec'ed applications on Wayland session".

**Comment by mhogomchungu** [comment]
I already commented on this bug here[1]

[1] https://bugs.launchpad.net/ubuntu/+source/sirikali/+bug/1713313/comments/24
