### ISSUE TITLE
How to add options to fuse

### ISSUE THREAD

**Issue by grangerp** [mhogomchungu/sirikali#45]
Not sure if it is the right place ti ask question.
I want to mount a volume with gocryptfs and add option to fuse -o allow_other, on command line I use:
```bash
gocryptfs -allow_other dir1 dir2
```
But I did not find how to di it with the gui, look like configuration file dialog should be the way but I did not find any documentatios on the config file format.

Thanks

**Comment by mhogomchungu** [comment]
Your question was asked and answered here[1].

I am closing this ticket but feel free to ask if explanations in that ticked were not sufficient.

[1] https://github.com/mhogomchungu/sirikali/issues/27
