### ISSUE TITLE
Add pre-unmount command

### ISSUE THREAD

**Issue by theit8514** [mhogomchungu/sirikali#46]
Most of the time when using SiriKali and XFCE, I run into an issue where SiriKali is unable to unmount the mounted volume because of a lingering process (the background thumbnailer 'tumblerd') attached to the mount. Would it be possible to add a customizable pre-unmount command that is executed prior to unmounting the volume?

E.g. fuser -m -k $PATH_TO_VOLUME

**Comment by mhogomchungu** [comment]
Latest git version has the option.

After you have updated from git version.. Open the config file located probably at 
```"~/.config/SiriKali/SiriKali.conf``` and then add a line
```PreUnMountCommand=fuser -m -k```

That command will be executed after a path to a volume is appended to it and an attempt to unmount the volume will be carried out only when the command specified returned 0.

Will appreciate if you could confirm that it works. Will add a GUI way to add the option at some point in the future.

**Comment by theit8514** [comment]
I understand the concerns on the unsaved document front but I prefer being able to immediately unmount. I'll probably switch to -HUP just in case.

After updating, I have no issues with executing fuser directly, but since that returns 1 if there are no open files/processes, it never unmounts the volume. I tried switching to a simple bash script but the script wouldn't execute until I added the #!/bin/bash to the header. Not sure if that's something on your side but I've never had that issue before.

```
#!/bin/bash

fuser -m -k -HUP $1
sleep 1
exit 0
```

Thanks!

**Comment by mhogomchungu** [comment]
The code that runs your script is here[1]. Its all Qt code and i do not do anything "personally".

I am glad to feature works for you and good luck!!!

[1] https://github.com/mhogomchungu/sirikali/blob/bca6cc666e6aee989e8498d49c6f5115eb468195/src/utility.cpp#L226-L261

**Comment by mhogomchungu** [comment]
The git version has a GUI way to set this option.

![screenshot_20171107_075117](https://user-images.githubusercontent.com/3496115/32477637-c9646ed0-c390-11e7-8421-7ab701e96a6e.png)
