### ISSUE TITLE
Problems with leftover backing directory

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#47]
If there is a problem during a session, the backing dir in ~/.Sirikali may remain. On subsequent mounts, !/.Sirikali/<dir> (2) is created and used. In this situation, the "Open Folder" operation does not work.

**Comment by mhogomchungu** [comment]
I can not reproduce this, you are seeing this behavior in what version of SiriKali.

**Comment by davesteele** [comment]
All, up to 1.3.1.

**Comment by davesteele** [comment]
Neither can I, reliably. I'll leave this here and expand if it happens again.

**Comment by davesteele** [comment]
Best I can figure, this is actually a different thing. If the directory is already open in a File window on the desktop, another isn't opened, and it isn't brought to the front. So, not a Sirikali bug, though it would be convenient if the window were promoted somehow.
