### ISSUE TITLE
Disable wallets

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#48]
I can't figure out how to get Sirikali to stop asking me about Wallet passwords. I wish to type in the passwords. Key Storage -> None does not do it.

**Comment by mhogomchungu** [comment]
1. You are asked for a password for what backend?
2, What version of SiriKali are you using that has this problem.
3. Can you give steps you take that shows this problem.
4. Do you have your volumes set to auto mount at start up/when volume become available?

**Comment by mhogomchungu** [comment]
Can you post the contents of the config file? It should be at "~/.config/SiriKali/SiriKali.conf"

Careful,the "favoritesVolumes" entry may contain personal information.

**Comment by mhogomchungu** [comment]
I think the steps to disable it is through "menu->automount favorites->auto mount key source->none"

Yes,its time to have a proper window to manage all these configuration options!

**Comment by davesteele** [comment]
In not home right now.

Latest version, on Debian sid.

It's a favorite, but not auto mounted. That is, I have to trigger the mount.

**Comment by mhogomchungu** [comment]
Ok, the above steps should clear the problem. Those steps are also documented in the FAQ[1].

[1] https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#60-how-do-i-unlock-a-volume-through-a-favorite-entry-without-invoking-a-wallet

**Comment by davesteele** [comment]
A little obscure, but it works.

**Comment by mhogomchungu** [comment]
While here, this[1] bug should be closed as "invalid".

[1] https://launchpad.net/ubuntu/+source/sirikali/+bugs?search=Search&field.status=New

**Comment by mhogomchungu** [comment]
I have just added a GUI window to manage options and an image of the relevant GUI part for this thread is below:

![screenshot_20171107_014828](https://user-images.githubusercontent.com/3496115/32468146-2412f7e4-c35e-11e7-81f4-1fc2a8ac9116.png)

**Comment by davesteele** [comment]
Looks good.
