### ISSUE TITLE
Mount Options Dialog forgets values

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/sirikali#5]
When I set mount options (e.g. a config file or a number of minutes after which to auto-unmount the filesystem), then close the Mount Options Dialog and open it again, the setting fields are empty again.

**Comment by mhogomchungu** [comment]
I think there are privacy issues with remembering the path to the last used config file.

**Comment by smessmer** [comment]
It's ok when the fields are cleared after closing the mount dialog (i.e. finishing or cancelling the mount operation). What I'm talking about is that the values are lost when I reopen the mount options dialog from the same mount dialog, without closing the mount dialog.

**Comment by mhogomchungu** [comment]
current git version has corrections for the problem you identified here.

It is now possible to save these mount options with a favorite volume.

**Comment by smessmer** [comment]
fixed. Thanks.
