### ISSUE TITLE
Error on OSX when making

### ISSUE THREAD

**Issue by kys86468** [mhogomchungu/sirikali#50]
make -j$(sysctl -n hw.ncpu)

[  2%] Linking C static library libsecretlib.a
[  2%] Linking C static library liblxqt-wallet-backend.a
[  4%] Built target secretlib
[  4%] Built target lxqt-wallet-backend
Scanning dependencies of target lxqt-wallet
[  6%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/lxqt_osx_keychain.cpp.o
[  6%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/lxqt_wallet.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[  7%] Linking CXX static library liblxqt-wallet.a
[ 18%] Built target lxqt-wallet
[ 18%] Generating src/moc_checkforupdates.cpp
[ 20%] Generating src/moc_sirikali.cpp
[ 20%] Generating src/moc_configoptions.cpp
[ 21%] Generating src/3rdParty/tasks/moc_task.cpp
[ 22%] Generating ui_help.h
Scanning dependencies of target sirikali
[ 23%] Building CXX object CMakeFiles/sirikali.dir/src/moc_configoptions.cpp.o
[ 23%] Building CXX object CMakeFiles/sirikali.dir/src/moc_keydialog.cpp.o
[ 24%] Building CXX object CMakeFiles/sirikali.dir/src/moc_checkforupdates.cpp.o
[ 25%] Building CXX object CMakeFiles/sirikali.dir/src/moc_sirikali.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
In file included from /Users/admin/Downloads/sirikali/build/src/moc_configoptions.cpp:9:
In file included from /Users/admin/Downloads/sirikali/build/src/../../src/configoptions.h:23:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/QDialog:1:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qdialog.h:43:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h:43:
In file included from /usr/local/opt/qt5/lib/QtGui.framework/Headers/qtguiglobal.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:45:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4007:19: error: invalid application of 'sizeof' to an incomplete type 'void'
    static_assert(sizeof(_Tp) > 0, "Type must be complete.");
                  ^~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4305:15: note: in instantiation of template class 'std::__1::__check_complete<void>' requested
      here
    : private __check_complete<_Fp>
              ^....................

**Comment by mhogomchungu** [comment]
Can you post the output of cmake command.

I dont think there is much i can do here since the crush seems to happen within Qt

**Comment by kys86468** [comment]
cmake -DCMAKE_INSTALL_PREFIX=$HOME/sirikali -DQT5=true -DCMAKE_BUILD_TYPE=RELEASE . ..
-- Checking for module 'pwquality'
--   No package 'pwquality' found
-- found json.hpp header file at: /Users/admin/Downloads/sirikali/src/3rdParty/json/nlohmann/json.hpp
-- found gcrypt header file at: /usr/local/include/gcrypt.h
-- found gcrypt library at: /usr/local/lib/libgcrypt.dylib
-- adding library search path of: /usr/local/lib
-- Checking for module 'lxqt-wallet'
--   No package 'lxqt-wallet' found
-- ERROR: could not find lxqt_wallet package
-- ---------------------------------------------------------------------------
-- lxqt wallet support will be provided by an internal library
-- ---------------------------------------------------------------------------
-- found gcrypt header file: /usr/local/include/gcrypt.h
-- found gcrypt library: /usr/local/lib/libgcrypt.dylib
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.18.5
--
--------------------------------------------------------------------------
-- kwallet support NOT found,will not build kwallet functionality
-- -----------------------------------------------------------------------
--
--------------------------------------------------------------------------
-- libsecret support found,will build libsecret functionality
-- -----------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- Building GUI components using Qt5
-- ---------------------------------------------------------------------------


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/admin/Downloads/sirikali/build

**Comment by mhogomchungu** [comment]
You should have run the cmake command on a "clean" build folder to force it to print everything, I was most interested on the version of clang you are using but that info is not listed in your output because you ran cmake on an already configured folder.

**Comment by kys86468** [comment]
cmake -DCMAKE_INSTALL_PREFIX=$HOME/sirikali -DQT5=true -DCMAKE_BUILD_TYPE=RELEASE . ..
-- The C compiler identification is AppleClang 9.0.0.9000038
-- The CXX compiler identification is AppleClang 9.0.0.9000038
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'pwquality'
--   No package 'pwquality' found
-- found json.hpp header file at: /Users/admin/Downloads/sirikali/src/3rdParty/json/nlohmann/json.hpp
-- found gcrypt header file at: /usr/local/include/gcrypt.h
-- found gcrypt library at: /usr/local/lib/libgcrypt.dylib
-- adding library search path of: /usr/local/lib
-- Checking for module 'lxqt-wallet'
--   No package 'lxqt-wallet' found
-- ERROR: could not find lxqt_wallet package
-- ---------------------------------------------------------------------------
-- lxqt wallet support will be provided by an internal library
-- ---------------------------------------------------------------------------
-- found gcrypt header file: /usr/local/include/gcrypt.h
-- found gcrypt library: /usr/local/lib/libgcrypt.dylib
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.18.5
--
--------------------------------------------------------------------------
-- kwallet support NOT found,will not build kwallet functionality
-- -----------------------------------------------------------------------
--
--------------------------------------------------------------------------
-- libsecret support found,will build libsecret functionality
-- -----------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- Building GUI components using Qt5
-- ---------------------------------------------------------------------------


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/admin/Downloads/sirikali/build
MacBook-Pro:build admin$ make -j$(sysctl -n hw.ncpu)
Scanning dependencies of target lxqt-wallet-backend
Scanning dependencies of target secretlib
[  1%] Building C object src/3rdParty/lxqt_wallet/backend/CMakeFiles/lxqt-wallet-backend.dir/lxqtwallet.c.o
clang: [  2%] Building C object src/3rdParty/lxqt_wallet/frontend/libsecret/CMakeFiles/secretlib.dir/__/libsecret.c.o
warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[  3%] Linking C static library libsecretlib.a
[  4%] Linking C static library liblxqt-wallet-backend.a
[  4%] Built target secretlib
[  4%] Built target lxqt-wallet-backend
[  5%] Generating ui_password_dialog.h
[  5%] Generating ui_changepassworddialog.h
[  6%] Generating moc_task.cpp
[  7%] Generating moc_changepassworddialog.cpp
[  8%] Generating moc_password_dialog.cpp
Scanning dependencies of target lxqt-wallet
[  9%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/lxqt_osx_keychain.cpp.o
[ 10%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/changepassworddialog.cpp.o
[ 11%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/password_dialog.cpp.o
[ 12%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/lxqt_internal_wallet.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[ 13%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/lxqt_wallet.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[ 14%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/lxqt_libsecret.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[ 15%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/moc_changepassworddialog.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[ 16%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/moc_password_dialog.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[ 17%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/moc_task.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[ 18%] Linking CXX static library liblxqt-wallet.a
[ 18%] Built target lxqt-wallet
[ 19%] Generating src/moc_checkforupdates.cpp
[ 19%] Generating src/moc_configoptions.cpp
[ 20%] Generating qrc_icon.cpp
[ 21%] Generating src/moc_configfileoption.cpp
[ 22%] Generating src/moc_dialogok.cpp
[ 23%] Generating src/moc_help.cpp
[ 24%] Generating src/moc_sirikali.cpp
[ 25%] Generating src/moc_keydialog.cpp
[ 26%] Generating src/moc_oneinstance.cpp
[ 27%] Generating src/moc_dialogmsg.cpp
[ 28%] Generating src/moc_plugin.cpp
[ 29%] Generating src/moc_favorites.cpp
[ 30%] Generating src/moc_readonlywarning.cpp
[ 31%] Generating src/moc_walletconfig.cpp
[ 32%] Generating src/moc_walletconfiginput.cpp
[ 33%] Generating src/moc_options.cpp
[ 34%] Generating src/moc_filemanager.cpp
[ 35%] Generating src/moc_mountinfo.cpp
[ 36%] Generating src/moc_securefscreateoptions.cpp
[ 37%] Generating src/moc_cryfscreateoptions.cpp
[ 38%] Generating src/3rdParty/tasks/moc_task.cpp
[ 39%] Generating src/3rdParty/NetworkAccessManager/moc_networkAccessManager.cpp
[ 40%] Generating ui_sirikali.h
[ 41%] Generating ui_keydialog.h
[ 41%] Generating ui_dialogmsg.h
[ 42%] Generating ui_plugin.h
[ 43%] Generating ui_favorites.h
[ 44%] Generating ui_readonlywarning.h
[ 45%] Generating ui_walletconfig.h
[ 47%] Generating ui_walletconfiginput.h
[ 47%] Generating ui_options.h
[ 48%] Generating ui_dialogok.h
[ 50%] Generating ui_help.h
[ 50%] Generating ui_filemanager.h
[ 51%] Generating ui_securefscreateoptions.h
[ 52%] Generating ui_cryfscreateoptions.h
[ 53%] Generating ui_configfileoption.h
[ 54%] Generating ui_configoptions.h
Scanning dependencies of target sirikali
[ 58%] Building CXX object CMakeFiles/sirikali.dir/src/moc_checkforupdates.cpp.o
[ 58%] Building CXX object CMakeFiles/sirikali.dir/src/moc_dialogok.cpp.o
[ 58%] Building CXX object CMakeFiles/sirikali.dir/src/moc_configfileoption.cpp.o
[ 58%] Building CXX object CMakeFiles/sirikali.dir/src/moc_configoptions.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
[ 59%] Building CXX object CMakeFiles/sirikali.dir/src/moc_help.cpp.o
[ 60%] Building CXX object CMakeFiles/sirikali.dir/src/moc_sirikali.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
In file included from /Users/admin/Downloads/sirikali/build/src/moc_configoptions.cpp:9:
In file included from /Users/admin/Downloads/sirikali/build/src/../../src/configoptions.h:23:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/QDialog:1:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qdialog.h:43:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h:43:
In file included from /usr/local/opt/qt5/lib/QtGui.framework/Headers/qtguiglobal.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:45:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4007:19: error: invalid application of 'sizeof' to an incomplete type 'void'
    static_assert(sizeof(_Tp) > 0, "Type must be complete.");
                  ^~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4305:15: note: in instantiation of template class 'std::__1::__check_complete<void>' requested
      here
    : private __check_complete<_Fp>
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4360:9: note: in instantiation of template class 'std::__1::__invokable_r<void, void>' requested
      here
        __invokable<_Fp, _Args...>::value,
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4369:14: note: in instantiation of template class 'std::__1::__invoke_of<void>' requested here
    : public __invoke_of<_Fp, _Args...>
             ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:605:2: note: in instantiation of template class 'std::__1::result_of<void ()>' requested
      here
        future<typename std::result_of<Fn()>::type>& run( Fn&& function )
        ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:663:24: note: while substituting explicitly-specified template arguments into function
      template 'run'
                _private_add_void( f,Task::run< void >( std::forward<std::function<void()>>( e ) ),
                                     ^
In file included from /Users/admin/Downloads/sirikali/build/src/moc_configoptions.cpp:9:
In file included from /Users/admin/Downloads/sirikali/build/src/../../src/configoptions.h:23:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/QDialog:1:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qdialog.h:43:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h:43:
In file included from /usr/local/opt/qt5/lib/QtGui.framework/Headers/qtguiglobal.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:45:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4308:25: error: cannot pass expression of type 'decltype(std::__1::__declval<void>(0))'
      (aka 'void') to variadic constructor
        _VSTD::__invoke(_VSTD::declval<_Fp>(), _VSTD::declval<_Args>()...));
                        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__config:392:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4360:9: note: in instantiation of template class 'std::__1::__invokable_r<void, void>' requested
      here
        __invokable<_Fp, _Args...>::value,
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4369:14: note: in instantiation of template class 'std::__1::__invoke_of<void>' requested here
    : public __invoke_of<_Fp, _Args...>
             ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:605:2: note: in instantiation of template class 'std::__1::result_of<void ()>' requested
      here
        future<typename std::result_of<Fn()>::type>& run( Fn&& function )
        ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:663:24: note: while substituting explicitly-specified template arguments into function
      template 'run'
                _private_add_void( f,Task::run< void >( std::forward<std::function<void()>>( e ) ),
                                     ^
In file included from /Users/admin/Downloads/sirikali/build/src/moc_checkforupdates.cpp:9:
In file included from /Users/admin/Downloads/sirikali/build/src/../../src/checkforupdates.h:23:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/QFile:1:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qfile.h:44:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qfiledevice.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qiodevice.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:45:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4007:19: error: invalid application of 'sizeof' to an incomplete type 'void'
    static_assert(sizeof(_Tp) > 0, "Type must be complete.");
                  ^~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4305:15: note: in instantiation of template class 'std::__1::__check_complete<void>' requested
      here
    : private __check_complete<_Fp>
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4360:9: note: in instantiation of template class 'std::__1::__invokable_r<void, void>' requested
      here
        __invokable<_Fp, _Args...>::value,
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4369:14: note: in instantiation of template class 'std::__1::__invoke_of<void>' requested here
    : public __invoke_of<_Fp, _Args...>
             ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:605:2: note: in instantiation of template class 'std::__1::result_of<void ()>' requested
      here
        future<typename std::result_of<Fn()>::type>& run( Fn&& function )
        ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:663:24: note: while substituting explicitly-specified template arguments into function
      template 'run'
                _private_add_void( f,Task::run< void >( std::forward<std::function<void()>>( e ) ),
                                     ^
In file included from /Users/admin/Downloads/sirikali/build/src/moc_checkforupdates.cpp:9:
In file included from /Users/admin/Downloads/sirikali/build/src/../../src/checkforupdates.h:23:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/QFile:1:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qfile.h:44:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qfiledevice.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qiodevice.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:45:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4308:25: error: cannot pass expression of type 'decltype(std::__1::__declval<void>(0))'
      (aka 'void') to variadic constructor
        _VSTD::__invoke(_VSTD::declval<_Fp>(), _VSTD::declval<_Args>()...));
                        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__config:392:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4360:9: note: in instantiation of template class 'std::__1::__invokable_r<void, void>' requested
      here
        __invokable<_Fp, _Args...>::value,
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4369:14: note: in instantiation of template class 'std::__1::__invoke_of<void>' requested here
    : public __invoke_of<_Fp, _Args...>
             ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:605:2: note: in instantiation of template class 'std::__1::result_of<void ()>' requested
      here
        future<typename std::result_of<Fn()>::type>& run( Fn&& function )
        ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:663:24: note: while substituting explicitly-specified template arguments into function
      template 'run'
                _private_add_void( f,Task::run< void >( std::forward<std::function<void()>>( e ) ),
                                     ^
2 errors generated.
make[2]: *** [CMakeFiles/sirikali.dir/src/moc_configoptions.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/admin/Downloads/sirikali/build/src/moc_sirikali.cpp:9:
In file included from /Users/admin/Downloads/sirikali/build/src/../../src/sirikali.h:23:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/QObject:1:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qobject.h:46:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qobjectdefs.h:48:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qnamespace.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:45:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4007:19: error: invalid application of 'sizeof' to an incomplete type 'void'
    static_assert(sizeof(_Tp) > 0, "Type must be complete.");
                  ^~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4305:15: note: in instantiation of template class 'std::__1::__check_complete<void>' requested
      here
    : private __check_complete<_Fp>
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4360:9: note: in instantiation of template class 'std::__1::__invokable_r<void, void>' requested
      here
        __invokable<_Fp, _Args...>::value,
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4369:14: note: in instantiation of template class 'std::__1::__invoke_of<void>' requested here
    : public __invoke_of<_Fp, _Args...>
             ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:605:2: note: in instantiation of template class 'std::__1::result_of<void ()>' requested
      here
        future<typename std::result_of<Fn()>::type>& run( Fn&& function )
        ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:663:24: note: while substituting explicitly-specified template arguments into function
      template 'run'
                _private_add_void( f,Task::run< void >( std::forward<std::function<void()>>( e ) ),
                                     ^
In file included from /Users/admin/Downloads/sirikali/build/src/moc_sirikali.cpp:9:
In file included from /Users/admin/Downloads/sirikali/build/src/../../src/sirikali.h:23:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/QObject:1:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qobject.h:46:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qobjectdefs.h:48:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qnamespace.h:43:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:45:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4308:25: error: cannot pass expression of type 'decltype(std::__1::__declval<void>(0))'
      (aka 'void') to variadic constructor
        _VSTD::__invoke(_VSTD::declval<_Fp>(), _VSTD::declval<_Args>()...));
                        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__config:392:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4360:9: note: in instantiation of template class 'std::__1::__invokable_r<void, void>' requested
      here
        __invokable<_Fp, _Args...>::value,
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:4369:14: note: in instantiation of template class 'std::__1::__invoke_of<void>' requested here
    : public __invoke_of<_Fp, _Args...>
             ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:605:2: note: in instantiation of template class 'std::__1::result_of<void ()>' requested
      here
        future<typename std::result_of<Fn()>::type>& run( Fn&& function )
        ^
/Users/admin/Downloads/sirikali/build/src/../../src/3rdParty/tasks/task.h:663:24: note: while substituting explicitly-specified template arguments into function
      template 'run'
                _private_add_void( f,Task::run< void >( std::forward<std::function<void()>>( e ) ),
                                     ^
2 errors generated.
make[2]: *** [CMakeFiles/sirikali.dir/src/moc_checkforupdates.cpp.o] Error 1
2 errors generated.
make[2]: *** [CMakeFiles/sirikali.dir/src/moc_sirikali.cpp.o] Error 1
make[1]: *** [CMakeFiles/sirikali.dir/all] Error 2
make: *** [all] Error 2

**Comment by mhogomchungu** [comment]
Delete everything,download everything again and try to build again and report if the problem is still there.

The old code compiled fine in gcc 7.2 and clang 3.9 but it failed at the same place it failed on you on clang 5.0.0.

**Comment by kys86468** [comment]
thnx for fix. it works now!
