### ISSUE TITLE
Add Fedora 27 build

### ISSUE THREAD

**Issue by gyaxo** [mhogomchungu/sirikali#52]
Hi,

Can you add a Fedora 27 build to OBS?

Thanks!

**Comment by mhogomchungu** [comment]
Fedora 27 changed something and its failing[1] to build and all my attempts to solve the problem have so far being unsuccessful. 

[1] https://build.opensuse.org/build/home:obs_mhogomchungu/Fedora_27/x86_64/sirikali/_log

**Comment by mhogomchungu** [comment]
Binary packages are posted. Thanks for the tip.
