### ISSUE TITLE
Mount failure.

### ISSUE THREAD

**Issue by Achaean** [mhogomchungu/sirikali#55]
Mount fails with the message:
Failed To Unlock The Volume.
Not supported Volume Encountered.

Sirikali v.1.3.2 from it's repository, at Debian Jessie (oldstable) x64 KDE, with gocryptfs 1.4.2.

**Comment by mhogomchungu** [comment]
You got the error probably because ```gocryptfs.conf``` config file was not found in the cipher folder. Are you sure it is there?

**Comment by Achaean** [comment]
No hint. Never messed with it! :-)
Sirikali - Gocryptfs combination, used to work out of the box, without the need for setting extra options.
I can't find it. Where's the cipher folder?

**Comment by mhogomchungu** [comment]
```Cipher folder``` is the folder that contains your encrypted data,it is also the folder that hosts ```gocryptfs.conf```.

Look at the folder that you are pointing SiriKali to unlock,do you see a file in it called ```gocryptfs.conf````?. I think you are getting the error you are getting because this file is missing for some reason.

Alternatively, try to unlock the folder using gocryptfs manually and report your result.

**Comment by Achaean** [comment]
Oh, I see! :-)
gocryptfs.conf is there. Trying to manually unmounting it (or even logging off or restarting) didn't help.
I continue to receive this message.

I tried also simple ecryptfs. It has even more issues. It can't even encrypt a folder.
Since I didn't have these issues with previous version, I think something broke with the latest one.

**Comment by mhogomchungu** [comment]
The ecryptfs issue should be in its own thread, you are getting that error probably because ```ecryptfs``` module is not loaded or `ecryptfs-tools``` package is not installed.

Open the terminal and run below command to load it:

If you are on Ubuntu,run below command
```
sudo modprobe ecryptfs
```

If you are anywhere else,run below command
```
su -c "modprobe ecryptfs"
```

Back to the original post,the only part in the code that produces the error you are getting here[1] and you will get the error if either the config file is not in the cipher folder or you setup the volume as a favorite and you gave it a wrong a config file path.

[1] https://github.com/mhogomchungu/sirikali/blob/fdf10f6dfc51a6f5f3b87e76f070c1bc147709ee/src/siritask.cpp#L690-L747

**Comment by Achaean** [comment]
Ooops!!!
Sorry for mixing up contents! :-)

Indeed, installing ecryptfs-utils. solves the problem.
Just a suggestion:
Ecryptfs-utils should be added (I think) to ecryptfs-simple requirements, so Installing ecryptfs-simple will trigger ecryptfs-utils installation too.

PS. Since this is no longer a problem, I'm not opening a new thread.

**Comment by Achaean** [comment]
I tested it for a while and seems like it behaves properly now (with ecryptfs-utils installed).
It creates - mounts - unmounts directories without problem.
However, the specific directory (which created with previous version, without ecryptfs-utils) , still gives the same error.
(No problem for me. I have it backed up, elsewhere).
THANKS!!! :-)
