### ISSUE TITLE
Feature Request: Favorite stores mount options

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/sirikali#6]
It would be cool, if I could store mount options (e.g. an external configuration file) with a favorite file system.

**Comment by mhogomchungu** [comment]
current git version has the feature you requested here.

When adding a volume to favorites list,you will have an opportunity to also set idle time out,path to config file as well as if a volume should be available to auto mounting feature or not.

**Comment by smessmer** [comment]
Thanks. It works :)
