### ISSUE TITLE
How to translate

### ISSUE THREAD

**Issue by jony0008** [mhogomchungu/sirikali#60]
I would like to translate sirikali into Swedish, is there any instructions?

**Comment by mhogomchungu** [comment]
1. Install Qt Linguist. 
2. Go here[1] and then click "clone or download" and then click "Download Zip".
3. Extract the zip file and then browse to "translations" folder and then open "sv_SE.ts" file and with Qt Linguist and start adding your translations through the application.
4. Send me the file through my email address and i will add it to the project for everybody else to use.

All the translations i have received so far have worked as i described above.

If you know how to make pull requests on github then

1. Clone the repository using git
2. Add your translations to the "sv_SE.ts" file.
3. Upload your changes to your clone.
3. Make a pull request.

**Comment by mhogomchungu** [comment]
Are you doing the translation?

**Comment by jony0008** [comment]
@mhogomchungu Sorry, I haven't had the time.

**Comment by mhogomchungu** [comment]
Take your time, i am closing this one since the asked question was answered i think adequately. Feel free to ask here when you get around to doing the translation and you found the provided steps not sufficient.
