### ISSUE TITLE
MACOS: Failure to open and unmount encrypted folder with space

### ISSUE THREAD

**Issue by izenn** [mhogomchungu/sirikali#62]
When i mount a folder that has a space in the name i get the following error:
Could not open mount point because "/usr/bin/open" tool does not appear to be working correctly

when i try to unmount i get the following error:
"Failed to Unmount securefs Volume"

steps to recreate:
create new volume (in my case i created /Users/username/test 1)
mount new volume (works fine)
open (fails)
unmount (fails)

**Comment by mhogomchungu** [comment]
Did you use the git version or the released version?

**Comment by izenn** [comment]
i was using the release version.  I'll try the git version and then if i still have issues i'll run a --debug-full

**Comment by mhogomchungu** [comment]
The git version will probably also contain the issue as i have not changed anything that involves handling of paths..

Spaces in paths i though was a solved problem and i am surprised you are experiencing it and the problem must be specific to either Qt version you are using or Qt on MACOS.

**Comment by mhogomchungu** [comment]
The git version will probably also contain the issue as i have not changed anything that involves handling of paths..

Spaces in paths i though was a solved problem and i am surprised you are experiencing it and the problem must be specific to either Qt version you are using or Qt on MACOS.

**Comment by izenn** [comment]
Output from debug full (didn't output anything when i tried to unmount or open)
```
$ /Applications/sirikali.app/Contents/MacOS/sirikali --debug-full
objc[17114]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8f71cb68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10f8f0cd8). One of the two will be used. Which one is undefined.
-------------------------
Backend Generated Output:
Exit Code: 0
Command Sent To Backend: "/usr/local/bin/securefs" mount -b  -o rw -o fsname=securefs@"/Users/adam/test 2" -o subtype=securefs "/Users/adam/test 2" "/Users/adam/.SiriKali/test 2"
-------------------------
2018-03-27 10:20:03.300 sirikali[17114:144989] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
```
QT Version (from homebrew): qt-5.10.1.high_sierra.bottle.tar.gz

**Comment by mhogomchungu** [comment]
If i can inject an unrelated issue here, does the GUI properly update itself everytime you unlock/lock a volume or do you have to occassionally click "refresh" to force an update?

Back to your issue, i do not know how i can solve this one, those spaces are properly guarded with quotes and for some reason, Qt on your system appears to be be removing them.

**Comment by izenn** [comment]
for the unrelated issue, i have not had to hit refresh to date.

for the issue, what about a search/replace changing the " " to "\ " to escape the space?  I have been able to replicate the issue on 3 different high sierra systems running homebrew with the latest updated packages

**Comment by mhogomchungu** [comment]
That doesnt work and gcc complains with below warning
```
/home/ink/.projects/SiriKali/src/utility.h: In static member function ‘static QString utility::Task::makePath(QString)’:
/home/ink/.projects/SiriKali/src/utility.h:519:19: warning: unknown escape sequence: '\040'
    e.replace( " ","\ " ) ;
                   ^~~~
```

**Comment by izenn** [comment]
```e.replace( " ","\\ " ) ;``` worked for for compiling but it did not fix the issue.  i'm poking around the code now trying to figure out how to add logging (i'm not one to wait ;))

**Comment by mhogomchungu** [comment]
I should have read your comment, i already committed the code to log all executed comamnds, the commit is here: https://github.com/mhogomchungu/sirikali/commit/c7319d59c753014c203c5db522a4daaa01f3964d

The above commit generates below log when a securefs volume is created,its volume properties are checked and when the volume is closed.

```
[ink@mtz SiriKali (master)]$ sirikali --debug-full
-------
Exit Code: 0
Exit Status: 0
StdOut: 
-------
StdError: 
-------
Command: "/usr/bin/securefs" create   "/home/ink/securefs"
-------
Exit Code: 0
Exit Status: 0
StdOut: 
-------
StdError: [Warning] [0x7f115b79b3c0] [2018-03-27 17:43:42.274343872 UTC]    securefs is about to enter background without a log file. You won't be able to inspect what goes wrong. You can remount with option --log instead.
-------
Command: "/usr/bin/securefs" mount -b  -o rw -o fsname=securefs@"/home/ink/securefs" -o subtype=securefs "/home/ink/securefs" "/home/_/securefs"
-------
Exit Code: 0
Exit Status: 0
StdOut: Config file path: /home/ink/securefs/.securefs.json
Filesystem format version: 4
Is full or lite format: lite
Is underlying directory flattened: false
Is multiple mounts allowed: true
Is timestamp stored within the fs: false

Content block size: 4096 bytes
Content IV size: 96 bits
Password derivation algorithm: PBKDF2-HMAC-SHA256
Password derivation iterations: 65536
Per file key generation algorithm: AES
Content cipher: AES-128-GCM
-------
StdError: 
-------
Command: "/usr/bin/securefs" info "/home/ink/securefs"
-------
Exit Code: 0
Exit Status: 0
StdOut: 
-------
StdError: 
-------
Command: fusermount -u "/home/_/securefs"
[ink@mtz SiriKali (master)]$ 

```

**Comment by mhogomchungu** [comment]
I do not have a MAC and all the support come from users like yourself. There is some code in MACOS i would like to update and i was hopping you will help me test it but you will have to be running git version of SiriKali to test it.

**Comment by izenn** [comment]
I have no problems testing and debugging 👍 
Here is the output when i mount and then unmount
(tl;dr it is trying to umount "on")

```
$ sirikali.app/Contents/MacOS/sirikali --debug-full
Previous instance seem to have crashed,trying to clean up before starting
-------
Exit Code: 0
Exit Status: 0
StdOut: /dev/disk1s1 on / (apfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s4 on /private/var/vm (apfs, local, noexec, journaled, noatime, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
-------
StdError: 
-------
Command: mount
-------
Exit Code: 0
Exit Status: 0
StdOut: /dev/disk1s1 on / (apfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s4 on /private/var/vm (apfs, local, noexec, journaled, noatime, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
-------
StdError: 
-------
Command: mount
-------
Exit Code: 0
Exit Status: 0
StdOut: /dev/disk1s1 on / (apfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s4 on /private/var/vm (apfs, local, noexec, journaled, noatime, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
-------
StdError: 
-------
Command: mount
objc[24971]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8f71cb68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x107cf0cd8). One of the two will be used. Which one is undefined.
-------
Exit Code: 0
Exit Status: 0
StdOut: 
-------
StdError: [Warning] [0x7fff92b21340] [2018-03-27 17:57:52.620481000 UTC]    securefs is about to enter background without a log file. You won't be able to inspect what goes wrong. You can remount with option --log instead.
-------
Command: "/usr/local/bin/securefs" mount -b  -o rw -o fsname=securefs@"/Users/adam/test 2" -o subtype=securefs "/Users/adam/test 2" "/Users/adam/.SiriKali/test 2"
-------
Exit Code: 0
Exit Status: 0
StdOut: 
-------
StdError: 
-------
Command: /usr/bin/open "/Users/adam/.SiriKali/test 2"
-------
Exit Code: 0
Exit Status: 0
StdOut: /dev/disk1s1 on / (apfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s4 on /private/var/vm (apfs, local, noexec, journaled, noatime, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
securefs@/Users/adam/test 2 on /Users/adam/.SiriKali/test 2 (osxfuse, nodev, nosuid, synchronous, mounted by adam)
-------
StdError: 
-------
Command: mount
-------
Exit Code: 0
Exit Status: 0
StdOut: /dev/disk1s1 on / (apfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s4 on /private/var/vm (apfs, local, noexec, journaled, noatime, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
securefs@/Users/adam/test 2 on /Users/adam/.SiriKali/test 2 (osxfuse, nodev, nosuid, synchronous, mounted by adam)
-------
StdError: 
-------
Command: mount
-------
Exit Code: 1
Exit Status: 0
StdOut: 
-------
StdError: umount: on: not currently mounted
-------
Command: umount "on"
-------
Exit Code: 1
Exit Status: 0
StdOut: 
-------
StdError: umount: on: not currently mounted
-------
Command: umount "on"
-------
Exit Code: 1
Exit Status: 0
StdOut: 
-------
StdError: umount: on: not currently mounted
-------
Command: umount "on"
-------
Exit Code: 1
Exit Status: 0
StdOut: 
-------
StdError: umount: on: not currently mounted
-------
Command: umount "on"
-------
Exit Code: 1
Exit Status: 0
StdOut: 
-------
StdError: umount: on: not currently mounted
-------
Command: umount "on"

```

**Comment by izenn** [comment]
i think i've narrowed the problem down to volumeinfo.h:
```
                        utility2::stringListToStrings( e,
                                                      volumePath,
                                                      mountPoint,
                                                      fileSystem,
                                                      mode,
                                                      idleTimeout,
                                                      mountOptions ) ;
```
because of the space it is pulling the wrong thing for fileSystem

**Comment by mhogomchungu** [comment]
I will be grateful if you can solve this because, as i said,  i dont have a MAC and the current code works fine on linux and windows.

To test the new functionality i just added on MACOS, update from git version and then look up this[1] value here and change it to "1" and then recompile and then unlock a volume and lock it and see the GUI will update itself.

[1] https://github.com/mhogomchungu/sirikali/blob/5fafb8183d106d2c58856be7da28d3d17575cbea/src/mountinfo.cpp#L455

**Comment by mhogomchungu** [comment]
I think i have found out the problem, the entry for the volume given my "mount" command on your system looks like below:

```
securefs@/Users/adam/test 2 on /Users/adam/.SiriKali/test 2 (osxfuse, nodev, nosuid, synchronous, mounted by adam)
```
The problem is here because "mount" output does not make any attempt to shield to space character on a path, "mount" command on linux has the same issue but the problem is not on linux version of SiriKali because on linux, SiriKali uses output of "/proc/self/mountinfo" and it preserves the space character by substituting it with "\040". An entry for securefs with a space character on its path looks like below on "/proc/self/mountinfo"

```
34 30 0:28 / /home/_/foo\040bar rw,nosuid,nodev,relatime - fuse.securefs securefs@/home/ink/foo\040bar rw,user_id=500,group_id=500
```

The problem is not there on SiriKali windows because i took care of it here[1] and the same thing need to happen on MACOS.

[1] https://github.com/mhogomchungu/sirikali/blob/5fafb8183d106d2c58856be7da28d3d17575cbea/src/winfsp.cpp#L201

**Comment by izenn** [comment]
can you elaborate on what you want me to test with your comment:
To test the new functionality i just added on MACOS, update from git version and then look up this[1] value here and change it to "1" and then recompile and then unlock a volume and lock it and see the GUI will update itself.

I changed the value and recompiled but i'm not sure what i'm looking for

**Comment by mhogomchungu** [comment]
After you have changed the value to "1" and recompile, use SiriKali normally and pay attention to the GUI and see if the GUI automatically update itself to added volumes/removed volumes. If the GUI updates itself normally then all is good. You should though notice a slight delay after a volume is unlocked/locked before the GUI updates itself.

**Comment by izenn** [comment]
the gui seems to be updating properly - even when i manually unmount from the command line

**Comment by mhogomchungu** [comment]
Thanks for confirming the new code works.

Going back to your original issue, the problem is here[1] were we are reading volume entries from the system using "mount" command and we get confused since this command doesnt event attempt to preserve spaces on paths. Do you know of another way of checking for mounted volumes on MACOS?

[1] https://github.com/mhogomchungu/sirikali/blob/883d89928116cfb10f0e6274a861723caa668251/src/mountinfo.cpp#L52

**Comment by izenn** [comment]
i'm working on an alternate to mount.  I'll get back to you once i figure something out

**Comment by izenn** [comment]
what if we use df
```
$ df
Filesystem                  512-blocks      Used Available Capacity iused               ifree %iused  Mounted on
/dev/disk1s1                 489620264 106461688 379751896    22%  992174 9223372036853783633    0%   /
devfs                              451       451         0   100%     780                   0  100%   /dev
/dev/disk1s4                 489620264   2097192 379751896     1%       1 9223372036854775806    0%   /private/var/vm
map -hosts                           0         0         0   100%       0                   0  100%   /net
map auto_home                        0         0         0   100%       0                   0  100%   /home
securefs@/Users/adam/test 2  489620264 106461688 379751896    22%  992174          4293975121    0%   /Users/adam/.SiriKali/test 2
```

**Comment by izenn** [comment]
another update -- using gnu coreutils (brew install coreutils) i was able to get a better version of df where we can specify columns:
```
$ gdf --output=source,target
Filesystem                  Mounted on
/dev/disk1s1                /
/dev/disk1s4                /private/var/vm
securefs@/Users/adam/test 2 /Users/adam/.SiriKali/test 2
```

**Comment by mhogomchungu** [comment]
Above solution has two problems.

1. It introduces a dependency to the project
2. It does not have information that says the volume is read only or not.

I think the solution is with this[1] Qt class and i have set up a place for you to experiment with it here[2]. Change the value at line 48 to "0" for the alternative path to be used and experimented on.

It It should be easier to experiment with different solution within this function. The only requirement the function has is that its output must be equivalent to "mount" output.

[1] http://doc.qt.io/qt-5/qstorageinfo.html
[2] https://github.com/mhogomchungu/sirikali/blob/db93ca9484f21148122dc3fc4a303f3e8db8819d/src/mountinfo.cpp#L46

**Comment by izenn** [comment]
using the new code and changing 48 to 0 i still get the error:
Command: umount "on"

**Comment by mhogomchungu** [comment]
Can you try again, change the value again to 0, recompile and see if the problem is still around.

**Comment by izenn** [comment]
looking better!!
Volume path is reporting as a weird number and properties doesn't work, but unmount does.  also for my own reference, the value to change is on 69 instead of 48

here is the debug output:
```
Exit Code: 0
Exit Status: 0
StdOut: 
-------
StdError: 
-------
Command: "/usr/local/bin/securefs" create   "/Users/adam/test 2"
-------
git add
Exit Code: 0
Exit Status: 0
StdOut: 
-------
StdError: [Warning] [0x7fff8f098340] [2018-03-27 22:37:20.265165000 UTC]    securefs is about to enter background without a log file. You won't be able to inspect what goes wrong. You can remount with option --log instead.
-------
Command: "/usr/local/bin/securefs" mount -b  -o rw -o fsname=securefs@"/Users/adam/test 2" -o subtype=securefs "/Users/adam/test 2" "/Users/adam/.SiriKali/test 2"
-------
git add
Exit Code: 33
Exit Status: 0
StdOut: 
-------
StdError: [Error] [0x7fff8f098340] [2018-03-27 22:37:33.913878000 UTC]    The path 90784200/.securefs.json does not exist. Perhaps you are pointing to the wrong data directory?
-------
Command: "/usr/local/bin/securefs" info "90784200"
-------
git add
Exit Code: 0
Exit Status: 0
StdOut: 
-------
StdError: 
-------
Command: umount "/Users/adam/.SiriKali/test 2"
-------
git add
```

**Comment by mhogomchungu** [comment]
update from git, make the same change and try again.

**Comment by izenn** [comment]
everything is working perfectly now!!  I've found a couple other weird issues but none that prevents the app from working properly.  I'll open new issues for them

**Comment by mhogomchungu** [comment]
Final test, build from git version, compile and test to see if everything works as expect. There is no longer need to modify the code because the new way is know active by default. I have rearranged the code a bit i want to be sure i did not break anything.

**Comment by izenn** [comment]
nothing broke on my end
