### ISSUE TITLE
MacOS: After Hiding window, unable to bring it back

### ISSUE THREAD

**Issue by izenn** [mhogomchungu/sirikali#64]
On Mac, after i hide the window using the red x, the only way i'm able to get the window to show back up is to go to the system tray and tell it to open settings.  the window will then show up and all i need to do is close settings so that i can continue to mount/unmount volumes.

**Comment by mhogomchungu** [comment]
On linux and windows at least, SiriKali generates a tray icon and closing the main window hides the window and the application continues to live but minimized to tray. Clicking the tray icon is supposed to unhide the GUI,clicking the tray icon when the GUI is visible hides it. The whole that does these two things is here[1]. 

Are you saying SiriKali generates a tray icon as designed but clicking the icon does nothing?

[1] https://github.com/mhogomchungu/sirikali/blob/3416f35208fb9253e38f40ce552a5dc9443a121d/src/sirikali.cpp#L1382-L1399

**Comment by izenn** [comment]
kind of.  on Mac, clicking (both right or left) on the tray icon brings up the menu (similar to what happens if i right click on windows) but then clicking again to close the menu will bring the window back ONLY if the app is the main focus application.  Let me know if you want me to make a video -- i know this description is a bit strange

**Comment by mhogomchungu** [comment]
A video will be very much appreaciated.

**Comment by mhogomchungu** [comment]
Update from git and test again if SiriKali window managed to become a foreground window after its activated from the tray icon.

**Comment by izenn** [comment]
no luck -- still just a bouncing icon rather than bringing it to the foreground

**Comment by mhogomchungu** [comment]
I do not think its possible to force a hidden window on MACOS to be a top window programatically.

This is documented as it cant be done in windows[1] but this documentation doesn't say anything about MACOS.

Closing this one with a "it can't be done" tag on it.

[1] http://doc.qt.io/qt-5/qwidget.html#activateWindow
