### ISSUE TITLE
Failure to decrypt.

### ISSUE THREAD

**Issue by Achaean** [mhogomchungu/sirikali#65]
After entering the pwd, Sirikali mounts the encrypted volume, but it remanes encrypted.
Sirikali v1.3.3 with ecryptfs-simple (from repository), at Debian Jessie x64 KDE.

**Comment by mhogomchungu** [comment]
Sorry for the long delay, things were a bit hectic on this end.

That is very strange, are you sure you are looking at the  ```plain folder(mount point path)``` and not ```cipher folder```?

After you have mounted the volume, run the following command and post its output:
```
cat /proc/self/mountinfo | grep ecryptfs
```

**Comment by Achaean** [comment]
1) No problem for the delay! :-)

2) Sorry, but I delete the directory. I don't have it any more. :-(

3) Somehow my ext4 filesystem (where the encrypted directory was resting), got corrupted.
Maybe some problem with the (really old) Linux kernel I was using.
I'll upgrade to a more recent asap.
Here's my post at Debian's fora (for the ext4 filesystem corruption problem I faced):
http://forums.debian.net/viewtopic.php?f=10&t=137138

**Comment by mhogomchungu** [comment]
Closing this one because i dont like opened issues.

Feel free to reopen when you experience the problem again.
