### ISSUE TITLE
Unable to build on mac

### ISSUE THREAD

**Issue by kabo** [mhogomchungu/sirikali#66]
Hi,

I'm using SiriKali on my Linux machines and it works great, thanks for that.
But I'm trying to build SiriKali 1.3.3 on a Mac now. First, the build instructions should probably add `brew install cmake` in the dependencies section, as cmake wasn't installed.

Then I can't get `make` to work. I've attached the [output](https://github.com/mhogomchungu/sirikali/files/1949311/output.txt).

Running Mac 10.10.5, XCode 7.2.1

**Comment by kabo** [comment]
I tested `brew install gcc` and then made symlinks in `/usr/local/bin` so `cc` and `c++` would get picked up by the `cmake` script. It got me another error. 
[output2.txt](https://github.com/mhogomchungu/sirikali/files/1949735/output2.txt)

**Comment by mhogomchungu** [comment]
Try to build with again with AppleClang but first go to the problematic source file located here[1] and then add ```+#include <cstdlib``` somewhere at the top and try to build again.

If that still fail, then change ```std::malloc``` to ```malloc```

[1] /Users/frida/Downloads/SiriKali-1.3.3/src/3rdParty/lxqt_wallet/frontend/lxqt_wallet.cpp

**Comment by kabo** [comment]
Yup, adding `#include <cstdlib>` at the top of that file solved it. Thanks!
