### ISSUE TITLE
Could the author provide SHA/MD5 hash of encfs win 1.9.5 with PGP sign?

### ISSUE THREAD

**Issue by ccchan234** [mhogomchungu/sirikali#67]
Hi~

I saw the author have a PGP signature for himself 's contact.

Yet the binary for encfs build 1.9.5 is not signed.

Sign it may be trouble some.

But I think the author may help by
calculating the hash, put it in a txt and then sign the .TXT with his PGP?

We use encryption because we trust no authority but open source code.
Running a binary without knowing the source is contradication to OUR belief I think.

Thank you.

**Comment by mhogomchungu** [comment]
Done
