### ISSUE TITLE
Feature Request: Auto-Mount setting on a per-filesystem basis

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/sirikali#7]
It's currently not possible, to auto-mount some file systems from the favorite list only. I think it would make sense to have this setting be on a per-filesystem basis. It could for example be set as a boolean flag in the favorite file system.

**Comment by mhogomchungu** [comment]
current git version has the feature you requested here.

When adding a volume to favorites list,you will see a check box that makes the volume available to auto mounting functionality.

**Comment by smessmer** [comment]
Thanks
