### ISSUE TITLE
sshfs-win - Failed to complete the task / Warning: Permanently added ... to the list of known hosts

### ISSUE THREAD

**Issue by 4O4** [mhogomchungu/sirikali#72]
![](https://i.imgur.com/zcluNr6.png)

It is shown only during the first trial - standard behaviour of the ssh client. I think that warnings can be ignored if they can be distinguished by exit status or something.

**Comment by mhogomchungu** [comment]
I can not reproduce this one and i suspect you got this behavior when sshfs-win picked up the openssh's ssh and used to to connect to a remote system for the first time.

The behavior i see here is the same as what you reported here[1]

[1] https://github.com/mhogomchungu/sirikali/issues/73

**Comment by mhogomchungu** [comment]
This problem should be gone now since SiriKali will always connect using ",StrictHostKeyChecking=no" option to make sure this problem does not occur.

**Comment by mhogomchungu** [comment]
Beta version of sshfs-win is out(SSHFS-Win 3.2 BETA) and with it, SiriKali now correctly handles a first time connection to a remote system with "StrictHostKeyChecking=yes" option set.

![sirikali](https://user-images.githubusercontent.com/3496115/45076944-81251500-b0f4-11e8-8392-7790897659d5.png)

**Comment by LokLu** [comment]
I came across with the same issue. The "StrictHostKeyChecking" is set to no. The remote folder can be mounted firstly. But after around half minute, the following error was displayed and the remote folder was unmounted.
![image](https://user-images.githubusercontent.com/24246633/50463261-ac927f00-09c5-11e9-8072-a26245a01960.png)
