### ISSUE TITLE
sshfs-win - "Failed to complete the task..." error message with no additional log

### ISSUE THREAD

**Issue by 4O4** [mhogomchungu/sirikali#73]
![](https://i.imgur.com/l1VjCzx.png)

This issue is specific to the recent versions of Windows 10 that come with OpenSSH. I haven't been digging what is the root cause because it looks like some compatibility issues. The solution is simple however - SSHFS-WIN must go before `%SYSTEMROOT%\System32\OpenSSH\` in `PATH`

Submitting just in case because sooner or later someone else is gonna have the exact same system setup as I have and this might be pretty tricky to debug. I've just had a lot of luck that I saw "C:\Windows\System32\OpenSSH' in one of the previous error messages and that instantly made me suspicious.

**Comment by mhogomchungu** [comment]
I think i have solved this issue with this[1] commit, previously, the locations of where sshfs and encfs were added to the end of the PATH variable and the commit moves them to the front.

[1] https://github.com/mhogomchungu/sirikali/commit/9cf3e7488ad4a1f9cd2eaa9bf7420f5c6a22b3b2

**Comment by mhogomchungu** [comment]
I have reproduced this bug and i think the problem is with upstream and i have reported it here[1]

[1] https://github.com/billziss-gh/sshfs-win/issues/40

**Comment by mhogomchungu** [comment]
I think this problem is caused by hanging sshfs-win when attempting to write to "known_host" file and the problem should be gone now since SiriKali will always connect using ",StrictHostKeyChecking=no" option to make sure this problem does not occur.
