### ISSUE TITLE
Add support for cryptomator

### ISSUE THREAD

**Issue by fago** [mhogomchungu/sirikali#81]
It would be nice if support for cryptomator could be added.

Recent versions gained support for a fuse based mount and there is a CLI available: https://github.com/cryptomator/cli

Unfortunately cryptomator lacks auto-mount and secured password storage support via libsecret and co what sirikali implements nicely. Adding support for cryptomator in sirikali might be a good way to implement this: https://github.com/cryptomator/cryptomator/issues/422

**Comment by mhogomchungu** [comment]
The CLI version seems to lack support for fuse on linux[1]. Without it and based on a short testing of cryptomator-cli i have done, SiriKali will have to the following to work with it:

1. Start "cryptomator-cli" as a server and manually baby sitting it to make it behave like a daemon.
2. Gain root's privileges to mount a volume(mount command is used to mount).
3. On unmount, gain root's privileges again to unmount the volume(umount command is used to unmount).
4. Shut down the babysitted instance.

This "cryptomator-cli" tool currently works too differently to support on Linux and MACOS. SiriKali babysits its backends only on windows.

I am closing this one as a "wontfix" and feel free to reopen it again once "cryptomator-cli" gains support for FUSE backend.
 



[1] https://github.com/cryptomator/cli/issues/22#issuecomment-414322188

**Comment by mhogomchungu** [comment]
SiriKali now supports cryptomator-cli and the feature is discussed here: https://github.com/mhogomchungu/sirikali/issues/127

**Comment by mhogomchungu** [comment]
New version is out[1] and it has support for cryptomator[2]. The cryptomator page has info on how to make SiriKali aware of it.

[1] https://github.com/mhogomchungu/sirikali/releases/tag/1.4.8
[2] https://github.com/mhogomchungu/cli
