### ISSUE TITLE
MacSO: Unable to change language in Settings

### ISSUE THREAD

**Issue by defragekb** [mhogomchungu/sirikali#84]
I'm unable to change the apps language in the options (the list doesnt open when i click on 'Select language', just no reaction at all).
The language files have copied to the correct folder:
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/changelog
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/de_DE.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/en_US.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/es_MX.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/fr_FR.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/ru_RU.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/sirikali.icns

I've tried to hardcode the path in settings.cpp and it worked. However, it listed all the files from Resources folder.

After applying the suggested fix:
```
if( APPLE )
	file( WRITE ${PROJECT_BINARY_DIR}/locale_path.h "\n#define TRANSLATION_PATH \"${CMAKE_INSTALL_FULL_DATADIR}/sirikali.app/Contents/Resources/\"\n")
else()
	file( WRITE ${PROJECT_BINARY_DIR}/locale_path.h "\n#define TRANSLATION_PATH \"${CMAKE_INSTALL_FULL_DATADIR}/sirikali/translations/\"\n")
endif()
```

 the content in locale_path.h is:

`#define TRANSLATION_PATH "/Users/username/sirikali/share/sirikali.app/Contents/Resources/"`

which looks incorrect to me as there shoudn't be 'share' folder in the path. Additionally, this will make the path to be hardcoded as well, leading the broken functionality if we will move the .app to another location. Maybe I'm wrong as I'm not a programmer.

**Comment by defragekb** [comment]
This is the code I've tried that worked for me:

```
QString settings::localizationLanguagePath()
{
	if( utility::platformIsWindows() ){

		return QDir().currentPath() + "/translations" ;
		
	}else if( utility::platformIsOSX() ){
	
		return "/Users/username/sirikali/sirikali.app/Contents/Resources/";
		
	}else{
		return TRANSLATION_PATH ;
		
	}
}
```
But it wont work if the .app moved to another folder.

**Comment by mhogomchungu** [comment]
Change the lines in CMakeLists.txt file to below and try again
```
if( APPLE )
	file( WRITE ${PROJECT_BINARY_DIR}/locale_path.h "\n#define TRANSLATION_PATH \"${CMAKE_INSTALL_PREFIX}/sirikali.app/Contents/Resources/\"\n")
else()
	file( WRITE ${PROJECT_BINARY_DIR}/locale_path.h "\n#define TRANSLATION_PATH \"${CMAKE_INSTALL_FULL_DATADIR}/sirikali/translations/\"\n")
endif()
```

The long term solution on MAC is to create the so colled "bundle application" and read the translation files using  relative paths like way its done in windows.

**Comment by mhogomchungu** [comment]
> I've tried to hardcode the path in settings.cpp and it worked. However, it listed all the files from Resources folder.

Solution to this problem is to go here[1]  and changing

```
if( !it.startsWith( "qt_" ) )
```

to
```
if( !it.startsWith( "qt_" ) && it.endsWith( ".qm" ))
```
[1] https://github.com/mhogomchungu/sirikali/blob/fa3bd18172880a70ffbd1348481a80478d20da33/src/settings.cpp#L384

**Comment by defragekb** [comment]
> Change the lines in CMakeLists.txt file to below and try again

The path is correct now and the language selection works now.

Going to try the fix from the post above

**Comment by defragekb** [comment]
Now the language list contains languages only. Great!
What about changing language filenames to something more user-friendly? Let's say instead de_DE rename it to German etc?

**Comment by defragekb** [comment]
I think for the different versions of the same language it might would be better to add this info within the filename, i.e. Spanish (MX) etc.
However, when I tried to play with this, I've found that it won't apply the language if the filename contains spaces or letters with diacritic symbols such as ñ, so we can't use filename such as Español (MX) or Français.

If this isn't really hard to fix I think it would be cool, so people who don't know how their native language will be in English could easily find it.
Or at least make it possible to handle spaces in the filenames correctly then will be no problems with specifying the language version using English.

My native language is Russian. I haven't checked the translation to it yet.

**Comment by mhogomchungu** [comment]
The fix should be easy enough and it involves having a simple map of a translatable string a user see and the current name that is used internally.

It will be something like ```Español (MX) ```->```es_MX```

So, how would you translate ```Russian (RU)``` in Russian?

**Comment by defragekb** [comment]
Russian will be Русский. We have only one version so there's no need to specify that.

**Comment by mhogomchungu** [comment]
The list of supported languages is not more user friendly and translatable.

![screenshot_20181213_060437](https://user-images.githubusercontent.com/3496115/49913238-f21b5c00-fe9d-11e8-85be-cf6f9e1c0969.png)

**Comment by mhogomchungu** [comment]
No, i have not and i can not because i do not have a MAC to work on it, somebody else who has a MAC will have to donate the functionality.

An alternative fix i can do is to have a setting in an easily found area where a user can change the default location of where the language files should be searched or maybe have a predetermined list of paths of where to search for the language files.

I am open to suggestions.

**Comment by defragekb** [comment]
Ok I got it. Unfortunately, I'm zero in coding, especially in C++. I've tried to inject a code to print out some variables in a text file to find out whether some of them could be used as a base to build a relative path, but failed to compile that code. Some random guessing haven't brought any positive results as well.
So I have no idea if it is possible somehow to get the current working directory of the app, especially the path where running binary is located, something like 'pwd' command. It would be easy to build a path to the translations folder if we know the path for the binary, right?
I would be happy to help if I could to do more..

Or at least maybe state in OSX_BUILD_INSTRUCTION that the DCMAKE_INSTALL_PREFIX option is better to be a path where the main app location is planned, e.g. /Application or whatever a user wants

**Comment by mhogomchungu** [comment]
I just found out about this[1] API and i think its what we need when trying to figure out the executable is located where on the file system.

Update from git repository and post the full output of "make install" because i want to see where the executable is located, the output you gave in your first post does not contain this information.

Once you have SiriKali installed, try to move around the installation folder and see if it can still pick up the translation files.

The function that use the API is here[2]. I think this method will work only if sirkali binary is located in the root path of the installation folder.

[1] http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath

[2] https://github.com/mhogomchungu/sirikali/blob/0f688613a1c068a03df061187c0332173a7e0def/src/settings.cpp#L441

**Comment by defragekb** [comment]
I'm sorry for being silent so long, had no time at all for this.

> Update from git repository and post the full output of "make install" because i want to see where the executable is located, the output you gave in your first post does not contain this information.

```
$ make install
[  2%] Built target mhogomchungu_task
[  4%] Built target lxqt-wallet-backend
[ 14%] Built target lxqt-wallet
[ 16%] Built target mhogomchungu_network
[100%] Built target sirikali
Install the project...
-- Install configuration: "RELEASE"
-- Installing: /Users/username/sirikali/./sirikali.app
-- Installing: /Users/username/sirikali/./sirikali.app/Contents
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Info.plist
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/MacOS
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/MacOS/sirikali
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/changelog
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/de_DE.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/en_US.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/es_MX.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/fr_FR.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/ru_RU.qm
-- Installing: /Users/username/sirikali/./sirikali.app/Contents/Resources/sirikali.icns
```

On the previous builds when we were trying to make sirikali to be able to pick up the language files, the app was able to do so when it was run from the dir it was installed and wasn't able to pick them up if was moved anywhere else out of the install dir.

Today, I've cloned the lasted build from git and built it. The app wasn't able to pick up the lang files even being run from the install dir.

Of course it was run from Finder. Not from a "shortcut" but by double click on the sirikali.app folder (macOS treat it not like a regular folder and by default not just showing files within the dir, but runs the app). So, in this case there is no way to see any stdout.

However, if using the Terminal app navigate inside the app and run the binary itself, it will be possible to see output sent to stdout. I've tried this now, but the app still wasn't able to pick up any languages.

```
~$ cd sirikali/sirikali.app/Contents/MacOS/
MacOS$ ./sirikali 
```


The previous build I've built (from begin of Jan) is still on my system and it picks up the langs being run both from Finder and Terminal by launching the binary itself when it is in install dir, but after being moved to any other location both ways of running it, doesn't pick up the langs.

I've tried to re-build the app after editing the code like this:
```
QString settings::localizationLanguagePath()
{
   std::cout << QDir::currentPath().toLatin1().constData() << std::endl ;
	if( utility::platformIsWindows() ){
...

```
but running the app from the binary via Terminal didn't show any output when I tried language selection.

Even though this function looks the same as in the previous builds, it doesn't work anymore(?)

```
$cat locale_path.h 

#define TRANSLATION_PATH "/Users/username/sirikali/sirikali.app/Contents/Resources/"
```
looks correct.

I hope this info will be helpful for you. Have no idea how else I can help.
Not sure I will be able to reply fast here, but I will try.

**Comment by mhogomchungu** [comment]
I just became friends with a person who owns a mac, will ask him to use it over the weekend and will try to solve the problem.
