### ISSUE TITLE
sshfs-win - Failed to complete the task

### ISSUE THREAD

**Issue by LokLu** [mhogomchungu/sirikali#85]
I came across with the same issue. The "StrictHostKeyChecking" is set to no. The remote folder can be mounted firstly. But after around half minute, the following error was displayed and the remote folder was unmounted.
![image](https://user-images.githubusercontent.com/24246633/50463261-ac927f00-09c5-11e9-8072-a26245a01960.png)
I used sshfs-win-2.7 and the latest sirikali under Win10

_Originally posted by @LokLu in https://github.com/mhogomchungu/sirikali/issues/72#issuecomment-450061594_

**Comment by mhogomchungu** [comment]
Version 2.7 of sshfs-win is too old and the bug you are experiencing was fixed in recent versions.

Go here[1] and install version 3.2(Beta) and try again

[1] https://github.com/billziss-gh/sshfs-win/releases

**Comment by LokLu** [comment]
@mhogomchungu  Solved, thanks for your quick reply!
One small question, if I want to automatically fill in the password, what cmd should I put in the mount options?

**Comment by mhogomchungu** [comment]
That functionality is not there yet on windows and its in my TODO list but it exists in Linux and MACOS.

Closing this one since the reported issue is fixed.

**Comment by mhogomchungu** [comment]
The next version of SiriKali will refuse to work with version 2.7 and below of sshfs-win.

![screenshot_20181228_142511](https://user-images.githubusercontent.com/3496115/50514662-bb099500-0ab0-11e9-8489-f441c4c0c6bc.png)

**Comment by mhogomchungu** [comment]
About your second question, what is your use case?

1. Are you using a password and you want SiriKali to store it somehow and automatically retrieve it when trying to connect to a remote server?

2. You are using private keys and you want SiriKali to automatically inform sshfs where its it located so that it can use it to connect to the remote server?

3. Both of the above?
