### ISSUE TITLE
Could not create directory

### ISSUE THREAD

**Issue by mdehollander** [mhogomchungu/sirikali#90]
I am getting this error when mounting a remote filesystem. The disk and files are available for a few minutes, and then this message appears and the files are not longer accessible:

![image](https://user-images.githubusercontent.com/262872/51757188-09677f00-20c3-11e9-9f5f-ef064ddbb8a8.png)

First I thought it was a problem with WinFsp because there was just a release of 2019.1. But also with the 2018.1 the same things happens. Any thoughts what could be wrong?

**Comment by mhogomchungu** [comment]
This is a known problem[1] and its one sshfs version. It will be fixed there when the new version is out but you can overcome it now by using the beta version posted in the link below.

[1] https://github.com/mhogomchungu/sirikali/issues/85

**Comment by mdehollander** [comment]
Thanks a lot of your quick reply. Your GUI makes it really easy to mount remote file systems with open-source software. Thanks for providing this. I will give it a try with the sshfs beta version.
