### ISSUE TITLE
Sirikali displays "Gocryptfs Is Not Installed" despite /usr/local/bin/gocryptfs being present

### ISSUE THREAD

**Issue by lestephane** [mhogomchungu/sirikali#98]
How is gocryptfs presence being checked for? I downloaded the latest release of gocryptfs from github (there is no official package in ubuntu 16.04). gocryptfs is therefore in the PATH and executable. So what gives?

![image](https://user-images.githubusercontent.com/5460884/56500165-48a64000-64f9-11e9-99d3-9aec488c178c.png)

```bash
$ which gocryptfs
/usr/local/bin/gocryptfs
$ gocryptfs --version
gocryptfs v1.7 without_openssl; go-fuse v1.0.0-13-g75aaa80; 2019-03-17 go1.12
```

**Comment by mhogomchungu** [comment]
Did you restart SiriKali after you have installed gocryptfs?

**Comment by lestephane** [comment]
I need to install sirikali again to check

**Comment by lestephane** [comment]
Seems fine now, never mind
