### ISSUE TITLE
Feature Request - 'cleanup' and 'cruft' monitoring and resolution.

### ISSUE THREAD

**Issue by timoc** [mhogomchungu/sirikali#99]
One of the problems i constantly have with an encrypted filesystem, especiually one being synced in real-time by Dropbox or Onedrive-d is   their conflict resoultion breaks the filesystem.
e.g. Dropbox will make conflicted files for file "dklhfdshf9qeqw1" as "dklhfdshf9qeqw1-conflicted" or similar.

The conflict resolution approach i took before in [my old and abandoned sirikali like tool](https://github.com/timoc/encfsbox) was to automatically rename the unusable conflict file into a usable one. So <encfs:"filename">-conflicted into <encfs:filename-conflcted>

The feature request would be to do this, or notify the user of this and allow them to resolve it.

**Comment by mhogomchungu** [comment]
1. SiriKali already supports running a custom command before a volume is unmounted. 
2. SiriKali already supports running a custom command after a volume is mounted.

The custom command is required to return 0 for the volume to be unmounted.

Cant you create a script that SiriKali runs on those two occasions to get the behavior you want?

The behavior you want is very specific and i dont think SiriKali should carry it and the best i can do is add facilities to enable users to run their custom commands to give them the opportunity to extend its functionality.

Adding an ability to periodically run a custom customs is something i can do if your particular solution needs it.

**Comment by timoc** [comment]
Does SiriKali make the mount credentials available to to the script? I cannot tell much from #46
It implies the path is passed, and it sends the password to stdout if not empty, but `encfs showcruft` 
For example `encfsctl showcruft $mountpoint` needs the mount password to run, but there is no evidence that it worked.

Extending this approach will work for me. 
Can i suggest:
- all script Exit code and stderr/stdout to notification channel debugging output would work for me.
- 'test run script', the effort and debugging time on scripts is limited by the REPL of manually mounting and unmounting entering passwords again etc. 
- An additional 'monitoring script'. This is a script run every so often that can (via exit code) generate a notification such as a cruft warning. I would use it for encfs showcruft, but i am sure the other filesystems have a fsck-alike, or have artifact littering issues when used on a cloud drive.

nice to have would be 
- per mountpoint scripts, rather than global scripts

**Comment by mhogomchungu** [comment]
SiriKali does not send credentials to custom commands.

The post mount custom command is given 3 arguments.
1. The cipher folder path.
2. The mount point path.
3. The volume type.

The pre unmount custom command is given a single argument, the mount point path. The volume will be unmounted ONLY if the custom command returns zero.

The debug window in the git version now shows results from these custom commands.

Will start working on running custom commands periodically and with user specified intervals next.

Below image shows debug output for a command that unlocked an encfs volume and debug output for post mount custom command.

![Screenshot_20190511_113156](https://user-images.githubusercontent.com/3496115/57567369-bea71400-73e0-11e9-995b-c3499c7629c4.png)

**Comment by mhogomchungu** [comment]
The git version can now custom command every 10 minutes by default. You can change the value by changing ``runCommandOnIntervalTime``` configuration value. Times are in minutes.

The custom command can be added using ```runCommandOnInterval``` config option. After every interval minutes, the command will run once with each unlocked volume and it will be given 3 arguments.
1. Cipher path.
2. Mount point path.
3. Volume type.

The config file is located at ```~/.config/SiriKali/SiriKali.conf```

I am not sure if passing credentials to third party programs is a good idea and it probably wouldnt work consistently because SiriKali on linux and MACOS can be closed and restarted without affecting unlocked volumes and restarting SiriKali means losing all data stored in memory.

**Comment by mhogomchungu** [comment]
I wasnt going to add a GUI way to set the command that runs periodically but i just did and the attached image has proof of it. The last two entries came from this bug report.

I am closing this one since i think what is already done is the best i can do.

It will be up to your script to notify the user if it sees there is a need to do so. I am not even sure what kind of notifications will be expected and how to deliver them since different DE does it differently.

Per mount scripts is something i will do eventually.

In case you do not know, the SiriKali debug window can be activated by pressing "CTRL+D" key combo while SiriKali has focus. 

![Screenshot_20190513_125849](https://user-images.githubusercontent.com/3496115/57613238-111e3700-757f-11e9-94b2-61ebdcd82457.png)

**Comment by timoc** [comment]
Thanks - will try it out. 
- Did not know about the ctrl-d. maybe worth adding to somewhere the above screenshot?
- non zero return code to stsrem tray notification would be handy 
- credentials, and everything else should be passed in an evnironment variable, thats the current container best practice. Then it is up to the script to decide what it needs. Have to assume the script is authorised by the user to have that level of access.

**Comment by mhogomchungu** [comment]
Passing credentials to custom commands is a hard problem because its possible to:
1. Start SiriKali.
2. Unlock a volume.
3. Close SiriKali.
4. Start SiriKali.
5. Lock the unlocked volume.
6. Close SiriKali.

If SiriKali could hold on to credentials that were used to unlock a volume, then those credentials will be lost at step 3 above and your script will get see inconsistent behavior from SiriKali because from its perspective, it will be called sometimes with credentials and other times without them and i dont see how i can avoid this other than storing credentials to disk as SiriKali closing(Not going to do this) or preventing SiriKali from closing if it has unlocked volumes(Not going to do this either).

**Comment by timoc** [comment]
to make sure we are on the same page:
1- I assume that all scripts are subprocesses of a Sirikali process, and as such ENV variables can be set prior to it being called, and only vunerable as long as the subshell exists. The avaiilability of a given ENV property (e.g password) in the subshell would depend entirely on your intrepretation and/or availability of the property. 

2- I accept your point about when credentials are reasonably available. My encfs showcruft script would need them on every run. Pre-mount and post-mount credentials are also arguable, possibly optional?

3- It seems that the 'interval' script, if it is to have credentials, either has to persist them itself, or exist in a (sub)process for the lifecycle of the locked volume (beetween points 2 and 5 above), or only work in circumstances where the sirikali system tray is running, and sirikali can request/cache credentials prior to running the script.

**Comment by mhogomchungu** [comment]
1. Yes, all scripts are sub processes of SiriKali and SiriKali can pass them the credentials through setting an environmental variable before calling them or by calling them and then pass the credentials through the script's stdin. For this to work, SiriKali would have to maintain a data structure that keeps track of what volume was unlocked with what credentials. This data structure will be lost when SiriKali is restarted unless it is saved to disk when SiriKali is closed(Not doing this) or SiriKali is prevented from closing when atleast one volume is unlocked(Not doing this).

2. With the current implementation, your script will have to manage their own credentials either by asking the user on every run(bad user experience), or by asking them on first run and then cache it somehow like writing it to disk(bad idea).

An alternative that just came to mind and i can live with is to add an option to allow external commands to retrieve credentials from internal storage/kwallet/libsecret and SiriKali will retrieve the credentials and pass them to external commands ONLY if the option is set and the volume has an entry in the selected credential storage backend.

It seems dangerous to silently send credentials to external commands by default.

**Comment by mhogomchungu** [comment]
1. Update from git.
2. Go to menu->settings->manage keys in wallets and then set the wallet you want to use.
3. While at 2 above, click "key storage" and then select the entry you selected above.
4. In the window that will pop up, add your volume to the list.
5. Go the general options tab and then select "Allow external tools to get passwords from wallets".

Your interval script will now get the password you set in an environmental variable named "SiriKaliVolumeKey". The password wiil also be sent to the post mount script.

**Comment by mhogomchungu** [comment]
Would appreciate a comment if you managed or not to create a script that does what you want with the current SiriKali functionality.

**Comment by timoc** [comment]
I have to build the git version and the script. should have feedback next week.

**Comment by timoc** [comment]
1 Created test script:
```
#!/bin/env bash
echo "onedrive cruft: Checking $1 $2 $3"
```
2 added to monitor settings with refresh of 1
3 pressed control d for debug window
4 saw nothing in the log.

**Comment by mhogomchungu** [comment]
works fine here and your script produces the following entry in the debug window

The script will run after every interval minutes for each of the unlocked volume. Are you sure you tested with atleast one volume opened?

What are the contents of "~/.config/SiriKali/SiriKali.conf"


![Screenshot_20190523_200909](https://user-images.githubusercontent.com/3496115/58272288-ddb98480-7d96-11e9-8c66-ee247eaadd7f.png)
